/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using GemBox.Spreadsheet;
using OutSystems.RuntimeCommon;

namespace OutSystems.Spreadsheet {

    internal class GemboxReader : IExcelReader {

        static GemboxReader() {
            GemBoxLicensing.SetLicense();
        }

        private ExcelFile excelFile;
        protected ExcelWorksheet sheet;
        protected ExcelRow row = null;

        protected int currentrow = 0;

        private readonly string[] dataTypes;

        private readonly int fieldCount = 0;

        private readonly string[] attributeNames;
        private readonly string[] attributeLabels;
        private readonly string[] entityAttributeNames;
        private readonly string[] entityAttributeLabels;
        private readonly string[] originalHeaders;

        private readonly List<string> duplicateBindingLabels = new List<string>();

        private readonly int[] realIndices;

        private IEnumerable<ExcelWorksheet> _validEntityWorksheets;
        private IEnumerable<ExcelWorksheet> _workSheetsToProcess;
        private int _currentBootstrapWorksheet;

        private const int headerRow = 0;

        // Setting totalFields to -1 disables the "realIndices" feature
        public GemboxReader(string fileName, string sheetName = "", int totalFields = -1) {

            GetWorksheetFromFile(fileName, sheetName);
            if (totalFields == -1) {
                realIndices = Array.Empty<int>();
            } else {
                realIndices = new int[totalFields];
            }
            fieldCount = totalFields;
            if (fieldCount != -1) {
                for (int i = 0; i < realIndices.Length; ++i) {
                    realIndices[i] = i;
                }
            }
            try {
                row = sheet.Rows[headerRow];
            } catch {
            }
        }

        // Setting totalFields to -1 disables the "realIndices" feature
        public GemboxReader(byte[] fileContents, string sheetName, int totalFields) {

            GetWorksheetFromFile(fileContents, sheetName);
            if (totalFields == -1) {
                realIndices = Array.Empty<int>();
            } else {
                realIndices = new int[totalFields];
            }
            fieldCount = totalFields;
            if (fieldCount != -1) {
                for (int i = 0; i < realIndices.Length; ++i) {
                    realIndices[i] = i;
                }
            }
            try {
                row = sheet.Rows[headerRow];
            } catch {
            }
        }

        public GemboxReader(byte[] fileContents, string sheetName, int totalFields, string[] dataTypes, string[] attributeNames, string[] attributeLabels, string[] entityAttributeNames, string[] entityAttributeLabels) {

            GetWorksheetFromFile(fileContents, sheetName);
            this.dataTypes = dataTypes;
            this.attributeNames = attributeNames;
            this.attributeLabels = attributeLabels;
            this.entityAttributeNames = entityAttributeNames;
            this.entityAttributeLabels = entityAttributeLabels;

            realIndices = new int[attributeLabels.Length];
            originalHeaders = new string[attributeLabels.Length];

            for (int i = 0; i < GetRowCount(); i++) {
                int thisRowFieldCount = sheet.Rows[i].AllocatedCells.Count;
                while (thisRowFieldCount > 0 && sheet.Rows[i].Cells[thisRowFieldCount - 1].Value == null) {
                    thisRowFieldCount -= 1;
                }
                fieldCount = Math.Max(fieldCount, thisRowFieldCount);
            }
            try {
                row = sheet.Rows[headerRow];
                if (fieldCount != totalFields) {
                    fieldCount = 0;
                    for (int j = 0; j < attributeLabels.Length; ++j) {
                        realIndices[j] = -1;
                        for (int i = 0; i < row.AllocatedCells.Count; ++i) {
                            bool matched = false;

                            if (row.AllocatedCells[i].Value is string caption) {
                                if (caption.Contains(":")) {
                                    // this excel contains multiple records, look up in entityAttributelabels
                                    int separatorIndex = caption.IndexOf(":");
                                    string vEnt = caption.Substring(0, separatorIndex);
                                    string attribute = caption.Substring(separatorIndex + 1);
                                    if (vEnt + ":" + attribute == entityAttributeLabels[j] ||
                                        vEnt + ":" + attribute.FixName(/*extended*/false) == entityAttributeNames[j]) {
                                        matched = true;
                                    }
                                }

                                if (caption == attributeLabels[j] || caption.FixName(/*extended*/false) == attributeNames[j]) {
                                    matched = true;
                                }

                                if (matched) {
                                    if (realIndices[j] != -1) {
                                        duplicateBindingLabels.Add(caption);
                                    }
                                    realIndices[j] = i;
                                    originalHeaders[j] = caption;
                                    fieldCount += 1;
                                }
                            }
                        }
                    }
                } else {
                    for (int i = 0; i < realIndices.Length; ++i) {
                        realIndices[i] = i;
                        originalHeaders[i] = row.AllocatedCells[i].Value as string;
                    }
                }
            } catch {
            }
        }

        private void GetWorksheetFromFile(string fileName, string sheetName) {
            if (Path.GetExtension(fileName).EqualsIgnoreCase(".xls")) {
                excelFile = ExcelFile.Load(fileName, LoadOptions.XlsDefault);
            } else {
                excelFile = ExcelFile.Load(fileName);
            }

            if (!string.IsNullOrEmpty(sheetName)) {
                try {
                    sheet = excelFile.Worksheets[sheetName];
                } catch {
                    throw new InvalidOperationException("Error - '" + sheetName + "' sheet not found in excel file.");
                }
            } else {
                sheet = excelFile.Worksheets[0];
            }
        }

        private void GetWorksheetFromFile(byte[] fileContents, string sheetName) {
            try {
                using (MemoryStream stream = new MemoryStream(fileContents)) {
                    excelFile = ExcelFile.Load(stream, LoadOptions.XlsDefault);
                }
            } catch {
                using (MemoryStream stream = new MemoryStream(fileContents)) {
                    excelFile = ExcelFile.Load(stream, LoadOptions.XlsxDefault);
                }
            }

            if (!string.IsNullOrEmpty(sheetName)) {
                try {
                    sheet = excelFile.Worksheets[sheetName];
                } catch {
                    throw new InvalidOperationException("Error - '" + sheetName + "' sheet not found in excel file.");
                }
            } else {
                try {
                    sheet = excelFile.Worksheets["Sheet1"];
                } catch {
                    sheet = excelFile.Worksheets[0];
                }
            }
        }

        private HashSet<int> emptyRows = new HashSet<int>();

        public bool DataTypesValid(out string errorMsg) {
            errorMsg = string.Empty;
            if (dataTypes == null) {
                return true;
            }

            bool anyNonEmptyRealIndex = false;
            bool multipleBound = false;

            foreach (var duplicateBindingLabel in duplicateBindingLabels) {
                errorMsg += "Found duplicated '" + duplicateBindingLabel + "' column header in the Excel file.";
            }

            if (!duplicateBindingLabels.IsEmpty()) {
                return false;
            }

            HashSet<int> usedIndices = new HashSet<int>();
            for (int i = 0; i < realIndices.Length; i++) {
                if (realIndices[i] != -1) {
                    anyNonEmptyRealIndex = true;
                    if (!usedIndices.Contains(realIndices[i])) {
                        usedIndices.Add(realIndices[i]);
                    } else {
                        errorMsg += "Ambiguous binding of the '" + originalHeaders[i] + "' column header; prefix it with the entity name and a colon (':').\n";
                        multipleBound = true;
                    }
                }
            }

            if (multipleBound) {
                return false;
            }

            if (!anyNonEmptyRealIndex) {
                errorMsg = "None of the column headers match with the record attributes.";
                return false;
            }

            for (int rowIndex = 1; rowIndex <= RowCount; ++rowIndex) {
                bool anyCellFound = false;
                for (int fieldIndex = 0; fieldIndex < realIndices.Length; ++fieldIndex) {
                    int realIndex = realIndices[fieldIndex];
                    if (realIndex != -1) {
                        object cellValue = sheet.Cells[rowIndex, realIndex].Value;
                        if (cellValue != null) {
                            string cellType = cellValue.GetType().Name;

                            if (!TypeIsCompatible(dataTypes[fieldIndex], cellType, cellValue.ToString())) {
                                errorMsg = "Excel read error in row " + (rowIndex + 1) + ": Column '" + originalHeaders[fieldIndex] + "' has an invalid type. Expected a '" + dataTypes[fieldIndex] + "' but received a '" + cellType + "'.";
                                return false;
                            }
                            anyCellFound = true;
                        }
                    }
                }
                if (!anyCellFound) {
                    emptyRows.Add(rowIndex);
                }
            }

            return true;
        }

        public bool SetRow(int index) {
            if (index < GetRowCount()) {
                row = sheet.Rows[index];
                return true;
            }
            return false;
        }

        public int GetCellCount() {
            return row.AllocatedCells.Count;
        }

        public void GetCellPosition(string content, int row, out int column) {
            // the key column must be inside the first 10x10 square of cells
            for (column = 0; column < 10; column++) {
                object value = sheet.Cells[row, column].Value;
                if (value != null && value.ToString().EqualsIgnoreCase(content)) {
                    return;
                }
            }

            throw new Exception();
        }

        public void GetCellPosition(string content, out int row, out int column) {
            // the key column must be inside the first 10x10 square of cells
            for (column = 0; column < 10; column++) {
                for (row = 0; row < 10; row++) {
                    object value = sheet.Cells[row, column].Value;
                    if (value != null && value.ToString().EqualsIgnoreCase(content)) {
                        return;
                    }
                }
            }

            throw new Exception();
        }

        private bool TypeIsCompatible(string RLType, string ExcelType, string value) {
            var typeConversion = RLType + ">" + ExcelType;

            if (RLType == ExcelType || RLType == "String") {
                return true;
            }

            if (typeConversion == "Decimal>Int32" || typeConversion == "Decimal>Double" ||
                typeConversion == "DateTime>Double" || typeConversion == "Int32>Double" ||
                typeConversion == "Int64>Double" || typeConversion == "Int64>Int32") {
                return true;
            }

            if (typeConversion == "Decimal>String") {
                return ScriptableBuiltInFunction.TextToDecimalValidate(value);
            }

            if (typeConversion == "Int32>String") {
                return ScriptableBuiltInFunction.TextToIntegerValidate(value);
            }

            if (typeConversion == "Int64>String") {
                return ScriptableBuiltInFunction.TextToLongIntegerValidate(value);
            }

            if (typeConversion == "DateTime>String") {
                return ScriptableBuiltInFunction.TextToDateTimeValidate(value) ||
                       ScriptableBuiltInFunction.TextToDateValidate(value) ||
                       ScriptableBuiltInFunction.TextToTimeValidate(value);
            }

            return false;
        }

        private static readonly long TicksFrom1900_1_1 = new DateTime(1900, 1, 1).Ticks;

        public object GetValueAsObject(int i) {
            int realIndex = fieldCount == -1 ? i : realIndices[i];
            if (realIndex == -1) {
                return DBNull.Value;
            }

            return row.Cells[realIndex].Value;
        }

        public object GetValue(int i) {
            int realIndex = fieldCount == -1 ? i : realIndices[i];
            if (realIndex == -1) {
                return DBNull.Value;
            }

            object returnVal = row.Cells[realIndex].Value;

            if (returnVal == null) {
                returnVal = DBNull.Value;
            } else {

                if (dataTypes != null && dataTypes[i] == "DateTime") {
                    if (returnVal.GetType().Name == "Double") {
                        returnVal = DateTime.FromOADate((double)returnVal);
                    } else if (returnVal.GetType().Name == "String") {
                        string str = (string)returnVal;
                        if (str.IndexOf(" ") > 0) {
                            returnVal = ScriptableBuiltInFunction.TextToDateTime(str);
                        } else {
                            if (ScriptableBuiltInFunction.TextToTimeValidate(str)) {
                                returnVal = ScriptableBuiltInFunction.TextToTime(str);
                            } else {
                                returnVal = ScriptableBuiltInFunction.TextToDate(str);
                            }
                        }
                    }

                    // handle excel null dates for time values (30/12/1899)
                    var returnValDateTime = (DateTime)returnVal;
                    if (returnValDateTime.Year == 1899 &&
                        returnValDateTime.Month == 12 &&
                        returnValDateTime.Day == 30) {
                        return new DateTime(1900, 1, 1, returnValDateTime.Hour, returnValDateTime.Minute, returnValDateTime.Second);
                    }
                }

                if (dataTypes != null && dataTypes[i] == "Decimal" && returnVal.GetType().Name == "String") {
                    returnVal = ScriptableBuiltInFunction.TextToDecimal((string)returnVal);
                }

                if (dataTypes != null && dataTypes[i] == "Int32" && returnVal.GetType().Name == "String") {
                    returnVal = ScriptableBuiltInFunction.TextToInteger((string)returnVal);
                }

                if (dataTypes != null && dataTypes[i] == "Int64" && returnVal.GetType().Name == "String") {
                    returnVal = ScriptableBuiltInFunction.TextToLongInteger((string)returnVal);
                }

                if (returnVal is DateTime time && time.Ticks < TicksFrom1900_1_1) {
                    returnVal = time.AddDays(1);
                }
            }

            return returnVal;
        }

        public string GetString(int i) {
            int realIndex = fieldCount == -1 ? i : realIndices[i];
            if (realIndex == -1 || row.Cells[realIndex].Value == null) {
                return "";
            }
            try {
                return row.Cells[realIndex].Value.ToString();
            } catch {
                throw new Exception("Unexpected datatype.");
            }
        }

        public bool FilterValidEntityWorksheets(out string errorMessage) {
            errorMessage = "";

            if (excelFile.Worksheets.Count == 0) {
                errorMessage = "No Worksheets found in the Excel file.";
                return false;
            }

            var worksheets = excelFile.Worksheets.Cast<ExcelWorksheet>()
                                             .Where(workSheet => workSheet.Rows.Count >= 2);

            if (worksheets.IsEmpty()) {
                errorMessage = "No Worksheet with data was found in the Excel file.";
                return false;
            }

            var invalidWorkSheets = worksheets.Where(workSheet => (workSheet.Rows[0].Cells[0].Value as string).IsEmpty());
            worksheets = worksheets.Except(invalidWorkSheets);

            if (invalidWorkSheets.Any()) {
                errorMessage = invalidWorkSheets.Select(workSheet => "Definition of columns headers must start at the A1 cell in the '" + workSheet.Name + "' Worksheet.").StrCat("\n");
                if (worksheets.IsEmpty()) {
                    return false;
                }
            }

            var workSheetsWithRepeatedHeaders = worksheets.Where(workSheet => {
                var columnNames = new HashSet<string>();
                foreach (ExcelCell cell in workSheet.Rows[0].Cells) {
                    var excelColumnName = (cell.Value as string ?? string.Empty).ToLower();
                    if (excelColumnName.IsEmpty()) {
                        break;
                    }
                    if (columnNames.Contains(excelColumnName)) {
                        return true;
                    } else {
                        columnNames.Add(excelColumnName);
                    }
                }
                return false;
            });

            worksheets = worksheets.Except(workSheetsWithRepeatedHeaders);
            if (workSheetsWithRepeatedHeaders.Any()) {
                errorMessage = workSheetsWithRepeatedHeaders.Select(workSheet => "Columns headers must be unique in '" + workSheet.Name + "' Worksheet.").StrCat("\n");
                if (worksheets.IsEmpty()) {
                    return false;
                }
            }

            _validEntityWorksheets = worksheets;

            return true;
        }

        public int GetRowCount() {
            return sheet.Rows.Count;
        }
        public int GetColCount() {
            return sheet.Columns.Count;
        }

        public void SetWorksheet(int index) {
            sheet = excelFile.Worksheets[index];
            try {
                row = sheet.Rows[headerRow];
            } catch {
            }
        }

        public int GetWorksheetCount() {
            return excelFile.Worksheets.Count;
        }

        public IEnumerable<string> GetWorksheetNames() {
            return _validEntityWorksheets.Select(worksheet => worksheet.Name);
        }

        public void SetEntitiesToBootstrap(string bootstrapEntity) {

            _currentBootstrapWorksheet = -1;
            _workSheetsToProcess = _validEntityWorksheets;

            if (bootstrapEntity != "") {
                // try to find a worksheet with a name equal to the entity's name
                var workSheet = _validEntityWorksheets.Where(t => t.Name.EqualsIgnoreCase(bootstrapEntity)).FirstIfSingleOrDefault();
                // if not found, just use the first sheet found
                if (workSheet == null) {
                    workSheet = _validEntityWorksheets.ElementAt(0);
                }

                _workSheetsToProcess = new List<ExcelWorksheet>();
                (_workSheetsToProcess as List<ExcelWorksheet>).Add(workSheet);
            }
        }

        public bool NextEntity() {
            if (++_currentBootstrapWorksheet < _workSheetsToProcess.Count()) {
                SetWorksheet(_currentBootstrapWorksheet);
                return true;
            } else {
                return false;
            }
        }

        public string GetEntityName() {
            return _workSheetsToProcess.ElementAt(_currentBootstrapWorksheet).Name;
        }

        public bool NextResult() {
            return false;
        }

        public int Depth {
            get { return 0; }
        }

        public bool IsClosed {
            get { return currentrow == RowCount; }
        }

        public bool Read() {
            do {
                currentrow++;
            } while (emptyRows.Contains(currentrow));
            if (currentrow > RowCount) {
                return false;
            }

            row = sheet.Rows[currentrow];
            return true;
        }

        public int RecordsAffected {
            get { return 0; }
        }

        // without header
        private int RowCount {
            get { return GetRowCount() - 1; }
        }


        public int FieldCount {
            get { return fieldCount; }
        }

        public object this[string name] {
            get {
                throw new NotImplementedException();
            }
        }

        public object this[int i] {
            get {
                return GetValue(i);
            }
        }

        public void Close() { }

        public void Dispose() { }

        #region NotImplemented Region
        public DataTable GetSchemaTable() {
            throw new NotImplementedException();
        }

        public bool GetBoolean(int i) {
            throw new NotImplementedException();
        }

        public byte GetByte(int i) {
            throw new NotImplementedException();
        }

        public long GetBytes(int i, long fieldOffset, byte[] buffer, int bufferoffset, int length) {
            throw new NotImplementedException();
        }

        public char GetChar(int i) {
            throw new NotImplementedException();
        }

        public long GetChars(int i, long fieldoffset, char[] buffer, int bufferoffset, int length) {
            throw new NotImplementedException();
        }

        public IDataReader GetData(int i) {
            throw new NotImplementedException();
        }

        public string GetDataTypeName(int i) {
            throw new NotImplementedException();
        }

        public DateTime GetDateTime(int i) {
            throw new NotImplementedException();
        }

        public decimal GetDecimal(int i) {
            throw new NotImplementedException();
        }

        public double GetDouble(int i) {
            throw new NotImplementedException();
        }

        public Type GetFieldType(int i) {
            throw new NotImplementedException();
        }

        public float GetFloat(int i) {
            throw new NotImplementedException();
        }

        public Guid GetGuid(int i) {
            throw new NotImplementedException();
        }

        public short GetInt16(int i) {
            throw new NotImplementedException();
        }

        public int GetInt32(int i) {
            throw new NotImplementedException();
        }

        public long GetInt64(int i) {
            throw new NotImplementedException();
        }

        public string GetName(int i) {
            throw new NotImplementedException();
        }

        public int GetOrdinal(string name) {
            throw new NotImplementedException();
        }

        public int GetValues(object[] values) {
            throw new NotImplementedException();
        }

        public bool IsDBNull(int i) {
            throw new NotImplementedException();
        }

        #endregion NotImplemented Region
    }
}
