/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using GemBox.Spreadsheet;
using OutSystems.RuntimeCommon;
using System;
using System.Globalization;
using System.IO;

namespace OutSystems.Spreadsheet {

    internal class GemboxWriter : IExcelWriter {
        private const int MaxCellCharCount = 32_767;

        private ExcelFile _excelFile;
        private ExcelWorksheet _workSheet;

        private int _currentRow;
        private int _currentCell;

        private readonly bool _useXls;
        private readonly bool _sanitizeFormulas;
        private readonly bool _sanitizeNumbers;

        private LoadOptions GetLoadOptions =>  _useXls ? (LoadOptions)LoadOptions.XlsDefault : (LoadOptions)LoadOptions.XlsxDefault;

        private SaveOptions GetSaveOptions => _useXls ? (SaveOptions)SaveOptions.XlsDefault : (SaveOptions)SaveOptions.XlsxDefault;

        static GemboxWriter() {
            GemBoxLicensing.SetLicense();
        }

        public GemboxWriter(string sheetName = "Sheet1", bool useXls = false, bool sanitizeFormulas = false, bool sanitizeNumbers = true) {
            _excelFile = new ExcelFile();
            _workSheet = _excelFile.Worksheets.Add(sheetName);
            _currentRow = -1;
            _currentCell = -1;
            _useXls = useXls;
            _sanitizeFormulas = sanitizeFormulas;
            _sanitizeNumbers = sanitizeNumbers;
        }

        public GemboxWriter(Stream templateStream, bool useXls = false, bool sanitizeFormulas = false, bool sanitizeNumbers = true) {
            _currentRow = -1;
            _currentCell = -1;
            _useXls = useXls;
            _sanitizeFormulas = sanitizeFormulas;
            _sanitizeNumbers = sanitizeNumbers;

            _excelFile = ExcelFile.Load(templateStream, GetLoadOptions); // set _useXls first
            _workSheet = _excelFile.Worksheets[0];
        }

        public void CreateRow(int index) {
            _currentRow = index;
            _currentCell = -1;
        }

        public void CreateRow(int index, int colOffset) {
            _currentRow = index;
            _currentCell = colOffset - 1;
        }

        public void SkipCell() {
            _currentCell++;
        }

        public void CreateCell(object data) {
            _currentCell++;
            _workSheet.Cells[_currentRow, _currentCell].Value = SanitizeData(data);
        }

        private object SanitizeData(object data) {
            if (data is string str) {
                if (_sanitizeFormulas && (str.StartsWith("=") || str.StartsWith("-") || str.StartsWith("+") || str.StartsWith("@"))) {
                    if (!IsValidNumber(str)) {
                        return "'" + str;
                    }
                }
                return str.Left(MaxCellCharCount); // Max number of characters that a cell can contain.
            }

            return data;
        }

        private bool IsValidNumber(string value) {
            if (_sanitizeNumbers) {
                return false;
            }
            // The output of TryParse depends on the CurrentCulture of the server.
            // If it fails to parse with it, then it falls back to Invariant Culture.
            return double.TryParse(value, NumberStyles.Number, CultureInfo.CurrentCulture, out _)
                || double.TryParse(value, NumberStyles.Number, CultureInfo.InvariantCulture, out _);
        }

        public void CreateCellTime(object data) {
            _currentCell++;

            if (data is DateTime) {
                _workSheet.Cells[_currentRow, _currentCell].Value = data;
                _workSheet.Cells[_currentRow, _currentCell].Style.NumberFormat = FormatInfoLogic.GetOutputTimeFormatString().ToLower();
            }
        }

        public void CreateCellDate(object data) {
            _currentCell++;

            if (data is DateTime) {
                _workSheet.Cells[_currentRow, _currentCell].Value = data;
                _workSheet.Cells[_currentRow, _currentCell].Style.NumberFormat = FormatInfoLogic.GetOutputDateFormatString().ToLower();
            }
        }

        public void CreateCellDateTime(object data) {
            _currentCell++;

            if (data is DateTime) {
                _workSheet.Cells[_currentRow, _currentCell].Value = data;
                _workSheet.Cells[_currentRow, _currentCell].Style.NumberFormat = FormatInfoLogic.GetOutputDateTimeFormatString().ToLower();
            }
        }

        public void GetCellPosition(string content, int row, out int column) {
            // the key column must be inside the first 10x10 square of cells
            for (column = 0; column < 10; column++) {
                object value = _workSheet.Cells[row, column].Value;
                if (value != null && value.ToString().EqualsIgnoreCase(content)) {
                    return;
                }
            }
        }

        public void GetCellPosition(string content, out int row, out int column) {
            // the key column must be inside the first 10x10 square of cells
            row = 0;
            for (column = 0; column < 10; column++) {
                for (row = 0; row < 10; row++) {
                    object value = _workSheet.Cells[row, column].Value;
                    if (value != null && value.ToString().EqualsIgnoreCase(content)) {
                        return;
                    }
                }
            }
        }

        public void DoubleDefaultColumnWidth() {
            _workSheet.DefaultColumnWidth *= 2;
        }

        public void CopyColumnWidth(int targetCol, int sourceCol) {
            _workSheet.Columns[targetCol].Width = _workSheet.Columns[sourceCol].Width;
        }

        public void CopyStyle(int targetRow, int targetCol, int sourceRow, int sourceCol) {
            _workSheet.Cells[targetRow, targetCol].Style = _workSheet.Cells[sourceRow, sourceCol].Style;
        }

        public void DeleteColumn(int index) {
            _workSheet.Columns.Remove(index);
        }

        public byte[] Save() {
            using (MemoryStream stream = new MemoryStream()) {
                _excelFile.Save(stream, GetSaveOptions);
                return stream.ToArray();
            }
        }

        public void Write(string filename) {
            _excelFile.Save(filename, GetSaveOptions);
        }
    }
}
