/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("OutSystems.RESTService.Runtime")]
[assembly: InternalsVisibleTo("OutSystems.RESTService.Runtime.Core")]

[assembly: InternalsVisibleTo("OutSystems.Application.Initialization.ASPNet")]
[assembly: InternalsVisibleTo("OutSystems.Application.Initialization.ASPNetCore")]

[assembly: InternalsVisibleTo("OutSystems.Server.TestsCommon")]
[assembly: InternalsVisibleTo("ServerTests")]
[assembly: InternalsVisibleTo("PlatformDatabaseProvider.Tests")]
[assembly: InternalsVisibleTo("RuntimePlatform.Tests")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: InternalsVisibleTo("OutSystems.RuntimePlatform.Tests")]
[assembly: InternalsVisibleTo("OutSystems.Application.Initialization.ASPNetCore.Tests")]

#if RUNNING_ON_NET_4_6_1 || NET461
#if INTEGRATION_STUDIO
[assembly: AssemblyTrademark("net461+IntegrationStudio")]
#else
[assembly: AssemblyTrademark("net461")]
#endif
#elif RUNNING_ON_NET_4_7_2 || NET472
[assembly: AssemblyTrademark("net472")]
#elif NETSTANDARD2_0
[assembly: AssemblyTrademark("netstandard2.0")]
#endif
