/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Collections.Concurrent;
using OutSystems.Application.Session.Abstractions;

namespace OutSystems.Application.Session {
    public class SessionHashtable : ISessionHashtable {
        private ConcurrentDictionary<string, object> deserialized = new ConcurrentDictionary<string, object>();

        public object this[string key] {
            get {
                if (deserialized.ContainsKey(key))
                    return deserialized[key];

                return null;
            }
            set {
                deserialized[key] = value;
            }
        }
    }
}
