/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Data;
using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.Platform.QueryProvider;
using OutSystems.Internal.Db;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.RuntimePlatform.RuntimePublic.Db {
    [DatabaseProviderSpecificImplementationFor("Oracle")]
    internal class DBProcessOracle : DBProcess {
        protected override string ProcToDeleteTableName => "OSSYS_BPM_PROCESS_CLEANUP_IDS";

        public override IDatabaseProvider DatabaseProvider {
            get { return DatabaseAccess.ForRuntimeDatabase.DatabaseServices.DatabaseConfiguration.DatabaseProvider; }
        }

        /// <summary>
        /// Main method of the Processes Delete where it's define the ORACLE SQL flow
        /// </summary>
        /// <param name="trans"></param>
        /// <param name="processId"></param>
        /// <param name="olderThan"></param>
        /// <param name="bulkSizeLimit"></param>
        /// <param name="processDefinitionId"></param>
        internal override void DeleteProcesses(Transaction trans, int? processId, DateTime? olderThan, int? bulkSizeLimit, int? processDefinitionId) {
            OSTrace.Debug($"Running DeleteProcesses. processId: {processId} olderThan: {olderThan} bulkSizeLimit: {bulkSizeLimit} processDefinitionId: {processDefinitionId}");

            FillProcToDeleteTable(trans, processId, olderThan, bulkSizeLimit, processDefinitionId);
            RemoveCircularReferences(trans);
            InnerDeleteProcesses(trans, processId, olderThan, processDefinitionId);
        }

        /// <summary>
        /// Fills the global temporary table ProcIds with the ID of all processes to be deleted
        /// </summary>
        /// <param name="trans"></param>
        /// <param name="processId"></param>
        /// <param name="olderThan"></param>
        /// <param name="bulkSizeLimit"></param>
        /// <param name="processDefinitionId"></param>
        private void FillProcToDeleteTable(Transaction trans, int? processId, DateTime? olderThan, int? bulkSizeLimit, int? processDefinitionId) {
            OSTrace.Debug($"Running DeleteProcesses.FillProcToDeleteTable. processId: {processId} olderThan: {olderThan} bulkSizeLimit: {bulkSizeLimit} processDefinitionId: {processDefinitionId}");

            if (bulkSizeLimit == 0) {
                bulkSizeLimit = null;
            }

            string sql =
                $@"INSERT INTO {ProcToDeleteTableName}
                SELECT
                    ID 
                FROM (
                    SELECT 
                        ID 
                    FROM  
                        OSSYS_BPM_PROCESS
                    WHERE 
                        TOP_PROCESS_ID IN 
                        (
                            SELECT * FROM (
                                SELECT :PROCESSID FROM DUAL
                                    WHERE :PROCESSID IS NOT NULL
                                UNION
                                SELECT OSSYS_BPM_PROCESS.ID FROM OSSYS_BPM_PROCESS
                                    JOIN OSSYS_BPM_PROCESS_STATUS STATUS ON STATUS_ID = STATUS.ID
                                WHERE 
                                    STATUS.IS_TERMINAL = 1 
                                    AND PARENT_PROCESS_ID IS NULL 
                                    AND LAST_MODIFIED < :OLDERTHAN
                                    AND (:PROCESSDEFINITIONID IS NULL OR OSSYS_BPM_PROCESS.PROCESS_DEF_ID = :PROCESSDEFINITIONID)
                                    AND :PROCESSID IS NULL
                            )
                        )
                  ORDER BY ID DESC
                  )
                  {(bulkSizeLimit.HasValue ? "WHERE ROWNUM <= :BULKZISELIMIT" : "")}";

            using (var cmd = trans.CreateCommand(sql)) {
                cmd.CreateParameter("PROCESSID", DbType.Int32, processId);
                cmd.CreateParameter("BULKZISELIMIT", DbType.Int32, bulkSizeLimit);
                cmd.CreateParameter("OLDERTHAN", DbType.DateTime, olderThan);
                cmd.CreateParameter("PROCESSDEFINITIONID", DbType.Int32, processDefinitionId);

                cmd.ExecuteNonQuery();
            }
        }

        /// <summary>
        /// Delete the processes
        /// </summary>
        /// <param name="trans"></param>
        /// <param name="processId"></param>
        /// <param name="olderThan"></param>
        /// <param name="processDefinitionId"></param>
        private void InnerDeleteProcesses(Transaction trans, int? processId, DateTime? olderThan, int? processDefinitionId) {
            OSTrace.Debug($"Running DeleteProcesses.InnerDeleteProcesses. processId: {processId} olderThan: {olderThan} processDefinitionId: {processDefinitionId}");

            string sql =
                $@"DECLARE
                ROW_CNT NUMBER := 1; 
                
                BEGIN
                WHILE ROW_CNT > 0 LOOP
                    DELETE FROM OSSYS_BPM_PROCESS
                    WHERE ID IN (SELECT PROCESS_ID FROM {ProcToDeleteTableName})
                    AND ROWNUM <= {IterationSizeLimit};
                    
                    ROW_CNT := SQL%ROWCOUNT; 
                END LOOP;
                END;";

            CommandDeleteProcessesExecute(trans, sql, processId, olderThan, processDefinitionId);
        }
    }
}