/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using OutSystems.HubEdition.DatabaseAbstractionLayer.Platform.Configuration.ScriptParser;
using OutSystems.HubEdition.DatabaseProvider.SqlServer.ConfigurationService;
using OutSystems.HubEdition.DatabaseProvider.SqlServer.Platform.Configuration.ScriptParser;
using OutSystems.HubEdition.Extensibility.Data.ConfigurationService;
using OutSystems.HubEdition.Extensibility.Data.Platform.Configuration;

namespace OutSystems.HubEdition.DatabaseProvider.SqlServer.Platform.Configuration {

    public class SessionConfigurationManager : AbstractSessionConfigurationManager {

        public SessionConfigurationManager(ISessionDatabaseConfiguration sessionConfiguration)
            : base(sessionConfiguration) {
            preProcessedStatements = new ArrayList();
            InitializeDictionaries();
        }        

        public SessionConfigurationManager(ISessionDatabaseConfiguration sessionConfiguration, IPlatformDatabaseConfiguration platformConfiguration)
            : base(sessionConfiguration) {
            preProcessedStatements = new ArrayList();
            this.platformConfiguration = platformConfiguration;
            InitializeDictionaries();
        }

        private readonly IPlatformDatabaseConfiguration platformConfiguration;

        private void InitializeDictionaries() {
            scriptsTokenReplacements = new Dictionary<string, string>(){
                    {TAG_CATALOG, ((SessionDatabaseConfiguration)sessionConfiguration).Catalog},
                    {TAG_USERNAME, ((SessionDatabaseConfiguration)sessionConfiguration).SessionUser},
                    {TAG_ROWCOUNT, ((SessionDatabaseConfiguration)sessionConfiguration).DeleteExpiredSessionsAvoidLockRowCount.ToString()},
                    {TAG_VARSROWCOUNT, ((SessionDatabaseConfiguration)sessionConfiguration).DeleteExpiredSessionVarsAvoidLockRowCount.ToString()},
                    {TAG_PASSWORD, ((SessionDatabaseConfiguration)sessionConfiguration).SessionPassword },
                    {TAG_AUTH, ((SessionDatabaseConfiguration) sessionConfiguration).AuthenticationMode == AuthenticationType.Windows_Authentication ? "windows" : "sql"},
                    {TAG_OSADMINUSERNAME, ((PlatformDatabaseConfiguration)platformConfiguration).AdminUser }
                };
        }

        public override IEnumerable<IDatabaseScriptFile> CreationScriptFiles {
            get {
                yield return new DatabaseScriptFile(ScriptPath, "session_creation_sqlserver.sql");
                yield return new DatabaseScriptFile(ScriptPath, "session_creation_azure_01_masterdatabase.sql");
                yield return new DatabaseScriptFile(ScriptPath, "session_creation_azure_02_targetdatabase.sql");
            }
        }
        public override IEnumerable<IDatabaseScriptFile> ModelScriptFiles {
            get {
                yield return new DatabaseScriptFile(ScriptPath, "session_model_sqlserver.sql");
            }
        }

        private readonly ArrayList preProcessedStatements;

        private void NormalizeWindowsUser() {
            var sessionConf = (SessionDatabaseConfiguration)sessionConfiguration;

            if (sessionConf.AuthenticationMode != AuthenticationType.Windows_Authentication) {
                return;
            }

            sessionConf.SessionUser = WindowsUser.Normalize(sessionConf.SessionUser);
        }

        private void NormalizeAdminWindowsUser() {
            var platformConf = (PlatformDatabaseConfiguration)platformConfiguration;

            if (platformConf.AuthenticationMode != AuthenticationType.Windows_Authentication) {
                return;
            }

            platformConf.AdminUser = WindowsUser.Normalize(platformConf.AdminUser);
        }


        public override bool RequiresElevatedPrivileges() {
            return true;
        }

        public static string StatePermissionsScriptName {
            get {
                return "session_statepermissions_sqlserver.sql";
            }
        }

        internal VirtualDatabaseScriptFile StatePermissionScript() {
            var stateFileContent = @"/*  
Session Database Permission Statements Script 
NOTE: Make sure you have run the specific model script(s) for your database before running this script 
*/
            ";
            stateFileContent += ConfigurationManagerUtils.SQLGetStatePermissionStatement();
            return new VirtualDatabaseScriptFile(StatePermissionsScriptName, stateFileContent);
        }

        internal static string ReadMeTextFileName {
            get {
                return "README.txt";
            }
        }

        VirtualDatabaseScriptFile ReadMeTextFile() {
            return new VirtualDatabaseScriptFile(ReadMeTextFileName,
                @"To install the Session Database run the following SQL scripts in order:

1. Run the creation script(s) according to your database (check the comments in the file header(s) for more information):
    a. For SQL Server, run session_creation_sqlserver.sql
    b. For Azure SQL, run session_creation_azure_01_masterdatabase.sql and session_creation_azure_02_targetdatabase.sql

2. Run session_model_sqlserver.sql

3. Run session_statepermissions_sqlserver.sql");
        }

        public override IEnumerable<IDatabaseScriptFile> GenerateCreationScripts() {
            NormalizeWindowsUser();
            NormalizeAdminWindowsUser();

            //session database model
            List<IDatabaseScriptFile> scripts = new List<IDatabaseScriptFile>();
            foreach (var setupScript in CreationScriptFiles) {
                scripts.Add(new DatabaseStatementProcessor(setupScript, scriptsTokenReplacements, null));
            }

            foreach (var modelScript in ModelScriptFiles) {
                scripts.Add(new DatabaseStatementProcessor(modelScript, scriptsTokenReplacements, null));
            }

            var stateFileContent = @"/*  
Session Database Permission Statements Script 
NOTE: Make sure you have run the specific model script(s) for your database before running this script 
*/
            ";
            stateFileContent += ConfigurationManagerUtils.SQLGetStatePermissionStatement();
            scripts.Add(StatePermissionScript());

            scripts.Add(ReadMeTextFile());

            return scripts;
        }

        public override void Pre_CreateOrUpgradeSession() {
            NormalizeWindowsUser();

            var elevated = (IElevatedUserConfiguration)sessionConfiguration;

            var masterElevated = ConfigurationManagerUtils.ConfigurationToMaster(elevated);

            var runtimeElevated = (RuntimeDatabaseConfiguration)elevated.ElevatedRuntimeDatabaseConfiguration();

            ConfigurationManagerUtils.TestCredentials(masterElevated);

            bool isAzureDb = ConfigurationManagerUtils.IsDatabaseAzure(masterElevated);
            
            ConfigurationManagerUtils.CheckIfUserHasNecessaryElevatedPermissions(masterElevated, runtimeElevated);

            if (!isAzureDb) {
                ConfigurationManagerUtils.CreateSqlServerCatalogIfDoesntExist(masterElevated, runtimeElevated.Catalog, /*RecoveryMode*/ ConfigurationManagerUtils.DBRecoveryMode.Simple);
            } else {
                // We will not support automatically creating Azure databases.
                // An appropriate message is displayed.
                ConfigurationManagerUtils.CheckIfAzureDatabaseExists(masterElevated, runtimeElevated.Catalog);
            }

            // Prepare statements
            preProcessedStatements.Add(ConfigurationManagerUtils.GrantSessionUserPermissions(
                (SessionDatabaseConfiguration)sessionConfiguration,
                (PlatformDatabaseConfiguration)platformConfiguration));
        }

        public override IEnumerable<string> SessionStatements {
            get {
                NormalizeWindowsUser();

                foreach(var modelScript in ModelScriptFiles) {
                    string script = modelScript.ReadScriptFile();
                    StringBuilder str = new StringBuilder();

                    // read the entire script
                    var reader = new StringReader(script);
                    string line = reader.ReadLine();
                    while (line != null) {
                        if (line.Trim() == ConfigurationManagerUtils.StatementSeparator) {
                            //Add to the list of commands
                            string command = str.ToString();
                            command = DatabaseStatementProcessor.ReplaceTokens(command, scriptsTokenReplacements);
                            yield return command;

                            str = new StringBuilder();
                        } else if (line != string.Empty) {
                            str.AppendLine(line);
                        }
                        line = reader.ReadLine();
                    }

                    // Add pre processed statements
                    foreach (string preProcessedStatement in preProcessedStatements) {
                        yield return preProcessedStatement;
                    }
                }
            }
        }

        public override bool TestSessionConnection(out string friendlyMessage) {
            NormalizeWindowsUser();
            bool result = base.TestSessionConnection(out friendlyMessage);
            ConfigurationManagerUtils.CheckSessionRoles(sessionConfiguration, out friendlyMessage);
            return result;
        }

        public override int QueryTimeout {
            set {
                ConfigurationManagerUtils.queryTimeout = value;
            }
        }
    }
}