/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Data;
using OutSystems.HubEdition.Extensibility.Data.Platform.QueryProvider;
using OutSystems.Internal.Db;

namespace OutSystems.Application.Session.Data {
    [DatabaseProviderSpecificImplementationFor("Oracle")]
    internal class DBSessionMetadataOracle : DBSessionMetadata {
        internal override int ExecuteNonQueryGetIdentity(Command cmd, string idColumnName, string description) {
            cmd.CommandText = cmd.CommandText + " RETURNING " + idColumnName.ToUpper() + " INTO @id";

            DataParameter IdParamenter = cmd.CreateOutputParameter("@id", DbType.Int32);
            cmd.ExecuteNonQuery(description, true);
            return DataReaderUtils.SafeGet<int>(IdParamenter.Value);
        }
    }
}
