/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Collections.Generic;
using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;

namespace OutSystems.HubEdition.Extensibility.Data.IntrospectionService {

    /// <summary>
    /// Inspects a database server to retrieve information about its data model.
    /// Allows pagination of the list of table sources.
    /// </summary>
    public interface IIntrospectionServiceWithPagination : IIntrospectionService {

        /// <summary>
        /// Returns a list of table sources starting at specified offset with a max number of results less or equal than limit (e.g. tables, views) that belong to a given database. 
        /// </summary>
        /// <param name="database">Database from which we want to fetch the list of tables</param>
        /// <param name="isTableSourceToIgnore">The delegate to call to see if the table source should be ignored and excluded from the returned list</param>
        /// <param name="limit">Limit of results that we want to retrieve</param>
        /// <param name="offset">Starting index of the results</param>
        /// <param name="total">Total number of tables</param>  
        /// <returns>List of table sources paginated, in the given database</returns>
        IEnumerable<ITableSourceInfo> ListTableSources(IDatabaseInfo database, IsTableSourceToIgnore isTableSourceToIgnore, int limit, int offset, out int total);
    }
}
