/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NLog;
using NLog.Common;
using NLog.Config;
using NLog.Targets;
using NLog.Targets.Wrappers;
using OutSystems.Logging.LogDefinition;
using OutSystems.RuntimeCommon;
using OutSystems.RuntimeCommon.Extensibility.Plugins;
using OutSystems.RuntimeCommon.Log;
using OutSystems.RuntimeCommon.Settings;

namespace OutSystems.Logging.Implementations {
    public class NLogLoggerImplementation : LoggerImplementation {
        private const string TruncatedLogMessageSuffix = "\r\n<Message truncated in logging because it exceeded the maximum size>";

        private readonly string loggerIdentity = Guid.NewGuid().ToString();
        private readonly ConcurrentDictionary<Type, Target> targets = new ConcurrentDictionary<Type, Target>();
        private readonly ISettingsProvider settingsProvider;
        private readonly IEnumerable<ILoggingTargetFactory> targetFactories;
        private readonly Func<Target, WrapperTargetBase> extraTargetWrapper;

        private readonly int maxMessagesSizeInKbForLargeContentQueues;

        public NLogLoggerImplementation(IServiceProvider serviceProvider, Func<Target, WrapperTargetBase> extraTargetWrapper = null) {
            this.settingsProvider = serviceProvider.GetRequiredService<ISettingsProvider>();
            this.extraTargetWrapper = extraTargetWrapper;

            var pluginProvider = serviceProvider.GetRequiredService<AbstractPluginProvider<string, ILoggingPlugin>>();

            this.targetFactories = pluginProvider.Implementations
                                                 .Where(impl => impl.AppliesTo(settingsProvider))
                                                 .OrderByDescending((plugin) => plugin.Priority)
                                                 .Select(impl => impl.GetLoggingTargetFactory(serviceProvider))
                                                 .ToArray();

            this.maxMessagesSizeInKbForLargeContentQueues = settingsProvider.Get(LoggerSettings.MaxMessagesSizeInKbForLargeContentQueues) * 1000;
        }

        public virtual void OnAfterSend(Exception ex) {
            if (ex != null) {
                EventLogger.WriteError(ex);
            }
        }

        public override void SetUp() {
            if (LogManager.Configuration == null) { // Ensure we have a configuration object even if there is no config file
                LogManager.Configuration = new LoggingConfiguration();
            }

            int factoryCount = targetFactories.Count();

            Dictionary<Type, List<Target>> targetsToAdd = new Dictionary<Type, List<Target>>() {
                { typeof(ErrorLogDefinition), new List<Target>(factoryCount) } ,
                { typeof(GeneralLogDefinition), new List<Target>(factoryCount) } ,
                { typeof(ScreenLogDefinition), new List<Target>(factoryCount) } ,
                { typeof(CyclicJobLogDefinition), new List<Target>(factoryCount) } ,
                { typeof(ExtensionLogDefinition), new List<Target>(factoryCount) } ,
                { typeof(CustomLogDefinition), new List<Target>(factoryCount) } ,
                { typeof(IntegrationLogDefinition), new List<Target>(factoryCount) } ,
                { typeof(MobileRequestLogDefinition), new List<Target>(factoryCount) } ,
                { typeof(ServiceAPILogDefinition), new List<Target>(factoryCount) } ,
                { typeof(IntDetailLogDefinition), new List<Target>(factoryCount) } ,
                { typeof(MRDetailLogDefinition), new List<Target>(factoryCount) } ,
                { typeof(ServiceAPIDetailLogDefinition), new List<Target>(factoryCount) } ,
                { typeof(RequestEventDefinition), new List<Target>(factoryCount) }
            };

            foreach (ILoggingTargetFactory factory in targetFactories) {
                try {
                    targetsToAdd[typeof(ErrorLogDefinition)].Add(factory.CreateTargetForErrorLogs());
                    targetsToAdd[typeof(GeneralLogDefinition)].Add(factory.CreateTargetForGeneralLogs());
                    targetsToAdd[typeof(ScreenLogDefinition)].Add(factory.CreateTargetForScreenLogs());
                    targetsToAdd[typeof(CyclicJobLogDefinition)].Add(factory.CreateTargetForCyclicJobLogs());
                    targetsToAdd[typeof(ExtensionLogDefinition)].Add(factory.CreateTargetForExtensionLogs());
                    targetsToAdd[typeof(CustomLogDefinition)].Add(factory.CreateTargetForCustomLogs());
                    targetsToAdd[typeof(IntegrationLogDefinition)].Add(factory.CreateTargetForIntegrationLogs());
                    targetsToAdd[typeof(MobileRequestLogDefinition)].Add(factory.CreateTargetForMobileRequestLogs());
                    targetsToAdd[typeof(ServiceAPILogDefinition)].Add(factory.CreateTargetForServiceAPILogs());
                    targetsToAdd[typeof(IntDetailLogDefinition)].Add(factory.CreateTargetForIntDetailLogs());
                    targetsToAdd[typeof(MRDetailLogDefinition)].Add(factory.CreateTargetForMRDetailLogs());
                    targetsToAdd[typeof(ServiceAPIDetailLogDefinition)].Add(factory.CreateTargetForServiceAPIDetailLogs());
                    targetsToAdd[typeof(RequestEventDefinition)].Add(factory.CreateTargetForRequestEvents());
                } catch (Exception e) {
                    // This catch is required to avoid a null RuntimeLogger instance
                    // that would translate to no logs for no factory
                    EventLogger.WriteError(e);
                }
            }

            foreach (KeyValuePair<Type, List<Target>> typeTargets in targetsToAdd) {
                AddLogTarget(typeTargets.Key, typeTargets.Value, GetLogTypeSettings(typeTargets.Key));
            }

            if (settingsProvider.Get(LoggerSettings.EnableNLogInternalLogging)) {
                InternalLogger.LogFile = settingsProvider.Get(LoggerSettings.NLogInternalLoggingFile);
                InternalLogger.LogLevel = LogLevel.Trace;
            }

            LogManager.ReconfigExistingLoggers();
        }

        public override void Log(ScreenLogDefinition log) {
            SendLog(log);
        }

        public override void Log(ExtensionLogDefinition log) {
            SendLog(log);
        }

        public override void Log(GeneralLogDefinition log) {
            SendLog(log);
        }

        public override void Log(ErrorLogDefinition log) {
            SendLog(log);
        }

        public override void Log(CyclicJobLogDefinition log) {
            SendLog(log);
        }

        public override void Log(CustomLogDefinition log) {
            if (!settingsProvider.Get(LoggerSettings.SupportBulkLogs)) {
                throw new NotSupportedException("Bulk logs not supported in this installation. Please contact {C}.".ReplaceBranding());
            }

            if (!settingsProvider.Get(LoggerSettings.SupportCustomLogs)) {
                throw new NotSupportedException("Custom Logs not supported in this installation. Please contact {C} support.".ReplaceBranding());
            }

            SendLog(log);
        }

        public override void Log(IntegrationLogDefinition log) {
            SendLog(log);
        }

        public override void Log(IntDetailLogDefinition log) {
            log.Detail = TruncateLogMessage(log.Detail, maxMessagesSizeInKbForLargeContentQueues);

            SendLog(log);
        }

        public override void Log(RequestEventDefinition log) {
            SendLog(log);
        }

        public override void Log(MobileRequestLogDefinition log) {
            SendLog(log);
        }

        public override void Log(MRDetailLogDefinition log) {
            log.Detail = TruncateLogMessage(log.Detail, maxMessagesSizeInKbForLargeContentQueues);

            SendLog(log);
        }

        public override void Log(ServiceAPILogDefinition log) {
            SendLog(log);
        }

        public override void Log(ServiceAPIDetailLogDefinition log) {
            log.Detail = TruncateLogMessage(log.Detail, maxMessagesSizeInKbForLargeContentQueues);

            SendLog(log);
        }

        public override void Stop() {
            base.Stop();

            foreach (var logType in targets.Keys.ToArray()) {
                if (targets.TryRemove(logType, out Target target) && target != null) {
                    string registedTargetName = GetTargetNameUsedForConfiguration(logType);
                    LogManager.Configuration.RemoveTarget(registedTargetName);
                    target.Dispose(); // The RemoveTarget should close it internally, but lets make sure we Dispose it
                }
            }
        }

        private void SendLog<T>(T log) {
            var targetType = typeof(T);

            if (targets.TryGetValue(targetType, out var target) && target != null) { // Only deliver logs if there are targets defined for them
                var syncEvent = new OutSystemsLogEventInfo(log as AbstractLogDefinition);
                AsyncLogEventInfo @event = new AsyncLogEventInfo(syncEvent, OnAfterSend);
                target.WriteAsyncLogEvent(@event);
            }
        }

        private void AddLogTarget(Type logType, List<Target> finalTargets, LoggerSettings.LogTargetConfigurationSet config) {
            if (!finalTargets.IsNullOrEmpty()) { // Only register targets if there are implementations
                var registeredTarget = WrapTargetAndRegister(logType, finalTargets, config);
                if (registeredTarget != null) {
                    targets[logType] = registeredTarget;
                } else {
                    //LogType doesn't have any targets, so we skip it
                }
            }
        }

        private Target WrapTargetAndRegister(Type logType, List<Target> targets, LoggerSettings.LogTargetConfigurationSet config) {
            if (targets.IsNullOrEmpty()) {
                return null;
            }

            var internalLoggingEnabled = settingsProvider.Get(LoggerSettings.EnableNLogInternalLogging);

            var destinationTargets = targets
                                .Where(t => t != null)
                                .Select(t => {
                                    if (extraTargetWrapper != null) {
                                        t = extraTargetWrapper(t);
                                    }

                                    if (internalLoggingEnabled) {
                                        t = new TracingTarget(t);
                                    }

                                    Target buffer = CreateBufferTarget(t, logType, config);
                                    return CreateAsyncTarget(buffer, logType, config);
                                }).ToArray();
            Target finalTarget;

            if (destinationTargets.IsEmpty()) {
                return null;
            } else if (destinationTargets.Length == 1) {
                finalTarget = destinationTargets.First();
            } else {
                //We only need SplitGroupTarget if we have it configured for multiple plugins
                finalTarget = new OutSystemsSplitGroupTarget(destinationTargets);
            }

            LogManager.Configuration.AddTarget(GetTargetNameUsedForConfiguration(logType), finalTarget);

            return finalTarget;
        }

        private Target CreateAsyncTarget(Target innerTarget, Type logType, LoggerSettings.LogTargetConfigurationSet config) {
            return new AsyncTargetWrapper(
                                                    innerTarget,
                                                    settingsProvider.Get(config.MaxMessagesInQueue),
                                                    ParseOverflowActionFromString(
                                                        settingsProvider.Get(config.OnQueueOverflowAction))) {
                Name = "AsyncTargetFor" + logType.Name,
                FullBatchSizeWriteLimit = 15
            };
        }

        private Target CreateBufferTarget(Target innerTarget, Type logType, LoggerSettings.LogTargetConfigurationSet config) {
            return new BufferingTargetWrapper(
                                                    innerTarget,
                                                    settingsProvider.Get(config.MaxMessagesPerBatch),
                                                    settingsProvider.Get(config.TimeToWaitBetweenBatchInMs),
                                                    overflowAction: BufferingTargetWrapperOverflowAction.Flush) {
                Name = "BufferingTargetFor" + logType.Name,
                SlidingTimeout = false
            };
        }

        private static AsyncTargetWrapperOverflowAction ParseOverflowActionFromString(string overflowAction) {
            return (AsyncTargetWrapperOverflowAction)Enum.Parse(typeof(AsyncTargetWrapperOverflowAction), overflowAction, true);
        }

        private string GetTargetNameUsedForConfiguration(Type logType) {
            return loggerIdentity + "|" + logType.Name + "Target";
        }


        private LoggerSettings.LogTargetConfigurationSet GetLogTypeSettings(Type logType) {
            if (typeof(ErrorLogDefinition).Equals(logType)) {
                return LoggerSettings.ErrorLog;
            } else if (typeof(GeneralLogDefinition).Equals(logType)) {
                return LoggerSettings.GeneralLog;
            } else if (typeof(ScreenLogDefinition).Equals(logType)) {
                return LoggerSettings.ScreenLog;
            } else if (typeof(CyclicJobLogDefinition).Equals(logType)) {
                return LoggerSettings.CyclicJobLog;
            } else if (typeof(ExtensionLogDefinition).Equals(logType)) {
                return LoggerSettings.ExtensionLog;
            } else if (typeof(CustomLogDefinition).Equals(logType)) {
                return LoggerSettings.CustomLog;
            } else if (typeof(IntegrationLogDefinition).Equals(logType)) {
                return LoggerSettings.IntegrationLog;
            } else if (typeof(MobileRequestLogDefinition).Equals(logType)) {
                return LoggerSettings.MobileRequestLog;
            } else if (typeof(ServiceAPILogDefinition).Equals(logType)) {
                return LoggerSettings.ServiceAPIDetailLog;
            } else if (typeof(IntDetailLogDefinition).Equals(logType)) {
                return LoggerSettings.IntDetailLog;
            } else if (typeof(MRDetailLogDefinition).Equals(logType)) {
                return LoggerSettings.MRDetailLog;
            } else if (typeof(ServiceAPIDetailLogDefinition).Equals(logType)) {
                return LoggerSettings.ServiceAPIDetailLog;
            } else if (typeof(RequestEventDefinition).Equals(logType)) {
                return LoggerSettings.RequestEvent;
            }
            return null;
        }

        internal static string TruncateLogMessage(string str, int maxLength) {
            if (str == null || str.Length <= maxLength) {
                return str;
            }

            var builder = new StringBuilder(maxLength + TruncatedLogMessageSuffix.Length + 1);

            builder.Append(str, 0, maxLength - TruncatedLogMessageSuffix.Length);
            builder.Append(TruncatedLogMessageSuffix);

            return builder.ToString();
        }
    }
}
