/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.IO;

namespace OutSystems.Application.Core.Http {
    
    /// <summary>
    /// Represents an HTTP response object.
    /// </summary>
    public interface IHttpResponse {
        /// <summary>
        /// The HTTP context that contains this response object.
        /// </summary>
        IHttpContext HttpContext { get; }

        /// <summary>
        /// Cookie collection of this response object.
        /// </summary>
        IResponseCookies Cookies { get; }

        /// <summary>
        /// HTTP status code of the output returned to the client
        /// </summary>
        int StatusCode { get; set; }

        /// <summary>
        /// HTTP response headers
        /// </summary>
        IHttpHeaderDictionary Headers { get;  }

        /// <summary>
        /// Gets a value indicating whether the client is still connected to the server
        /// </summary>
        bool IsClientConnected { get; }

        /// <summary>
        /// Writes information to an HTTP response output stream
        /// </summary>
        void Write(string s);

        /// <summary>
        /// Sends all currently buffered output to the client
        /// </summary>
        void Flush();

        /// <summary>
        /// Gets or sets the response body Stream
        /// Equivalent to OutputStream from System.Web.Response
        /// </summary>
        Stream Body { get; set; }

        /// <summary>
        /// Clears all content output from the buffer stream
        /// </summary>
        void Clear();

        /// <summary>
        /// Adds a session ID to the virtual path if the session is using Cookieless session state and 
        /// returns the combined path. If Cookieless session state is not used, ApplyAppPathModifier(String) returns the original virtual path.
        /// </summary>
        string ApplyAppPathModifier(string virtualPath);

        /// <summary>
        /// Gets or sets the HTTP status string of the output returned to the client.
        /// </summary>
        string StatusDescription { get; set; }

        /// <summary>
        /// Gets or sets the Cache-Control HTTP header that matches one of the HttpCacheability enumeration values.
        /// </summary>
        string CacheControl { get; set; }
    }
}
