/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Collections.Generic;

namespace OutSystems.Application.Core.Http {
    public interface IHttpCollection<K, V>: IEnumerable<KeyValuePair<K, V>> {
        int Count { get; }

        V this[K key] { get; }

        ICollection<K> Keys { get; }

        bool ContainsKey(K key);

        bool TryGetValue(K key, out V value);
    }
}
