/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Linq;
using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;
using OutSystems.HubEdition.Extensibility.Data.DMLService;
using OutSystems.ObjectKeys;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.Extensibility.Data.Platform.DMLService {
    public static class DMLServiceExtensions {
        /// <summary>
        /// Returns an escaped identifier representing an object (e.g. table or view) that is qualified using 
        /// the information provided by the <see cref="IDatabaseServices.DatabaseConfiguration"/> associated with the <see cref="DMLService"/>.
        /// NOTE: This method uses the <see cref="IDatabaseObjectFactory.CreateLocalDatabaseInfo"/> for qualification.
        /// </summary>
        /// <param name="identifiers">IPlatformDMLIdentifiers to use for qualification</param>
        /// <param name="objectName">Name of the database object (e.g. table, view, stored procedure).</param>
        /// <returns>A string representing the escaped and qualified identifier.</returns>
        public static string EscapeAndQualifyIdentifierForLocalDatabase(this IPlatformDMLIdentifiers identifiers, string objectName) {
            return identifiers.EscapeAndQualifyIdentifier(
                identifiers.DMLService.DatabaseServices.ObjectFactory.CreateLocalDatabaseInfo(), objectName);
        }

        private const int DBSafeListLength = 900;
        /// <summary>
        /// Splits a collection into collections of 900 elements 
        /// </summary>
        /// <typeparam name="T">Type of the collection</typeparam>
        /// <param name="iDMLService"></param>
        /// <param name="coll">Collection to split</param>
        /// <returns></returns>
        public static IEnumerable<IEnumerable<T>> SplitIntoChunks<T>(this IDMLService iDMLService, IEnumerable<T> coll) {
            var arr = coll.ToArray();
            for (var offindex = 0; offindex < arr.Length; offindex += DBSafeListLength) {
                var chunkLength = Math.Min(DBSafeListLength, arr.Length - offindex);
                var chunk = new ArraySegment<T>(arr, offset: offindex, count: chunkLength);

                yield return chunk;
            }
        }

        public static string GenerateInStatement(this IDMLService iDMLService, IEnumerable<Guid> coll, string ColumnName) {
            return iDMLService.GenerateInStatement(coll.Select(c => iDMLService.EscapeTextValue(c.ToString())), ColumnName);
        }

        public static string GenerateInStatement(this IDMLService iDMLService, IEnumerable<ObjectKey> coll, string ColumnName) {
            return iDMLService.GenerateInStatement(coll.Select(c => ObjectKeyUtils.DatabaseValue(c)), ColumnName);
        }

        /// <summary>
        /// This method takes a string collection split is into smaller groups of 900 elements 
        /// and generates a string with multiple IN clauses for the column
        /// </summary>
        /// <param name="iDMLService"></param>
        /// <param name="coll">The collection that will be used to generate the in statements</param>
        /// <param name="ColumnName">the column which will filtered by the collection</param>
        /// <returns></returns>
        public static string GenerateInStatement(this IDMLService iDMLService, IEnumerable<string> coll, string ColumnName) {
            return iDMLService.GenerateInStatement<string>(coll.Select(c => $"'{iDMLService.EscapeTextValue(c)}'"), ColumnName);
        }

        public static string GenerateInStatement(this IDMLService iDMLService, IEnumerable<int> coll, string ColumnName) {
            return iDMLService.GenerateInStatement<int>(coll, ColumnName);
        }

        public static string GenerateInStatement(this IDMLService iDMLService, IEnumerable<long> coll, string ColumnName) {
            return iDMLService.GenerateInStatement<long>(coll, ColumnName);
        }

        private static string GenerateInStatement<T>(this IDMLService iDMLService, IEnumerable<T> coll, string ColumnName) {
            var chunks = iDMLService.SplitIntoChunks(coll);
            var sql = string.Join($" OR ", chunks.Select(c => $"{ColumnName} IN ({string.Join(",", c)})"));

            // If there is more than 1 chunk then an OR is present in the statement
            if (chunks.Count() > 1) {
                sql = $"({sql})"; 
            }

            return sql;
        }
    }
}
