/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Configuration;
using OutSystems.HubEdition.Extensibility.Data;

namespace OutSystems.HubEdition.DatabaseProvider.Oracle {
    internal static class ProviderSettings {
        internal const string EnableKeepAliveProbeSetting = "OutSystems.DatabaseProvider.Oracle.EnableKeepAliveProbe";
        internal const string UseDisabledOOBSetting = "OutSystems.DatabaseProvider.Oracle.UseDisabledOOB";
        internal const string NoValidateFKSetting = "OutSystems.DatabaseProvider.Oracle.NoValidateFK";
        internal const string EnableNlsSortFkIndexCreationSetting = "OutSystems.DatabaseProvider.Oracle.EnableNlsSortFkIndexCreation";
        internal const string DynamicTracingSetting = "OutSystems.DatabaseProvider.Oracle.DynamicTracing";

        private static bool GetAdditionalSetting(IDatabaseServices databaseServices, string setting, bool defaultValue) {
            if (databaseServices is IDatabaseServicesWithAdditionalSettings databaseServicesWithAdditionalSettings
                && databaseServicesWithAdditionalSettings.AdditionalSettings.TryGetValue(setting, out bool additionalSettingValue, defaultValue)) {
                
                return additionalSettingValue;
            }

            if (bool.TryParse(ConfigurationManager.AppSettings[setting], out bool value)) {
                return value;
            }

            return defaultValue;
        }

        internal static bool EnableKeepAliveProbe(IDatabaseServices databaseServices) {
            return GetAdditionalSetting(databaseServices, EnableKeepAliveProbeSetting, defaultValue: true);
        }

        internal static bool UseDisabledOOB(IDatabaseServices databaseServices) {
            return GetAdditionalSetting(databaseServices, UseDisabledOOBSetting, defaultValue: true);
        }

        internal static bool UseNoValidateFK(IDatabaseServices databaseServices) {
            return GetAdditionalSetting(databaseServices, NoValidateFKSetting, defaultValue: false);
        }

        internal static bool EnableNlsSortFkIndexCreation(IDatabaseServices databaseServices) {
            return GetAdditionalSetting(databaseServices, EnableNlsSortFkIndexCreationSetting, defaultValue: false);
        }

        internal static bool DynamicTracing(IDatabaseServices databaseServices) {
            return GetAdditionalSetting(databaseServices, DynamicTracingSetting, defaultValue: true);
        }
    }
}
