/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.Application.Core;
using OutSystems.Application.Core.Http;

namespace OutSystems.HubEdition.RuntimePlatform.Internal {

    /// <summary>
    /// Internal class to allow abstracting interactions to System.Web classes related to Http.
    /// This class is NOT a supported public API.
    /// </summary>
    public static class HttpHelper {

        // Local definition of SameSiteMode to avoid exposing Application.Core in RuntimePlatform
        public enum SameSiteMode {
            Unspecified = -1,
            None = 0,
            Lax = 1,
            Strict = 2
        }

        // Local definition of CookieOptions to avoid exposing Application.Core in RuntimePlatform
        public class CookieOptions {

            public string Domain { get; set; }
            public string Path { get; set; }
            public DateTime? Expires { get; set; }
            public TimeSpan? MaxAge { get; set; }
            public bool? HttpOnly { get; set; }
            public bool? Secure { get; set; }
            public SameSiteMode? SameSite { get; set; }
        }

        private static Application.Core.Http.CookieOptions.SameSiteMode? ConvertSameSiteMode(SameSiteMode? mode) {
            if (mode == null) {
                return null;
            }

            switch (mode.Value) {
                case SameSiteMode.Unspecified:
                    return Application.Core.Http.CookieOptions.SameSiteMode.Unspecified;
                case SameSiteMode.None:
                    return Application.Core.Http.CookieOptions.SameSiteMode.None;
                case SameSiteMode.Lax:
                    return Application.Core.Http.CookieOptions.SameSiteMode.Lax;
                case SameSiteMode.Strict:
                    return Application.Core.Http.CookieOptions.SameSiteMode.Strict;
                default:
                    return null;
            }
        }

        private static SameSiteMode? ConvertSameSiteMode(Application.Core.Http.CookieOptions.SameSiteMode? mode) {
            if (mode == null) {
                return null;
            }

            switch (mode.Value) {
                case Application.Core.Http.CookieOptions.SameSiteMode.Unspecified:
                    return SameSiteMode.Unspecified;
                case Application.Core.Http.CookieOptions.SameSiteMode.None:
                    return SameSiteMode.None;
                case Application.Core.Http.CookieOptions.SameSiteMode.Lax:
                    return SameSiteMode.Lax;
                case Application.Core.Http.CookieOptions.SameSiteMode.Strict:
                    return SameSiteMode.Strict;
                default:
                    return null;
            }
        }

        /// <summary>
        /// Sets a cookie, removing any existing cookie with the same name.
        /// It does not make any distinction about cookies with different Options.
        /// </summary>
        public static void SetCookie(string name, string value, CookieOptions options) {
            if (options == null) {
                throw new ArgumentNullException(nameof(options));
            }

            var context = HttpService.Context;

            if (context != null) {
                context.Response.Cookies.Set(name, value,
                    new Application.Core.Http.CookieOptions() {
                        Domain = options.Domain,
                        Path = options.Path,
                        Expires = options.Expires,
                        MaxAge = options.MaxAge,
                        HttpOnly = options.HttpOnly,
                        Secure = options.Secure,
                        SameSite = ConvertSameSiteMode(options.SameSite)
                    });
            } else {
                throw new Exception("Failed to set cookie. Current request not initialized. Context missing.");
            }
        }

        public static CookieOptions GetDefaultCookieOptions() {

            var context = HttpService.Context;
            var settingsProvider = HttpService.Context.Items[typeof(RuntimeCommon.Settings.ISettingsProvider).FullName] as RuntimeCommon.Settings.ISettingsProvider;

            if (context == null) {
                throw new Exception("Failed to set cookie. Current request not initialized. Context missing.");
            }

            if (settingsProvider == null) {
                throw new Exception("Failed to set cookie. Current request not initialized. Settings missing.");
            }

            var defaultOptions = OutSystems.Application.Core.Http.HttpResponseExtensions.DefaultCookieOptions(context.Response, settingsProvider);

            return new CookieOptions() {
                Domain = defaultOptions.Domain,
                Path = defaultOptions.Path,
                Expires = defaultOptions.Expires,
                MaxAge = defaultOptions.MaxAge,
                HttpOnly = defaultOptions.HttpOnly,
                Secure = defaultOptions.Secure,
                SameSite = ConvertSameSiteMode(defaultOptions.SameSite)
            };
        }
    }
}
