/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Data;
using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.ExecutionService.DatabasePropertiesService;

namespace OutSystems.HubEdition.DatabaseProvider.iDB2.ExecutionService {
    public class iDB2DatabasePropertiesService : BaseDatabasePropertiesService<Version, string> {
        public iDB2DatabasePropertiesService(IDatabaseServices databaseServices) : base(databaseServices) { }

        public override Version GetUnidentifiableVersion() => new Version(0, 0, 0, 0);
        public override string GetUnidentifiableEngine() => "N/A";
        public override Version GetMinimumRequiredVersion() => new Version(7, 1, 0, 0);

        protected override Version InnerGetServerVersion(IDbConnection connection) {
            // returns similar to "DB2 v11.1.4.4"
            // var commandText = $"SELECT SERVICE_LEVEL FROM SYSIBMADM.ENV_INST_INFO";
            // return GetVersionFromDBUsingRegex(connection, commandText);

            // Ignoring above code until we have an actual iDB2 infrastructure to test it against.
            return new Version(999, 999, 999, 999);
        }
    }
}
