/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.Application.Core;
using OutSystems.Application.Core.Http;
using OutSystems.RuntimeCommon;
using OutSystems.RuntimeCommon.Settings;
using OutSystems.Application.Session.Cookies;

namespace OutSystems.HubEdition.RuntimePlatform.Http {
    public static class HttpContextExtensions {
        private static readonly string DefaultLoggingModuleName = nameof(HttpContextExtensions);

        private const string OS_VISIT_COOKIE_NAME = "osVisit";
        private const string OS_VISITOR_COOKIE_NAME = "osVisitor";

        private const int OS_VISIT_COOKIE_VALIDITY_MINUTES = 30;
        private const int OS_VISITOR_COOKIE_VALIDITY_YEARS = 100;

        internal static bool RefreshCookie(
            IHttpContext context,
            string cookieName,
            DateTime cookieExpireDate,
            bool renewExpireDate,
            bool disableMetrics,
            ISettingsProvider settingsProvider,
            ILogService logService = null,
            string overrideCookieGuid = null) {

            var cookieValue = GetCookieValue(context, cookieName);

            if ((string.IsNullOrEmpty(cookieValue) || !GuidUtils.IsGuid(cookieValue))
                && ShouldCreateCookieForRequest(context, disableMetrics)) {

                var cookieGuid = string.IsNullOrEmpty(overrideCookieGuid) ? Guid.NewGuid().ToString() : overrideCookieGuid;
                context.Items[cookieName] = cookieGuid;

                SecureCookieUtils.SetSessionCookie(settingsProvider, context.Response.Cookies,
                           cookieName, cookieGuid,
                           new CookieOptions {
                               Expires = cookieExpireDate
                           });

                logService?.LogTrace($"Created new token '{cookieGuid.FormatSensitiveString()}' for cookie {cookieName}.", DefaultLoggingModuleName);

                return true;

            } else if (renewExpireDate && ShouldCreateCookieForRequest(context, disableMetrics)) {

                SecureCookieUtils.SetSessionCookie(settingsProvider, context.Response.Cookies,
                           cookieName, cookieValue,
                           new CookieOptions {
                               Expires = cookieExpireDate
                           });

                logService?.LogTrace($"Renewed token '{cookieValue.FormatSensitiveString()}' for cookie {cookieName}.", DefaultLoggingModuleName);
            }

            return false;
        }

        internal static bool RefreshVisitsTrackingCookies(IHttpContext context, bool disableMetrics, ISettingsProvider settingsProvider, ILogService logService = null) {
            var visitCookieRefreshed = RefreshCookie(context, OS_VISIT_COOKIE_NAME, DateTime.Now.AddMinutes(OS_VISIT_COOKIE_VALIDITY_MINUTES), true, disableMetrics, settingsProvider, logService);
            var visitorCookieRefreshed = RefreshCookie(context, OS_VISITOR_COOKIE_NAME, DateTime.Now.AddYears(OS_VISITOR_COOKIE_VALIDITY_YEARS), false, disableMetrics, settingsProvider, logService);

            return visitCookieRefreshed || visitorCookieRefreshed;
        }
         
        public static void UpdateVisitsTrackingInfo(this IHttpContext context, bool disableMetrics, SessionInfo sessionInfo, ISettingsProvider settingsProvider, ILogService logService = null) {
            sessionInfo[Visits.NEW_VISIT_KEY] = RefreshVisitsTrackingCookies(context, disableMetrics, settingsProvider, logService);
        }

        internal static string GetCookieValue(IHttpContext context, string cookieName) {
            context.Request.Cookies.TryGetValue(cookieName, out string cookieValue);

            return cookieValue;
        }

        private static bool ShouldCreateCookieForRequest(IHttpContext context, bool disableMetrics) {
            return !context.Request.UserAgent.IsEmpty() &&
                !context.Request.UserAgent.Contains("RichMail") &&
                !context.Request.UserAgent.Contains("Apache-HttpClient") &&
                !disableMetrics;
        }
    }
}
