/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using OutSystems.HubEdition.Extensibility.Data.DMLService;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.Internal.Db;

namespace OutSystems.RuntimePublic.Users {
    /// <summary>Class responsible for manipulating Users and Groups database cache for an OutSystems Application</summary>
    public static class UsersLocalManagement {

        private static bool IsIsolatedModule => RuntimeSettingsProvider.Instance.Get(RuntimePlatformSettings.Application.IsInIsolatedDB);

        private static int BatchSize => RuntimeSettingsProvider.Instance.Get(RuntimePlatformSettings.Misc.DatabaseBatchOperationsSize);

        private static int GetCurrentTenantId() => AppInfo.GetAppInfo().TenantId;

        /// <summary>Gets a representation of the User identified by <paramref name="userId" /> parameter.</summary>
        /// <param name="userId">The User identifier.</param>
        /// <returns>The User representation.</returns>
        /// <exception cref="InvalidOperationException">If <paramref name="userId" /> is equals or bellow 0</exception>
        public static ILocalUser User_Get(int userId) {
            LocalUser localUser = null;

            if (userId <= 0) {
                throw new InvalidOperationException("UserId cannot be less or equal to 0");
            }

            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetReadOnlyTransaction()) {
                var sql = @"SELECT ID, NAME, USERNAME, EMAIL, MOBILEPHONE, CREATION_DATE, LAST_LOGIN, IS_ACTIVE
                        FROM OSSYS_USER
                        WHERE ID = @ID AND TENANT_ID=@TENANT_ID";

                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@ID", DbType.Int32, userId);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, GetCurrentTenantId());

                    using (var reader = cmd.ExecuteReader()) {
                        if (reader.Read()) {
                            localUser = new LocalUser();
                            localUser.Id = reader.SafeGet<int>("ID");
                            localUser.Name = reader.SafeGet<string>("NAME");
                            localUser.Username = reader.SafeGet<string>("USERNAME");
                            localUser.Email = reader.SafeGet<string>("EMAIL");
                            localUser.MobilePhone = reader.SafeGet<string>("MOBILEPHONE");
                            localUser.Creation_Date = reader.SafeGet<DateTime>("CREATION_DATE");
                            localUser.Last_Login = reader.SafeGet<DateTime>("LAST_LOGIN");
                            localUser.Is_Active = reader.SafeGet<bool>("IS_ACTIVE");
                        }
                    }
                }
            }
            return localUser;
        }

        /// <summary>Creates a User based on the <paramref name="user" /> record.</summary>
        /// <param name="user">The User record.</param>
        /// <returns>Created User Identifier.</returns>
        /// <exception cref="InvalidOperationException">In case the caller is an Isolated Application and the <paramref name="user" /> Record doesn't have a valid Id defined.</exception>
        public static int User_Create(ILocalUser user) {
            var useId = IsIsolatedModule;

            if (useId && user.Id <= 0) {
                throw new InvalidOperationException("User Record must have an Id defined");
            }

            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetCommitableTransaction()) {
                var sql = $@"INSERT INTO OSSYS_USER({(useId ? "ID, " : "")}NAME, USERNAME, EMAIL, MOBILEPHONE, CREATION_DATE, LAST_LOGIN, IS_ACTIVE, TENANT_ID)
                        VALUES
                        ({(useId ? "@ID, " : "")}@NAME, @USERNAME, @EMAIL, @MOBILEPHONE, @CREATION_DATE, @LAST_LOGIN, @IS_ACTIVE, @TENANT_ID)";

                int result = 0;
                using (var cmd = trans.CreateCommand(sql)) {
                    if (useId) {
                        cmd.CreateParameter("@ID", DbType.Int32, user.Id);
                    }
                    cmd.CreateParameter("@NAME", DbType.String, user.Name);
                    cmd.CreateParameter("@USERNAME", DbType.String, user.Username);
                    cmd.CreateParameter("@EMAIL", DbType.String, user.Email);
                    cmd.CreateParameter("@MOBILEPHONE", DbType.String, user.MobilePhone);
                    cmd.CreateParameter("@CREATION_DATE", DbType.DateTime, user.Creation_Date);
                    cmd.CreateParameter("@LAST_LOGIN", DbType.DateTime, user.Last_Login);
                    cmd.CreateParameter("@IS_ACTIVE", DbType.Boolean, user.Is_Active);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, GetCurrentTenantId());

                    if (useId) {
                        cmd.ExecuteNonQuery();
                        result = user.Id;
                    } else {
                        result = DBRuntimePlatform.Instance.ExecuteNonQueryGetIdentity(cmd, "ID");
                    }
                }

                trans.Commit();
                return result;
            }
        }

        /// <summary>Creates or Updates a User based on the <paramref name="user" /> record.</summary>
        /// <param name="user">The User record.</param>
        /// <returns>Created User Identifier.</returns>
        /// <remarks>In case the caller is an Isolated Application the User will be created with the provided record identifier, otherwise a new identifier will be generated.</remarks>
        public static int User_CreateOrUpgrade(ILocalUser user) {
            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetCommitableTransaction()) {
                var useId = IsIsolatedModule;
                var tenantId = GetCurrentTenantId();
                var sql = $@"SELECT COUNT(ID)
                        FROM OSSYS_USER
                        WHERE ID=@USER_ID AND TENANT_ID=@TENANT_ID";
                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@USER_ID", DbType.Int32, user.Id);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantId);

                    var update = cmd.ExecuteScalar<int>() > 0;

                    if (update) {
                        useId = true;
                        sql = $@"UPDATE OSSYS_USER
                            SET
                                NAME=@NAME, 
                                USERNAME=@USERNAME, 
                                EMAIL=@EMAIL, 
                                MOBILEPHONE=@MOBILEPHONE, 
                                CREATION_DATE=@CREATION_DATE, 
                                LAST_LOGIN=@LAST_LOGIN, 
                                IS_ACTIVE=@IS_ACTIVE
                            WHERE
                                ID=@ID AND TENANT_ID=@TENANT_ID";
                    } else {
                        sql = $@"INSERT INTO OSSYS_USER({(useId ? "ID, " : "")}NAME, USERNAME, EMAIL, MOBILEPHONE, CREATION_DATE, LAST_LOGIN, IS_ACTIVE, TENANT_ID)
                        VALUES
                        ({(useId ? "@ID, " : "")}@NAME, @USERNAME, @EMAIL, @MOBILEPHONE, @CREATION_DATE, @LAST_LOGIN, @IS_ACTIVE, @TENANT_ID)";
                    }
                }

                int result = 0;
                using (var cmd = trans.CreateCommand(sql)) {
                    if (useId) {
                        cmd.CreateParameter("@ID", DbType.Int32, user.Id);
                    }
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantId);
                    cmd.CreateParameter("@NAME", DbType.String, user.Name);
                    cmd.CreateParameter("@USERNAME", DbType.String, user.Username);
                    cmd.CreateParameter("@EMAIL", DbType.String, user.Email);
                    cmd.CreateParameter("@MOBILEPHONE", DbType.String, user.MobilePhone);
                    cmd.CreateParameter("@CREATION_DATE", DbType.DateTime, user.Creation_Date);
                    cmd.CreateParameter("@LAST_LOGIN", DbType.DateTime, user.Last_Login);
                    cmd.CreateParameter("@IS_ACTIVE", DbType.Boolean, user.Is_Active);

                    if (useId) {
                        cmd.ExecuteNonQuery();
                        result = user.Id;
                    } else {
                        result = DBRuntimePlatform.Instance.ExecuteNonQueryGetIdentity(cmd, "ID");
                    }
                }

                trans.Commit();
                return result;
            }
        }

        /// <summary>Deletes the User identified by the <paramref name="userId" /> paramenter.</summary>
        /// <param name="userId">The User identifier.</param>
        /// <returns>
        ///   <c>true</c> if the User was successfully found and deleted, <c>false</c> otherwise.</returns>
        /// <exception cref="InvalidOperationException">If <paramref name="userId" /> is equals or bellow 0</exception>
        public static bool User_Delete(int userId) {
            if (userId <= 0) {
                throw new InvalidOperationException("User Record must have an Id defined");
            }

            return DeleteById("OSSYS_USER", "ID", userId);
        }

        /// <summary>Updates the User identified by the <paramref name="user" /> record identifier.</summary>
        /// <param name="user">The User record.</param>
        /// <exception cref="InvalidOperationException">If <paramref name="user" /> identifier is equals or bellow 0</exception>
        public static void User_Update(ILocalUser user) {
            if (user.Id <= 0) {
                throw new InvalidOperationException("User Record must have an Id defined");
            }

            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetCommitableTransaction()) {
                var sql = $@"UPDATE OSSYS_USER
                            SET
                                NAME=@NAME, 
                                USERNAME=@USERNAME, 
                                EMAIL=@EMAIL, 
                                MOBILEPHONE=@MOBILEPHONE, 
                                CREATION_DATE=@CREATION_DATE, 
                                LAST_LOGIN=@LAST_LOGIN, 
                                IS_ACTIVE=@IS_ACTIVE
                            WHERE
                                ID=@ID AND TENANT_ID=@TENANT_ID";

                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@ID", DbType.Int32, user.Id);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, GetCurrentTenantId());
                    cmd.CreateParameter("@NAME", DbType.String, user.Name);
                    cmd.CreateParameter("@USERNAME", DbType.String, user.Username);
                    cmd.CreateParameter("@EMAIL", DbType.String, user.Email);
                    cmd.CreateParameter("@MOBILEPHONE", DbType.String, user.MobilePhone);
                    cmd.CreateParameter("@CREATION_DATE", DbType.DateTime, user.Creation_Date);
                    cmd.CreateParameter("@LAST_LOGIN", DbType.DateTime, user.Last_Login);
                    cmd.CreateParameter("@IS_ACTIVE", DbType.Boolean, user.Is_Active);
                    cmd.ExecuteNonQuery();
                }

                trans.Commit();
            }
        }

        /// <summary>Adds the User identified by <paramref name="userId" /> to all Groups identified by <paramref name="groups" /> removing
        /// the User from all remaining Groups.</summary>
        /// <param name="userId">The User identifier.</param>
        /// <param name="groups">The Groups identifiers.</param>
        /// <exception cref="InvalidOperationException">If <paramref name="userId" /> is equals or bellow 0</exception>
        public static void User_SetGroups(int userId, IEnumerable<int> groups) {
            if (userId <= 0) {
                throw new InvalidOperationException("UserId must have be valid Identifier");
            }
            DoBulkAssociation("OSSYS_GROUP_USER", "USER_ID", "GROUP_ID", userId, groups);
        }

        /// <summary>Gets a representation of the Group identified by <paramref name="groupId" /> parameter.</summary>
        /// <param name="groupId">The Group identifier.</param>
        /// <returns>The Group representation.</returns>
        /// <exception cref="InvalidOperationException">If <paramref name="groupId" /> is equals or bellow 0</exception>
        public static ILocalGroup Group_Get(int groupId) {
            LocalGroup localGroup = null;
            if (groupId <= 0) {
                throw new InvalidOperationException("GroupId cannot be less or equal to 0");
            }

            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetReadOnlyTransaction()) {
                var sql = @"SELECT ID, NAME, DESCRIPTION, CREATED_BY, CREATED, HAS_CUSTOM_MANAGEMENT
                        FROM OSSYS_GROUP
                        WHERE ID=@ID AND TENANT_ID=@TENANT_ID";

                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@ID", DbType.Int32, groupId);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, GetCurrentTenantId());

                    using (var reader = cmd.ExecuteReader()) {
                        if (reader.Read()) {
                            localGroup = new LocalGroup();
                            localGroup.Id = reader.SafeGet<int>("ID");
                            localGroup.Name = reader.SafeGet<string>("NAME");
                            localGroup.Description = reader.SafeGet<string>("DESCRIPTION");
                            localGroup.Created_By = reader.SafeGet<int>("CREATED_BY");
                            localGroup.Creation_Date = reader.SafeGet<DateTime>("CREATED");
                            localGroup.Has_Custom_Management = reader.SafeGet<bool>("HAS_CUSTOM_MANAGEMENT");
                        }
                    }
                }
            }
            return localGroup;
        }

        /// <summary>Creates a Group based on the <paramref name="group" /> record.</summary>
        /// <param name="group">The Group record.</param>
        /// <returns>Created Group Identifier.</returns>
        /// <exception cref="InvalidOperationException">In case the caller is an Isolated Application and the <paramref name="group" /> Record doesn't have a valid Id defined.</exception>
        public static int Group_Create(ILocalGroup group) {
            var useId = IsIsolatedModule;

            if (useId && group.Id <= 0) {
                throw new InvalidOperationException("Group Record must have an Id defined");
            }

            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetCommitableTransaction()) {
                var sql = $@"INSERT INTO OSSYS_GROUP({(useId ? "ID, " : "")}NAME, DESCRIPTION, CREATED_BY, CREATED, HAS_CUSTOM_MANAGEMENT, TENANT_ID)
                        VALUES
                        ({(useId ? "@ID, " : "")}@NAME, @DESCRIPTION, @CREATED_BY, @CREATED, @HAS_CUSTOM_MANAGEMENT, @TENANT_ID)";

                int result = 0;
                using (var cmd = trans.CreateCommand(sql)) {
                    if (useId) {
                        cmd.CreateParameter("@ID", DbType.Int32, group.Id);
                    }
                    cmd.CreateParameter("@NAME", DbType.String, group.Name);
                    cmd.CreateParameter("@DESCRIPTION", DbType.String, group.Description);
                    cmd.CreateParameter("@CREATED_BY", DbType.Int32, group.Created_By);
                    cmd.CreateParameter("@CREATED", DbType.DateTime, group.Creation_Date);
                    cmd.CreateParameter("@HAS_CUSTOM_MANAGEMENT", DbType.Boolean, group.Has_Custom_Management);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, GetCurrentTenantId());

                    if (useId) {
                        cmd.ExecuteNonQuery();
                        result = group.Id;
                    } else {
                        result = DBRuntimePlatform.Instance.ExecuteNonQueryGetIdentity(cmd, "ID");
                    }
                }

                trans.Commit();
                return result;
            }
        }

        /// <summary>Creates or Updates a Group based on the <paramref name="group" /> record.</summary>
        /// <param name="group">The Group record.</param>
        /// <returns>Created Group Identifier.</returns>
        /// <remarks>In case the caller is an Isolated Application the Group will be created with the provided record identifier, otherwise a new identifier will be generated.</remarks>
        public static int Group_CreateOrUpdate(ILocalGroup group) {
            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetCommitableTransaction()) {
                var useId = IsIsolatedModule;
                var tenantId = GetCurrentTenantId();
                var sql = $@"SELECT COUNT(ID)
                        FROM OSSYS_GROUP
                        WHERE ID=@GROUP_ID AND TENANT_ID=@TENANT_ID";
                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@GROUP_ID", DbType.Int32, group.Id);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantId);

                    var update = cmd.ExecuteScalar<int>() > 0;

                    if (update) {
                        useId = true;
                        sql = $@"UPDATE OSSYS_GROUP
                            SET
                                NAME=@NAME, 
                                DESCRIPTION=@DESCRIPTION, 
                                CREATED_BY=@CREATED_BY, 
                                CREATED=@CREATED, 
                                HAS_CUSTOM_MANAGEMENT=@HAS_CUSTOM_MANAGEMENT
                            WHERE
                                ID=@ID AND TENANT_ID=@TENANT_ID";
                    } else {
                        sql = $@"INSERT INTO OSSYS_GROUP({(useId ? "ID, " : "")}NAME, DESCRIPTION, CREATED_BY, CREATED, HAS_CUSTOM_MANAGEMENT, TENANT_ID)
                        VALUES
                        ({(useId ? "@ID, " : "")}@NAME, @DESCRIPTION, @CREATED_BY, @CREATED, @HAS_CUSTOM_MANAGEMENT, @TENANT_ID)";
                    }
                }
                int result = 0;
                using (var cmd = trans.CreateCommand(sql)) {
                    if (useId) {
                        cmd.CreateParameter("@ID", DbType.Int32, group.Id);
                    }
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantId);
                    cmd.CreateParameter("@NAME", DbType.String, group.Name);
                    cmd.CreateParameter("@DESCRIPTION", DbType.String, group.Description);
                    cmd.CreateParameter("@CREATED_BY", DbType.Int32, group.Created_By);
                    cmd.CreateParameter("@CREATED", DbType.DateTime, group.Creation_Date);
                    cmd.CreateParameter("@HAS_CUSTOM_MANAGEMENT", DbType.Boolean, group.Has_Custom_Management);

                    if (useId) {
                        cmd.ExecuteNonQuery();
                        result = group.Id;
                    } else {
                        result = DBRuntimePlatform.Instance.ExecuteNonQueryGetIdentity(cmd, "ID");
                    }
                }

                trans.Commit();
                return result;
            }
        }

        /// <summary>Creates or Updates all Groups based on the <paramref name="groups" /> records enumerable with the option to delete existing Groups.</summary>
        /// <param name="groups">The Group records enumerable.</param>
        /// <param name="deleteExisting">Controls whenever the existing Groups should be cleaned up.</param>
        /// <remarks>In case the caller is an Isolated Application the Groups will be created with the provided record identifier, otherwise a new identifier will be generated.
        /// In case the caller is not an Isolated Application existing Groups won't be deleted even if <paramref name="deleteExisting"/> is <c>true</c></remarks>
        public static void Group_CreateOrUpdateMultiple(IEnumerable<ILocalGroup> groups, bool deleteExisting = true) {
            string genericErrorMessage = "Error while trying perform a BulkOperation to update Groups database cache, {0}. This will require a manual operation on Application's Database.";
            var tenantId = GetCurrentTenantId();
            var useId = IsIsolatedModule;
            // If Ids for INSERT statements are db generated (aka !IsIsolatedModule, aka System) there is no way of knowing all of them,
            // so we skip the deletion of remaining Groups
            var skipDelete = !useId || !deleteExisting;
            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetCommitableTransaction()) {
                var dmlFunctions = trans.DatabaseServices.DMLService.Functions;
                var dmlService = trans.DatabaseServices.DMLService;
                var programmaticSQL = DatabaseAccess.ForRuntimeDatabase.DatabaseServices.DMLService.ProgrammaticSql;
                Command cmd = null;
                var existingIds = GetExistingIds(trans, tenantId, "OSSYS_GROUP", "ID");
                var deleteSQL = new StringBuilder($"DELETE FROM OSSYS_GROUP WHERE TENANT_ID = @TENANT_ID");
                var data = groups;
                foreach (var batchLazy in data.Batch(BatchSize)) {

                    var sql = new StringBuilder();
                    sql.AppendLine(programmaticSQL.BeginProgrammaticSQLBlock());
                    var recIds = new List<int>();

                    while (batchLazy.MoveNext()) {
                        var group = batchLazy.Current;

                        if (existingIds.Contains(group.Id)) {
                            var update = $@"UPDATE OSSYS_GROUP 
                                SET 
                                    NAME='{dmlService.EscapeTextValue(group.Name)}',
                                    DESCRIPTION='{dmlService.EscapeTextValue(group.Description)}',
                                    CREATED_BY={group.Created_By},
                                    CREATED={group.Creation_Date.ToDatabaseValue(dmlFunctions)},
                                    HAS_CUSTOM_MANAGEMENT={(group.Has_Custom_Management ? '1' : '0')}
                                WHERE
                                    ID={group.Id} AND TENANT_ID=@TENANT_ID;";
                            sql.AppendLine(update);
                        } else {
                            var insert = $@"INSERT INTO OSSYS_GROUP ({(useId ? "ID, " : "")}NAME, DESCRIPTION, CREATED_BY, CREATED, HAS_CUSTOM_MANAGEMENT, TENANT_ID)
                                VALUES (
                                        {(useId ? group.Id + "," : "")}
                                        '{dmlService.EscapeTextValue(group.Name)}',
                                        '{dmlService.EscapeTextValue(group.Description)}',
                                        {group.Created_By},
                                        {group.Creation_Date.ToDatabaseValue(dmlFunctions)},
                                        {(group.Has_Custom_Management ? '1' : '0')},
                                         @TENANT_ID
                                        );";
                            sql.AppendLine(insert);
                        }

                        sql.AppendLine();
                        recIds.Add(group.Id);
                    }

                    deleteSQL.Append($" AND ID NOT IN ({string.Join(",", recIds)})");

                    try {
                        sql.AppendLine(programmaticSQL.EndProgrammaticSQLBlock());
                        using (cmd = trans.CreateCommand(sql.ToString())) {
                            cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantId);
                            cmd.ExecuteNonQuery();
                        }
                    } catch (Exception e) {
                        throw new DataBaseException(
                            string.Format(genericErrorMessage, $"cannot insert or update some Groups"),
                            e);
                    }
                }

                if (!skipDelete) {
                    try {
                        using (cmd = trans.CreateCommand(deleteSQL.ToString())) {
                            cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantId);
                            cmd.ExecuteNonQuery();
                        }
                    } catch (Exception e) {
                        throw new DataBaseException(
                            string.Format(genericErrorMessage, $"cannot cleanup existing Groups"),
                            e);
                    }
                }

                trans.Commit();
            }
        }

        /// <summary>Deletes the Group identified by the <paramref name="groupId" /> paramenter.</summary>
        /// <param name="groupId">The Group identifier.</param>
        /// <returns>
        ///   <c>true</c> if the Group was successfully found and deleted, <c>false</c> otherwise.</returns>
        /// <exception cref="InvalidOperationException">If <paramref name="groupId" /> is equals or bellow 0</exception>
        public static bool Group_Delete(int groupId) {
            if (groupId <= 0) {
                throw new InvalidOperationException("Group Record must have an Id defined");
            }

            return DeleteById("OSSYS_GROUP", "ID", groupId);
        }

        /// <summary>Updates the Group identified by the <paramref name="group" /> record identifier.</summary>
        /// <param name="group">The Group record.</param>
        /// <exception cref="InvalidOperationException">If <paramref name="group" /> identifier is equals or bellow 0</exception>
        public static void Group_Update(ILocalGroup group) {
            if (group.Id <= 0) {
                throw new InvalidOperationException("User Record must have an Id defined");
            }

            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetCommitableTransaction()) {
                var sql = $@"UPDATE OSSYS_GROUP
                            SET 
                                NAME=@NAME, 
                                DESCRIPTION=@DESCRIPTION, 
                                CREATED_BY=@CREATED_BY, 
                                CREATED=@CREATED, 
                                HAS_CUSTOM_MANAGEMENT=@HAS_CUSTOM_MANAGEMENT
                            WHERE
                                ID=@ID AND TENANT_ID=@TENANT_ID";

                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@ID", DbType.Int32, group.Id);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, GetCurrentTenantId());
                    cmd.CreateParameter("@NAME", DbType.String, group.Name);
                    cmd.CreateParameter("@DESCRIPTION", DbType.String, group.Description);
                    cmd.CreateParameter("@CREATED_BY", DbType.Int32, group.Created_By);
                    cmd.CreateParameter("@CREATED", DbType.DateTime, group.Creation_Date);
                    cmd.CreateParameter("@HAS_CUSTOM_MANAGEMENT", DbType.Boolean, group.Has_Custom_Management);
                    cmd.ExecuteNonQuery();
                }

                trans.Commit();
            }
        }

        /// <summary>Adds the User identified by <paramref name="userId" /> to the Group identified by <paramref name="groupId" />.</summary>
        /// <param name="groupId">The Group identifier.</param>
        /// <param name="userId">The User identifier.</param>
        public static void Group_AddUser(int groupId, int userId) {
            SetAssociation("OSSYS_GROUP_USER", "GROUP_ID", "USER_ID", groupId, userId);
        }

        /// <summary>Removes the User identified by <paramref name="userId" /> from the Group identified by <paramref name="groupId" />.</summary>
        /// <param name="groupId">The Group identifier.</param>
        /// <param name="userId">The User identifier.</param>
        public static void Group_RemoveUser(int groupId, int userId) {
            RemoveAssociation("OSSYS_GROUP_USER", "GROUP_ID", "USER_ID", groupId, userId);
        }

        /// <summary>Checks if the Group identified by <paramref name="groupId" /> has the User identified by <paramref name="userId" /> associated.</summary>
        /// <param name="groupId">The Group identifier.</param>
        /// <param name="userId">The User identifier.</param>
        /// <returns>
        ///   <c>true</c> if the Group has the User, <c>false</c> otherwise</returns>
        public static bool Group_HasUser(int groupId, int userId) {
            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetReadOnlyTransaction()) {
                var sql = $@"SELECT COUNT(ID)
                        FROM OSSYS_GROUP_USER
                        WHERE GROUP_ID=@GROUP_ID AND USER_ID=@USER_ID AND TENANT_ID=@TENANT_ID";
                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@GROUP_ID", DbType.Int32, groupId);
                    cmd.CreateParameter("@USER_ID", DbType.Int32, userId);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, GetCurrentTenantId());

                    return cmd.ExecuteScalar<int>() > 0;
                }
            }
        }

        /// <summary>Adds all Users identified by <paramref name="users" /> to the Group identified by <paramref name="groupId" /> removing
        /// all remaining Users from the Group.</summary>
        /// <param name="groupId">The Group identifier.</param>
        /// <param name="users">The Users identifiers.</param>
        /// <exception cref="InvalidOperationException">If <paramref name="groupId" /> is equals or bellow 0</exception>
        public static void Group_SetUsers(int groupId, IEnumerable<int> users) {
            if (groupId <= 0) {
                throw new InvalidOperationException("GroupId must have be valid Identifier");
            }
            DoBulkAssociation("OSSYS_GROUP_USER", "GROUP_ID", "USER_ID", groupId, users);
        }

        private static IEnumerable<int> GetExistingIds(Transaction trans, int tenantId, string tableName, string idColumnName) {
            var sql = $@"SELECT DISTINCT({idColumnName})
                                    FROM {tableName}
                                    WHERE
                                        TENANT_ID = @TENANT_ID";
            var result = new List<int>();
            using (var cmd = trans.CreateCommand(sql)) {
                cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantId);
                using (var reader = cmd.ExecuteReader()) {
                    while (reader.Read()) {
                        result.Add(reader.SafeGet<int>(idColumnName));
                    }
                }
            }
            return result;
        }

        private static string BuildRecordsWithIdSelect(string idColumnName, string recordColumntring, List<int> recordsIds, List<string> recordsValues) {
            return $@"SELECT {idColumnName}, {recordColumntring}
                                        FROM 
                                        (
                                            VALUES
                                                {string.Join(
                                                    ",",
                                                    recordsValues
                                                    .Select(
                                                        (str, idx) =>
                                                            $"({recordsIds[idx]}, {str})"))}
                                        ) SOME_NAME ({idColumnName}, {recordColumntring})";
        }

        private static void DoBulkAssociation(string tableName, string mainIdColumnName, string associationIdColumnName, int mainId, IEnumerable<int> associationIds, bool ignoreNonExistingForeignKeys = false, string associationTableName = "", string associationTableIdColumnName = "") {
            var tenantId = GetCurrentTenantId();
            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetCommitableTransaction()) {
                Command cmd = null;

                if (!associationIds.Any()) {
                    var sql = $@"DELETE FROM {tableName}
                            WHERE 
                                {mainIdColumnName} = @MAIN_ID AND TENANT_ID = @TENANT_ID";

                    using (cmd = trans.CreateCommand(sql)) {
                        cmd.CreateParameter("@MAIN_ID", DbType.Int32, mainId);
                        cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantId);
                        cmd.ExecuteNonQuery();
                    }

                    trans.Commit();
                    return;
                }

                var recordsSelects = new StringBuilder();
                var idsSelects = new StringBuilder();
                var deleteValues = new StringBuilder();
                bool isFirst = true;
                var batches = associationIds.Batch(BatchSize);

                foreach (var batchLazy in batches) {
                    var batchData = batchLazy.ToIEnumerable().ToArray();
                    var AssociationIdValues = "(" + string.Join(",", batchData) + ")";

                    var recordIdValues = DBRuntimePlatform.Instance.GetSelectForValues(batchData, associationIdColumnName);

                    if (isFirst) {


                        recordsSelects.Append(recordIdValues);

                        idsSelects.Append($@"SELECT DISTINCT({associationIdColumnName})
                                        FROM {tableName}
                                        WHERE
                                            {mainIdColumnName} = @MAIN_ID AND TENANT_ID = @TENANT_ID AND
                                            ({associationIdColumnName} IN {AssociationIdValues}");

                        isFirst = false;
                    } else {

                        recordsSelects.Append($@" UNION(
                                                {recordIdValues}
                                            )");

                        idsSelects.Append($@" OR {associationIdColumnName} IN {AssociationIdValues}");
                    }
                    deleteValues.Append($@" AND {associationIdColumnName} NOT IN {AssociationIdValues}");
                }

                idsSelects.Append(")");
                var deleteSql = $@"DELETE FROM {tableName}
                                WHERE 
                                    {mainIdColumnName} = @MAIN_ID AND TENANT_ID = @TENANT_ID {deleteValues}";

                var insertSql = $@"INSERT INTO {tableName} ({mainIdColumnName}, {associationIdColumnName}, TENANT_ID)
                                SELECT @MAIN_ID {mainIdColumnName}, {associationIdColumnName}, @TENANT_ID TENANT_ID
                                FROM 
                                (
                                    {recordsSelects}
                                ) SOME_NAME
                                WHERE 
                                    SOME_NAME.{associationIdColumnName} NOT IN 
                                    (
                                        {idsSelects}
                                    )";

                if (ignoreNonExistingForeignKeys) {
                    insertSql += $@" AND 
                                    SOME_NAME.{associationIdColumnName} IN 
                                    (
                                        SELECT {associationTableIdColumnName} from {associationTableName}
                                    )";
                }

                using (cmd = trans.CreateCommand(deleteSql)) {
                    cmd.CreateParameter("@MAIN_ID", DbType.Int32, mainId);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantId);
                    cmd.ExecuteNonQuery();
                }

                using (cmd = trans.CreateCommand(insertSql)) {
                    cmd.CreateParameter("@MAIN_ID", DbType.Int32, mainId);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantId);
                    cmd.ExecuteNonQuery();
                }

                trans.Commit();
            }
        }

        private static bool DeleteById(string tableName, string idColumnName, int id) {
            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetCommitableTransaction()) {
                var sql = $@"DELETE FROM {tableName}
                             WHERE
                             {idColumnName}= @ID AND TENANT_ID=@TENANT_ID";
                bool result = false;
                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@ID", DbType.Int32, id);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, GetCurrentTenantId());
                    result = cmd.ExecuteNonQuery() > 0;
                }

                trans.Commit();
                return result;
            }
        }

        private static void SetAssociation(string tableName, string mainIdColumnName, string AssociationIdColumnName, int mainId, int AssociationId) {
            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetCommitableTransaction()) {
                var tenantId = GetCurrentTenantId();
                var sql = $@"SELECT COUNT({mainIdColumnName})
                        FROM {tableName}
                        WHERE {mainIdColumnName}=@MAIN_ID AND {AssociationIdColumnName}=@ASSOCIATION_ID AND TENANT_ID=@TENANT_ID";
                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@MAIN_ID", DbType.Int32, mainId);
                    cmd.CreateParameter("@ASSOCIATION_ID", DbType.Int32, AssociationId);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantId);

                    if (cmd.ExecuteScalar<int>() > 0) {
                        return;
                    }
                }
                sql = $@"INSERT INTO {tableName}({mainIdColumnName}, {AssociationIdColumnName}, TENANT_ID)
                        VALUES
                        (@MAIN_ID, @ASSOCIATION_ID, @TENANT_ID)";

                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@MAIN_ID", DbType.Int32, mainId);
                    cmd.CreateParameter("@ASSOCIATION_ID", DbType.Int32, AssociationId);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, tenantId);

                    cmd.ExecuteNonQuery();
                }

                trans.Commit();
            }
        }

        private static bool RemoveAssociation(string tableName, string mainIdColumnName, string AssociationIdColumnName, int mainId, int AssociationId) {
            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetCommitableTransaction()) {
                var sql = $@"DELETE FROM {tableName}
                        WHERE
                        {mainIdColumnName}= @MAIN_ID AND {AssociationIdColumnName}=@ASSOCIATION_ID AND TENANT_ID=@TENANT_ID";
                bool result = false;
                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@MAIN_ID", DbType.Int32, mainId);
                    cmd.CreateParameter("@ASSOCIATION_ID", DbType.Int32, AssociationId);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, GetCurrentTenantId());

                    result = cmd.ExecuteNonQuery() > 0;
                }

                trans.Commit();
                return result;
            }
        }

        private static bool HasAssociation(string tableName, string mainIdColumnName, string AssociationIdColumnName, int mainId, int AssociationId) {
            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetReadOnlyTransaction()) {
                var sql = $@"SELECT COUNT(ID)
                        FROM {tableName}
                        WHERE {mainIdColumnName}=@MAIN_ID AND {AssociationIdColumnName}=@ASSOCIATION_ID AND TENANT_ID=@TENANT_ID";
                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@MAIN_ID", DbType.Int32, mainId);
                    cmd.CreateParameter("@ASSOCIATION_ID", DbType.Int32, AssociationId);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, GetCurrentTenantId());

                    return cmd.ExecuteScalar<int>() > 0;
                }
            }
        }

        private static IEnumerable<IEnumerator<T>> Batch<T>(this IEnumerable<T> source, int batchSize) {
            using (var enumerator = source.GetEnumerator()) {
                while (enumerator.MoveNext()) {
                    yield return YieldBatchElements(enumerator, batchSize - 1);
                }
            }
        }

        private static IEnumerator<T> YieldBatchElements<T>(IEnumerator<T> source, int batchSize) {
            yield return source.Current;
            for (int i = 0; i < batchSize && source.MoveNext(); i++) {
                yield return source.Current;
            }
        }

        private static IEnumerable<T> ToIEnumerable<T>(this IEnumerator<T> enumerator) {
            while (enumerator.MoveNext()) {
                yield return enumerator.Current;
            }
        }

        private static string ToDatabaseValue(this DateTime dateTime, IDMLFunctions funcs) {
            return funcs.NewDateTime(
                                    dateTime.Year.ToString("D"),
                                    dateTime.Month.ToString("D"),
                                    dateTime.Day.ToString("D"),
                                    dateTime.Hour.ToString("D"),
                                    dateTime.Minute.ToString("D"),
                                    dateTime.Second.ToString("D"));
        }

        #region Old Authorization endpoints
        //(this data is now stored in System Database)
        /*
        /// <summary>Grants the Role identified by <paramref name="roleId" /> to the User identified by <paramref name="userId" />.</summary>
        /// <param name="userId">The User identifier.</param>
        /// <param name="roleId">The Role identifier.</param>
        public static void User_GrantRole(int userId, int roleId) {
            SetAssociation("OSSYS_USER_ROLE", "USER_ID", "ROLE_ID", userId, roleId);
        }

        /// <summary>Revokes the Role identified by <paramref name="roleId" /> from the User identified by <paramref name="userId" />.</summary>
        /// <param name="userId">The User identifier.</param>
        /// <param name="roleId">The Role identifier.</param>
        public static void User_RevokeRole(int userId, int roleId) {
            RemoveAssociation("OSSYS_USER_ROLE", "USER_ID", "ROLE_ID", userId, roleId);
        }

        /// <summary>Checks if the User identified by <paramref name="userId" /> has the Role identified by <paramref name="roleId" /> associated.</summary>
        /// <param name="userId">The User identifier.</param>
        /// <param name="roleId">The Role identifier.</param>
        /// <returns>
        ///   <c>true</c> if the User has the Role, <c>false</c> otherwise</returns>
        public static bool User_CheckRole(int userId, int roleId) {
            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetReadOnlyTransaction()) {
                var sql = $@"SELECT COUNT(ID)
                        FROM OSSYS_USER_ROLE
                        WHERE USER_ID=@USER_ID AND ROLE_ID=@ROLE_ID AND TENANT_ID=@TENANT_ID";
                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@USER_ID", DbType.Int32, userId);
                    cmd.CreateParameter("@ROLE_ID", DbType.Int32, roleId);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, GetCurrentTenantId());

                    return cmd.ExecuteScalar<int>() > 0;
                }
            }
        }

        /// <summary>Grants all Roles identified by <paramref name="roles" /> to the User identified by <paramref name="userId" /> revoking all
        /// remaining Roles from the User.</summary>
        /// <param name="userId">The User identifier.</param>
        /// <param name="roles">The Roles identifiers.</param>
        /// <exception cref="InvalidOperationException">If <paramref name="userId" /> is equals or bellow 0</exception>
        public static void User_SetRoles(int userId, IEnumerable<int> roles) {
            if (userId <= 0) {
                throw new InvalidOperationException("UserId must have be valid Identifier");
            }
            DoBulkAssociation("OSSYS_USER_ROLE", "USER_ID", "ROLE_ID", userId, roles, true, "OSSYS_ROLE", "ID");
        }

        /// <summary>Grants all Roles identified by <paramref name="roles" /> to the User identified by <paramref name="userId" /> revoking all
        /// remaining Roles from the User.</summary>
        /// <param name="trans">The</param>
        /// <param name="tenantId">The Tenant.</param>
        /// <param name="userId">The User identifier.</param>
        /// <param name="roles">The Roles identifiers.</param>
        /// <exception cref="InvalidOperationException">If <paramref name="userId" /> is equals or bellow 0</exception>
        public static void User_SetRoles(Transaction trans, int tenantId, int userId, IEnumerable<int> roles) {
            if (userId <= 0) {
                throw new InvalidOperationException("UserId must have be valid Identifier");
            }
            DoBulkAssociation(trans, tenantId, "OSSYS_USER_ROLE", "USER_ID", "ROLE_ID", userId, roles, true, "OSSYS_ROLE", "ID");
        }

        /// <summary>Adds the Role identified by <paramref name="roleId" /> to the Group identified by <paramref name="groupId" />.</summary>
        /// <param name="groupId">The Group identifier.</param>
        /// <param name="roleId">The Role identifier.</param>
        public static void Group_AddRole(int groupId, int roleId) {
            SetAssociation("OSSYS_GROUP_ROLE", "GROUP_ID", "ROLE_ID", groupId, roleId);
        }

        /// <summary>Removes the Role identified by <paramref name="roleId" /> from the Group identified by <paramref name="groupId" />.</summary>
        /// <param name="groupId">The Group identifier.</param>
        /// <param name="roleId">The Role identifier.</param>
        public static void Group_RemoveRole(int groupId, int roleId) {
            RemoveAssociation("OSSYS_GROUP_ROLE", "GROUP_ID", "ROLE_ID", groupId, roleId);
        }

        /// <summary>Checks if the Group identified by <paramref name="groupId" /> has the Role identified by <paramref name="roleId" /> associated.</summary>
        /// <param name="groupId">The Group identifier.</param>
        /// <param name="roleId">The Role identifier.</param>
        /// <returns>
        ///   <c>true</c> if the Group has the Role, <c>false</c> otherwise</returns>
        public static bool Group_HasRole(int groupId, int roleId) {
            using (var trans = DatabaseAccess.ForRuntimeDatabase.GetReadOnlyTransaction()) {
                var sql = $@"SELECT COUNT(ID)
                        FROM OSSYS_GROUP_ROLE
                        WHERE GROUP_ID=@GROUP_ID AND ROLE_ID=@ROLE_ID AND TENANT_ID=@TENANT_ID";
                using (var cmd = trans.CreateCommand(sql)) {
                    cmd.CreateParameter("@GROUP_ID", DbType.Int32, groupId);
                    cmd.CreateParameter("@ROLE_ID", DbType.Int32, roleId);
                    cmd.CreateParameter("@TENANT_ID", DbType.Int32, GetCurrentTenantId());

                    return cmd.ExecuteScalar<int>() > 0;
                }
            }
        }

        /// <summary>Adds all Roles identified by <paramref name="roles" /> to the Group identified by <paramref name="groupId" /> removing
        /// all remaining Roles from the Group.</summary>
        /// <param name="groupId">The Group identifier.</param>
        /// <param name="roles">The Roles identifiers.</param>
        /// <exception cref="InvalidOperationException">If <paramref name="groupId" /> is equals or bellow 0</exception>
        public static void Group_SetRoles(int groupId, IEnumerable<int> roles) {
            if (groupId <= 0) {
                throw new InvalidOperationException("GroupId must have be valid Identifier");
            }
            DoBulkAssociation("OSSYS_GROUP_ROLE", "GROUP_ID", "ROLE_ID", groupId, roles, true, "OSSYS_ROLE", "ID");
        }
        */
        #endregion
    }
}
