/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.DatabaseProvider.PostgreSQL.DatabaseObjects;
using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;
using OutSystems.HubEdition.Extensibility.Data.DMLService;
using OutSystems.HubEdition.Extensibility.Data.DMLService.DMLPlaceholders;
using System.Collections.Generic;

namespace OutSystems.HubEdition.DatabaseProvider.PostgreSQL.DMLService {
    public class DMLEntityActions : BaseDMLEntityActions {

        internal DMLEntityActions(IDMLService dmlService, ITableSourceInfo tableSourceInfo) : base(dmlService, tableSourceInfo) { }

        public TableSourceInfo EntityInfo {
            get {
                return base.TableSourceInfo as TableSourceInfo;
            }
        }

        private volatile IDictionary<SelectPlaceholder, string> getForUpdatePlaceholderValues;
        private volatile IDictionary<InsertPlaceholder, string> createAndRetrieveIdPlaceholderValues;  

        public override IDictionary<SelectPlaceholder, string> SQLPlaceholderValuesForGetForUpdate() {
            if (getForUpdatePlaceholderValues == null) {
                lock (this) {
                    if (getForUpdatePlaceholderValues == null) {
                        getForUpdatePlaceholderValues = new Dictionary<SelectPlaceholder, string>();
                        getForUpdatePlaceholderValues.Add(SelectPlaceholder.AfterStatement, " FOR UPDATE");
                    }
                }
            }
            return getForUpdatePlaceholderValues;
        }

        public override IDictionary<InsertPlaceholder, string> SQLPlaceholderValuesForCreateAndRetrieveId(string idColumnName, string outputParameterName, out RetrieveIdMethod retrieveIdMethod) {
            retrieveIdMethod = RetrieveIdMethod.OutputParameter;
            if (createAndRetrieveIdPlaceholderValues == null) {
                lock (this) {
                    if (createAndRetrieveIdPlaceholderValues == null) {
                        createAndRetrieveIdPlaceholderValues = new Dictionary<InsertPlaceholder, string>();
                        string afterStatement = " RETURNING " + idColumnName;

                        createAndRetrieveIdPlaceholderValues.Add(InsertPlaceholder.AfterStatement, afterStatement);
                    }
                }
            }
            return createAndRetrieveIdPlaceholderValues;
        }
    }
}
