/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OutSystems.HubEdition.Extensibility.Data.DMLService;
using OutSystems.HubEdition.Extensibility.Data.DMLService.DMLPlaceholders;

namespace OutSystems.HubEdition.DatabaseProvider.PostgreSQL.DMLService {
    class DMLQueries : BaseDMLQueries {
        public DMLQueries(IDMLService dmlService) : base(dmlService) { }

        // Anedoctical reports on the interwebs seem to show that count(*) is faster than count(col)/count(1) on PostgreSQL.
        public override IDictionary<StatementPlaceholder, string> SQLPlaceholderValuesForCountQuery() {
            Dictionary<StatementPlaceholder, string> count = new Dictionary<StatementPlaceholder, string> {
                { StatementPlaceholder.BeforeStatement, "SELECT COUNT(*) FROM (" }, 
                { StatementPlaceholder.AfterStatement, ") as result" }
            };
            return count;
        }

        public override IDictionary<SelectPlaceholder, string> SQLPlaceholderValuesForMaxRecords(string maxRecordsParam) {
            Dictionary<SelectPlaceholder, string> res = new Dictionary<SelectPlaceholder, string> {
                { SelectPlaceholder.BeforeStatement, "SELECT * FROM (" },
                { SelectPlaceholder.AfterStatement, ") as result LIMIT " + maxRecordsParam }
            };
            return res;
        }
    }
}
