/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Text;
using OutSystems.RuntimeCommon;
using OutSystems.RuntimeCommon.Settings;

namespace OutSystems.RuntimeSettingsConfiguration {
    public static partial class RuntimeSettingsDefinition {

        public static class Catalog {
            public static class ModuleCatalogSetting {
                private static string GetSettingKey(string moduleKey) => $"OutSystems.Module.{moduleKey}.Catalog";
                public static ISetting<string> Catalog(string moduleKey) => BuildSetting(GetSettingKey(moduleKey), Constants.MainDatabaseLogicalName);
            }
            public static class CatalogConfigurationSetting {
                private static string GetSettingKey(string catalogName, string configName) => $"OutSystems.Catalog.{catalogName}.{configName}";
                public static ISetting<string> Name(string catalogName) => BuildSetting(GetSettingKey(catalogName, "Name"), Constants.MainDatabaseLogicalName);
                public static ISetting<string> Catalog(string catalogName) => BuildSetting(GetSettingKey(catalogName, "Catalog"), Constants.MainDatabaseLogicalName);
                public static ISetting<string> Schema(string catalogName) => BuildSetting(GetSettingKey(catalogName, "Schema"), string.Empty);
                public static ISetting<string> Tablespace(string catalogName) => BuildSetting(GetSettingKey(catalogName, "Tablespace"), string.Empty);
                public static ISetting<string> TablespaceIndex(string catalogName) => BuildSetting(GetSettingKey(catalogName, "TablespaceIndex"), string.Empty);
                public static ISetting<string> Username(string catalogName) => BuildSetting(GetSettingKey(catalogName, "Username"), string.Empty);
                public static ISetting<string> Password(string catalogName) => BuildSetting(GetSettingKey(catalogName, "Password"), string.Empty, isEncrypted: true);
            }
        }
    }
}
