/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.RuntimeCommon.Settings;

namespace OutSystems.RuntimeSettingsConfiguration {
    public static partial class RuntimeSettingsDefinition {
        public static class Debug {
            public static readonly ISetting<bool> UseShortRequestsOnDebugger = BuildSetting("OutSystems.HubEdition.UseShortRequestsOnDebugger", false);
            // TODO jmt: not used in hubserver
            public static readonly ISetting<bool> AllowDebuggingMobileAppsFromAnyIP = BuildSetting("OutSystems.HubEdition.AllowDebuggingMobileAppsFromAnyIP", false);
            public static readonly ISetting<bool> AllowDebuggingTraditionalAppsFromAnyIp = BuildSetting("OutSystems.HubEdition.AllowDebuggingTraditionalAppsFromAnyIp", false);
            public static readonly ISetting<bool> DebugSetCurrentLocale = BuildSetting("DebugSetCurrentLocale", false);
            public static readonly ISetting<bool> ForceClientSideTracing = BuildSetting("OutSystems.Tracing.ForceClientSideTracing", false);
        }
    }
}
