/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.RuntimeCommon.Settings;

namespace OutSystems.RuntimeSettingsConfiguration {
    public static partial class RuntimeSettingsDefinition {
        public static class Environment {
            public static readonly ISetting<string> Key = BuildSetting<string>("OutSystems.Environment.Key", null);
            public static readonly ISetting<string> Name = BuildSetting<string>("OutSystems.Environment.Name", null);
            public static readonly ISetting<int> ServiceCenterId = BuildSetting("OutSystems.Environment.ServiceCenterId", 1);
            public static readonly ISetting<int> ServiceCenterTenantId = BuildSetting("OutSystems.Environment.ServiceCenterTenantId", 1);
            public static readonly ISetting<string> AdministrationEmail = BuildSetting("OutSystems.Environment.AdministrationEmail", string.Empty);
            public static readonly ISetting<bool> ISAPIFilterEnabled = BuildSetting("OutSystems.Environment.ISAPIFilterEnabled", true);
            public static readonly ISetting<bool> OptimizeTenantViewsCreation = BuildSetting("OutSystems.Environment.OptimizeTenantViewsCreation", true);            
        }
    }
}
