/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.RuntimeCommon.Settings;

namespace OutSystems.RuntimeSettingsConfiguration {
    public static partial class RuntimeSettingsDefinition {
        public static class ExternalConnections {
            public static string BaseKey = "OutSystems.ExternalConnections.";
            public static class DBConnectionSetting {
                public static ISetting<string> DBConnection(string dbConnectionName) => BuildSetting($"{BaseKey}{dbConnectionName}", string.Empty);
            }
        }
    }
}