/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.RuntimeCommon.Settings;

namespace OutSystems.RuntimeSettingsConfiguration {
    public static partial class RuntimeSettingsDefinition {
        public static class Fixes {
            // RPD-3565 advance query flag to control the fix of literals being misinterpreted as identifiers
            public static readonly ISetting<bool> LiteralsMisinterpretedAsIdentifiers = BuildSetting("Fix_LiteralsMisinterpretedAsIdentifiers", true);
        }
    }
}
