/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.RuntimeCommon.Settings;

namespace OutSystems.RuntimeSettingsConfiguration {
    public static partial class RuntimeSettingsDefinition {
        public static class Misc {
            public static readonly ISetting<bool> GenerateLegacyExcell2003 = BuildSetting("OutSystems.HubEdition.GenerateLegacyExcell2003", false);

            public static readonly ISetting<bool> SanitizeSpreadsheetFormulas = BuildSetting("OutSystems.HubEdition.SanitizeSpreadsheetFormulas", true);

            public static readonly ISetting<bool> SanitizeSpreadsheetNumbers = BuildSetting("OutSystems.HubEdition.SanitizeSpreadsheetNumbers", true);

            public static readonly ISetting<string> SettingsKeyPath = BuildSetting("OutSystems.HubEdition.SettingsKeyPath", string.Empty);

            public static readonly ISetting<string> DefaultErrorPage = BuildSetting("OutSystems.HubEdition.DefaultErrorPage", string.Empty);

            // not ossys_parameter. used in the web.config
            public static readonly ISetting<string> UnifiedEspaceKey = BuildSetting("OutSystems.HubEdition.UnifiedEspaceKey", string.Empty);

            public static readonly ISetting<int> DefaultWebReferenceTimeoutMs = BuildSetting("OutSystems.HubEdition.DefaultWebReferenceTimeoutMs", 100000);

            public static readonly ISetting<bool> DisableMetricsCollect = BuildSetting("OutSystems.HubEdition.DisableMetricsCollect", false);
            
            public static readonly ISetting<bool> DisableRuntimeTelemetry = BuildSetting("OutSystems.HubEdition.DisableRuntimeTelemetry", false);

            public static readonly ISetting<string> HTTPtoHTTPSproxyHeader = BuildSetting("OutSystems.HubEdition.HTTPtoHTTPSproxyHeader", string.Empty);

            public static readonly ISetting<bool> JavascriptAPI_ShowHiddenFields = BuildSetting("OutSystems.HubEdition.JavascriptAPI_ShowHiddenFields", false);

            public static readonly ISetting<int> ApplicationServerPort = BuildSetting("ApplicationServerPort", 80);

            public static readonly ISetting<int> ApplicationServerSecurePort = BuildSetting("ApplicationServerSecurePort", 443);

            public static readonly ISetting<string> InternalAddress = BuildSetting("InternalAddress", "127.0.0.1");

            public static readonly ISetting<bool> RuntimeExpect100Continue = BuildSetting("Runtime.Expect100Continue", false);

            public static readonly ISetting<string> CallbackDebugInformationKey = BuildSetting("OutSystems.HubEdition.Callback.DebugInformationKey", string.Empty);

            public static readonly ISetting<bool> RequestTracerExposedIntegrationExecuted = BuildSetting("RequestEvents.ExposedIntegrationExecuted.Enabled", false);

            public static readonly ISetting<bool> RequestTracerServiceActionExecuted = BuildSetting("RequestEvents.ServiceActionExecuted.Enabled", true);

            public static readonly ISetting<bool> RequestTracerInternalCallExecuted = BuildSetting("RequestEvents.InternalCallExecuted.Enabled", false);

            public static readonly ISetting<bool> RequestTracerUndefinedMainEventExecuted = BuildSetting("RequestEvents.TraceEventsFromUndefinedMainTypes.Enabled", false);

            public static readonly ISetting<bool> RequestTracerScreenServerExecutedEnabled = BuildSetting("RequestEvents.ScreenServerExecuted.Enabled", false);

            public static readonly ISetting<bool> RequestTracerTimerExecutedEnabled = BuildSetting("RequestEvents.TimerExecuted.Enabled", false);

            public static readonly ISetting<bool> QueuesAvailable = BuildSetting("OutSystems.HubEdition.QueuesAvailable", false);

            public static readonly ISetting<bool> CompressHttpAjaxResponse = BuildSetting("OutSystems.HubEdition.CompressHttpAjaxResponse", true);

            public static readonly ISetting<int> SlowExtensionCallInMs = BuildSetting("OutSystems.HubEdition.Log.SlowExtensionCallInMs", 200);

            public static readonly ISetting<int> SlowIntegrationInMs = BuildSetting("OutSystems.HubEdition.Log.SlowIntegrationInMs", 200);

            public static readonly ISetting<int> SlowServiceActionInMs = BuildSetting("OutSystems.HubEdition.Log.SlowServiceActionInMs", 200);

            public static readonly ISetting<int> MaxLogsPerRequestAudit = BuildSetting("OutSystems.HubEdition.Log.MaxLogsPerRequestAudit", 3000);

            public static readonly ISetting<int> MaxLogsPerSecondInLogsEndpoint = BuildSetting("OutSystems.HubEdition.Log.MaxLogsPerSecondInLogsEndpoint", 200);

            public static readonly ISetting<int> MaxLogsPerRequestExtension = BuildSetting("OutSystems.HubEdition.Log.MaxLogsPerRequestExtension", 3000);

            public static readonly ISetting<int> CustomErrorStackSize = BuildSetting("OutSystems.HubEdition.Log.CustomErrorStackSize", 2000);

            public static readonly ISetting<string> XUACompatible = BuildSetting("OutSystems.WebPages.X-UA-Compatible", "IE=edge,chrome=1");

            public static readonly ISetting<bool> EnableCoreRestEndpoints = BuildSetting("OutSystems.Development.EnableCoreRestEndpoints", false);

            public static readonly ISetting<bool> DisableCoreSoapEndpoints = BuildSetting("OutSystems.Development.DisableCoreSoapEndpoints", false);

            public static readonly ISetting<int> DatabaseBatchOperationsSize = BuildSetting("OutSystems.RuntimePublic.Users.DatabaseBatchOperationsSize", 100);

            public static readonly ISetting<bool> EnablePTAVersioning = BuildSetting("OutSystems.HubEdition.EnablePTAVersioning", false);

            public static readonly ISetting<bool> ProcessDeletionDeadlockMitigation = BuildSetting("OutSystems.RuntimePublic.ProcessDeletion.DeadlockMitigation", false);

            // Transaction Behaviour
            // Defines the behaviour in order to support Read Committed without MARS support - OP-CR-8940 #RAT-216
            public static readonly ISetting<bool> ReadUncommittedOrReadCommittedWithMARS = BuildSetting("OutSystems.HubEdition.NoMARSSupport", true);
        }
    }
}
