/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Specialized;
using System.Globalization;
using System.IO;
using System.Web;
using System.Web.Configuration;
using System.Web.SessionState;
using OutSystems.HubEdition.Extensibility.Data.Platform.Session;
using OutSystems.RuntimeCommon.Settings;

namespace OutSystems.Application.Session.Persistent.Data {
    public static class SessionIdParser {

        private const string APP_SUFFIX_FORMAT = "x8";

        private static int GetHashCode(string s) {
            int hash = 5381;
            int len = s.Length;

            for (int i = 0; i < len; i++) {
                int c = Convert.ToInt32(s[i]);
                hash = ((hash << 5) + hash) ^ c;
            }

            return hash;
        }

        public static string Parse(string sessionId, ISettingsProvider settingsProvider) {
            string unifiedEspaceKey = settingsProvider.Get(SessionSettings.UnifiedEspaceKey);
            bool useBackwardCompability = settingsProvider.Get(SessionSettings.UseBackwardCompatibilitySessionId);
            var webConfigHasSetting = bool.TryParse(settingsProvider.Get(SessionSettings.UseInMemorySession), out bool applicationIsInMemory);
            
            if (!webConfigHasSetting) {
                applicationIsInMemory = settingsProvider.Get(SessionSettings.UseInMemorySessionId);
            }
            
            if (applicationIsInMemory) {
                return GetInMemorySessionIdentifier(sessionId, unifiedEspaceKey);
            } else if (useBackwardCompability) {
                return GetBackwardCompabilitySessionIdentifier(sessionId, unifiedEspaceKey);
            } else {
                return DefaultSessionIdentifier(sessionId, unifiedEspaceKey);
            }
        }
        
        private static string GetInMemorySessionIdentifier(string sessionId, string unifiedEspaceKey) {
            return unifiedEspaceKey + "_" + sessionId;
        }

        private static string GetBackwardCompabilitySessionIdentifier(string sessionId, string unifiedEspaceKey) {
            string appName = "";
            const string Prefix = "/LM/W3SVC/1/ROOT";

            if (!string.IsNullOrEmpty(unifiedEspaceKey)) {
                appName = Prefix + "/" + unifiedEspaceKey;
            } else if (HttpRuntime.AppDomainAppId != null) {
                // should never happen because setting should be always filled
                appName = Prefix + HttpRuntime.AppDomainAppVirtualPath.ToLower();
            } else {
                throw new InvalidOperationException("Not running as an application");
            }

            string appIdentifier = GetHashCode(appName.ToLower()).ToString(APP_SUFFIX_FORMAT, CultureInfo.InvariantCulture);
            
            return sessionId + appIdentifier;
        }

        private static string DefaultSessionIdentifier(string sessionId, string unifiedEspaceKey) {
            return sessionId + unifiedEspaceKey;
        }
    }

    /// <summary>
    /// Provides session state via SQL Server or Oracle
    /// </summary>
    public class SqlSessionStateStore : SessionStateStoreProviderBase, IDisposable {

        private const int INITIAL_STORE_DATASTREAM_SIZE = 7000;
        private const string INVALID_SESSION_STATE = "The Session State information is invalid and might be corrupted.";

        private static bool s_oneTimeInited = false;

        // Per request info
        private HttpContext _rqContext;
        private int _rqOrigStreamLen;
        private bool _stateFetchedOnCurrentRequest;

        private IPlatformSessionService DatabaseServices { get; }
        private ISettingsProvider SettingsProvider { get; }

        private DatabaseAccessWorkarounds DatabaseWorkarounds { get; }

        public SqlSessionStateStore(IPlatformSessionService sessionDatabase, ISettingsProvider settingsProvider) {
            DatabaseServices = sessionDatabase;
            SettingsProvider = settingsProvider;
            DatabaseWorkarounds = new DatabaseAccessWorkarounds();
        }

        public override void Initialize(string name, NameValueCollection config) {

            if (String.IsNullOrEmpty(name))
                name = "Session State Provider";

            base.Initialize(name, config);

            if (!s_oneTimeInited) {

                var sessionSection = (SessionStateSection) WebConfigurationManager.GetSection("system.web/sessionState");
                DatabaseServices.QueryTimeout = (int) sessionSection.SqlCommandTimeout.TotalSeconds;

                s_oneTimeInited = true;
            }

        }

        public override bool SetItemExpireCallback(SessionStateItemExpireCallback expireCallback) {
            return false;
        }

        public override void Dispose() {
        }

        public override void InitializeRequest(HttpContext context) {
            _rqContext = context;
            _rqOrigStreamLen = 0;
            _stateFetchedOnCurrentRequest = false;
        }

        public override void EndRequest(HttpContext context) {
            _rqContext = null;
        }

        class GetResult {
            public byte[] data;
            public int lockId;
            public bool locked;
            public TimeSpan lockAge;
            public ItemState itemState;
        }

        public SessionStateStoreData DoGet(
            HttpContext context, bool exclusive, string id,
                                        out bool locked,
                                        out TimeSpan lockAge,
                                        out object lockId,
            out SessionStateActions actionFlags) {

            _stateFetchedOnCurrentRequest = true;

            ItemState itemState;

            Func<GetResult> ExecuteGet = () => {
                var getResult = new GetResult();
                getResult.data = exclusive ?
                DatabaseServices.GetAndLock(id, out getResult.lockId, out getResult.locked, out getResult.lockAge, out getResult.itemState) :
                DatabaseServices.Get(id, out getResult.lockId, out getResult.locked, out getResult.lockAge, out getResult.itemState);

                return getResult;
            };

            var result = DatabaseWorkarounds.ExecuteWithoutRequestTimeout(ExecuteGet);

            byte[] data = result.data;
            lockId = result.lockId;
            locked = result.locked;
            lockAge = result.lockAge;
            itemState = result.itemState;

            actionFlags = (SessionStateActions)itemState;

            SessionUtils.SetRetrievedSessionSize(context.Items, data == null ? 0 : data.Length);

            if (data == null) {
                return null;
            }

            using (var s = new MemoryStream(data)) {
                var item = Deserialize(context, s);
                _rqOrigStreamLen = (int)s.Position;
                return item;
            }
        }

        public override SessionStateStoreData GetItem(HttpContext context,
                                                        String id,
                                                        out bool locked,
                                                        out TimeSpan lockAge,
                                                        out object lockId,
                                                        out SessionStateActions actionFlags) {
            return DoGet(context, false, SessionIdParser.Parse(id, SettingsProvider), out locked, out lockAge, out lockId, out actionFlags);
        }

        public override SessionStateStoreData GetItemExclusive(HttpContext context,
                                                String id,
                                                out bool locked,
                                                out TimeSpan lockAge,
                                                out object lockId,
                                                out SessionStateActions actionFlags) {
            return DoGet(context, true, SessionIdParser.Parse(id, SettingsProvider), out locked, out lockAge, out lockId, out actionFlags);
        }

        // This will deserialize and return an item.
        // This version uses the default classes for SessionStateItemCollection, HttpStaticObjectsCollection
        // and SessionStateStoreData
        private static SessionStateStoreData Deserialize(HttpContext context, Stream stream) {
            int timeout;
            SessionStateItemCollection sessionItems;
            bool hasItems;
            bool hasStaticObjects;
            HttpStaticObjectsCollection staticObjects;
            Byte eof;

            try {
                BinaryReader reader = new BinaryReader(stream);
                timeout = reader.ReadInt32();
                hasItems = reader.ReadBoolean();
                hasStaticObjects = reader.ReadBoolean();

                if (hasItems) {
                    sessionItems = SessionStateItemCollection.Deserialize(reader);
                } else {
                    sessionItems = new SessionStateItemCollection();
                }

                if (hasStaticObjects) {
                    staticObjects = HttpStaticObjectsCollection.Deserialize(reader);
                } else {
                    staticObjects = SessionStateUtility.GetSessionStaticObjects(context);
                }

                eof = reader.ReadByte();
                if (eof != 0xff) {
                    throw new HttpException(INVALID_SESSION_STATE);
                }
            } catch (EndOfStreamException) {
                throw new HttpException(INVALID_SESSION_STATE);
            }

            return new SessionStateStoreData(sessionItems, staticObjects, timeout);
        }

        private static SessionStateStoreData CreateLegitStoreData(HttpContext context,
                                                    ISessionStateItemCollection sessionItems,
                                                    HttpStaticObjectsCollection staticObjects,
                                                    int timeout) {
            if (sessionItems == null) {
                sessionItems = new SessionStateItemCollection();
            }

            if (staticObjects == null && context != null) {
                staticObjects = SessionStateUtility.GetSessionStaticObjects(context);
            }

            return new SessionStateStoreData(sessionItems, staticObjects, timeout);
        }

        static private void SerializeStoreData(SessionStateStoreData item, int initialStreamSize, out byte[] buf, out int length) {
            using (var s = new MemoryStream(initialStreamSize)) {
                Serialize(item, s);
                length = (int)s.Length;
                buf = s.GetBuffer();
                Array.Resize(ref buf, length);
            }
        }

        // This method will take an item and serialize it
        private static void Serialize(SessionStateStoreData item, Stream stream) {
            bool hasItems = true;
            bool hasStaticObjects = true;

            BinaryWriter writer = new BinaryWriter(stream);
            writer.Write(item.Timeout);

            if (item.Items == null || item.Items.Count == 0) {
                hasItems = false;
            }
            writer.Write(hasItems);

            if (item.StaticObjects == null || item.StaticObjects.NeverAccessed) {
                hasStaticObjects = false;
            }
            writer.Write(hasStaticObjects);

            if (hasItems) {
                ((SessionStateItemCollection)item.Items).Serialize(writer);
            }

            if (hasStaticObjects) {
                item.StaticObjects.Serialize(writer);
            }

            // Prevent truncation of the stream
            writer.Write(unchecked((byte)0xff));
        }

        public override void ReleaseItemExclusive(HttpContext context,
                                String id,
                                object lockId) {
            int lockCookie = (int)lockId;
            Func<int> ExecuteReleaseLock = () => {
                DatabaseServices.ReleaseLock(SessionIdParser.Parse(id, SettingsProvider), lockCookie);
                return 0;
            };

            DatabaseWorkarounds.ExecuteWithoutRequestTimeout(ExecuteReleaseLock);
        }

        public void SetItemTimeout(string sessionId, int timeout) {
            Func<int> ExecuteResetSessionTimeout = () => {
                DatabaseServices.ResetSessionTimeout(sessionId, new TimeSpan(0, timeout, 0));
                return 0;
            };

            DatabaseWorkarounds.ExecuteWithoutRequestTimeout(ExecuteResetSessionTimeout);
        }

        private void DeleteSession(string sessionId) {

            Func<int> ExecuteDeleteSession = () => {
                DatabaseServices.DeleteSession(SessionIdParser.Parse(sessionId, SettingsProvider));
                return 0;
            };

            DatabaseWorkarounds.ExecuteWithoutRequestTimeout(ExecuteDeleteSession);
        }

        private void ChangeSessionId(string oldSessionId, string newSessionId) {
            Func<int> ExecuteChangeSessionId = () => {
                DatabaseServices.ChangeSessionId(SessionIdParser.Parse(oldSessionId, SettingsProvider), SessionIdParser.Parse(newSessionId, SettingsProvider));
                return 0;
            };
            DatabaseWorkarounds.ExecuteWithoutRequestTimeout(ExecuteChangeSessionId);
        }

        private int GetUserId(string sessionId) {
            Func<int> ExecuteGetUserBySessionId = () => {
                return DatabaseServices.GetUserBySessionId(SessionIdParser.Parse(sessionId, SettingsProvider));
            };

            return DatabaseWorkarounds.ExecuteWithoutRequestTimeout(ExecuteGetUserBySessionId);
        }

        public override void SetAndReleaseItemExclusive(HttpContext context,
                                    string id,
                                    SessionStateStoreData item,
                                    object lockId,
                                    bool newItem) {
            byte[] buf;
            int lockCookie;

            try {
                SerializeStoreData(item, INITIAL_STORE_DATASTREAM_SIZE, out buf, out int length);
            } catch {
                if (!newItem) {
                    ReleaseItemExclusive(context, id, lockId);
                }
                throw;
            }

            // Save it to the store

            if (lockId == null) {
                lockCookie = 0;
            } else {
                lockCookie = (int)lockId;
            }

            Func<int> ExecuteInsert = () => {

                if (newItem) {
                    try {
                        DatabaseServices.Insert(SessionIdParser.Parse(id, SettingsProvider), buf, new TimeSpan(0, item.Timeout, 0));
                    } catch (RepeatedInsertException) {
                        // It's possible that two threads (from the same session) are creating the session
                        // state, both failed to get it first, and now both tried to insert it.
                        // One thread may lose with a Primary Key Violation error. If so, that thread will
                        // just lose and exit gracefully.
                    }
                } else {
                    DatabaseServices.Update(SessionIdParser.Parse(id, SettingsProvider), lockCookie, buf, _rqOrigStreamLen, new TimeSpan(0, item.Timeout, 0));
                }
                return 0;
            };

            DatabaseWorkarounds.ExecuteWithoutRequestTimeout(ExecuteInsert);
        }

        public override void RemoveItem(HttpContext context,
                                        String id,
                                        object lockId,
                                        SessionStateStoreData item) {
            int lockCookie = (int)lockId;


            Func<int> ExecuteDelete = () => {
                DatabaseServices.Delete(SessionIdParser.Parse(id, SettingsProvider), lockCookie);
                return 0;
            };

            DatabaseWorkarounds.ExecuteWithoutRequestTimeout(ExecuteDelete);
        }

        public override void ResetItemTimeout(HttpContext context, string id) {
            if (!_stateFetchedOnCurrentRequest) {
                // #RPC-347
                // This method is called my Asp.Net automatically to extend the timeout of a session
                // Unfortunatelly it does that even for requests that are sessionless (like REST and SOAP) if a session cookie is present
                // Skipping the timeout changes when no session was adquired (or at least tried to adquire) on the current request
                return;
            }

            Func<int> ExecuteResetModuleTimeout = () => {
                DatabaseServices.ResetModuleTimeout(SessionIdParser.Parse(id, SettingsProvider));
                return 0;
            };

            DatabaseWorkarounds.ExecuteWithoutRequestTimeout(ExecuteResetModuleTimeout);
        }

        public override SessionStateStoreData CreateNewStoreData(HttpContext context, int timeout) {
            return CreateLegitStoreData(context, null, null, timeout);
        }

        public override void CreateUninitializedItem(HttpContext context, String id, int timeout) {

            // Store an empty data
            SerializeStoreData(CreateNewStoreData(context, timeout), INITIAL_STORE_DATASTREAM_SIZE, out byte[] buf, out int length);

            try {

                Func<int> ExecuteInsertUninitialized = () => {
                    DatabaseServices.InsertUninitialized(SessionIdParser.Parse(id, SettingsProvider), buf, new TimeSpan(0, timeout, 0));
                    return 0;
                };

                DatabaseWorkarounds.ExecuteWithoutRequestTimeout(ExecuteInsertUninitialized);
            } catch (RepeatedInsertException) {
                // It's possible that two threads (from the same session) are creating the session
                // state, both failed to get it first, and now both tried to insert it.
                // One thread may lose with a Primary Key Violation error. If so, that thread will
                // just lose and exit gracefully.
            }
        }
    }
}