/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

namespace OutSystems.HubEdition.Extensibility.Data.Platform {

    /// <summary>
    /// Represents a set of properties that are specific to a platform database provider.
    /// </summary>
    public interface IPlatformProviderProperties : IProviderProperties {

        /// <summary>
        /// Returns true if the Multiple Database feature is supported for this provider.
        /// </summary>
        /// <value>
        /// True if Multiple Database feature is supported, False otherwise.
        /// </value>
        bool SupportsMultipleDatabases { get; }

        /// <summary>
        /// Returns true if Aggregates/SQL can have their Iteration Multiplicity optimized.<para/>
        /// Setting this as FALSE is the safest way of working around Database Drivers/Engines that do not support Multiple Active Result Sets.
        /// </summary>
        /// <value>
        /// True if Aggregates/SQL can have their Iteration Multiplicity optimized to IterationMultiplicity.Single (e.g. Lazy Loaded), False if it needs to be forced as IterationMultiplicity.Multiple (e.g. Eager Loaded).
        /// </value>
        bool SupportsIterationMultiplicitySingleOptimization { get; }
        
    }
}
