/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.IO;
using System.Net;
using System.Text;
using System.Threading;
using Newtonsoft.Json;

namespace OutSystems.Internal.REST {
    /// <summary>
    /// Class that implements the IOAuth2Client interface,
    /// providing the necessary functionality for interacting with an OAuth2 authorization server using the client credentials grant type.
    /// It encapsulates the logic and operations required to manage the access_token.
    /// </summary>
    internal class OAuth2ClientCredentials : IOAuth2Client {

        private const string HttpPOST = "POST";
        private const string ContentType = "application/x-www-form-urlencoded";
        private const string AuthenticationScheme = "Bearer";
        private readonly OAuth2Configs configs;
        private string access_token = String.Empty;
        private DateTime expirationDate = default; /*1/1/0001 12:0:0 A.M */
        private readonly ReaderWriterLockSlim rwlocker = new ReaderWriterLockSlim();
        private byte[] payloadBytes = null;
        private string authHeader = String.Empty;
        private volatile bool isForcing = false;

        /// <summary>
        /// Public getter that returns the OAuth2Configs object associated with the OAuth2ClientCredentials instance.
        /// It contains the OAuth2 configurations that are used in the token request.
        /// </summary>
        public OAuth2Configs Configs { get => configs; }

        /// <summary>
        /// The internal constructor of the OAuth2ClientCredentials class is used to create an instance of the class with the provided OAuth2Configs object.
        /// </summary>
        internal OAuth2ClientCredentials(OAuth2Configs configs) {
            OAuth2Configs.CheckPreConditions(configs);
            this.configs = configs;
            BuildPayloadAndAuthHeader(configs);
        }

        private void BuildPayloadAndAuthHeader(OAuth2Configs oAuthConfigs) {
            var payload = $"grant_type=client_credentials";

            if (oAuthConfigs.ClientAuthentication == ClientAuthentication.SendInBody) {
                payload = payload + $"&client_id={oAuthConfigs.ClientId}&client_secret={oAuthConfigs.ClientSecret}";
            } else {
                authHeader = Convert.ToBase64String(Encoding.ASCII.GetBytes($"{oAuthConfigs.ClientId}:{oAuthConfigs.ClientSecret}"));
            }

            if (!String.IsNullOrEmpty(configs.Scope)) {
                payload = payload + $"&scope={configs.Scope}";
            }

            payloadBytes = Encoding.UTF8.GetBytes(payload);
        }

        private bool IsTokenExpired() {
            return expirationDate < DateTime.UtcNow;
        }

        public void SetForcing() {
            isForcing = true;
        }

        private HttpWebRequest BuildHttpRequest() {
            var request = (HttpWebRequest)HttpWebRequest.Create(configs.TokenUrl);
            request.Method = HttpPOST;
            request.ContentType = ContentType;

            if (!String.IsNullOrEmpty(authHeader)) {
                request.Headers.Add(HttpRequestHeader.Authorization, $"Basic {authHeader}");
            }

            using (var stream = request.GetRequestStream()) {
                stream.Write(payloadBytes, 0, payloadBytes.Length);
            }

            return request;
        }

        /// <summary>
        /// Method that returns the Authorization header (token_type + access_token).
        /// It retrieves the access_token from the authorization server. 
        /// </summary>
        public string GetAuthorizationHeader(IOAuth2Logger logger) {
            HttpWebRequest request = null;
            HttpWebResponse response = null;
            var responseText = String.Empty;
            try {
                //Concurrent reads are allowed
                rwlocker.EnterReadLock();
                if (IsTokenExpired() || isForcing) {
                    try {
                        rwlocker.ExitReadLock();
                        //writes are atomic and exclusive.
                        rwlocker.EnterWriteLock();
                        if (IsTokenExpired() || isForcing) {
                            try {
                                request = BuildHttpRequest();
                                response = (HttpWebResponse)request.GetResponse();
                            } catch (WebException we) {
                                rwlocker.ExitWriteLock();
                                response = (HttpWebResponse)we.Response;
                                if (response == null) {
                                    throw;
                                }
                            }

                            using (var streamReader = new StreamReader(response.GetResponseStream())) {
                                responseText = streamReader.ReadToEnd();
                                if (String.IsNullOrEmpty(responseText)) {
                                    throw new AuthorizationServerException(response.StatusCode);
                                }

                                if (response.StatusCode < HttpStatusCode.OK || response.StatusCode >= HttpStatusCode.BadRequest) {
                                    throw new AuthorizationServerException(response.StatusCode, responseText);
                                }

                                AuthServerResponse authServerResponse = null;
                                try {
                                    authServerResponse = JsonConvert.DeserializeObject<AuthServerResponse>(responseText);
                                } catch (JsonSerializationException ex) {
                                    throw new AuthorizationServerException(response.StatusCode, responseText, ex);
                                }

                                access_token = authServerResponse.access_token;
                                isForcing = false;
                                //if expires_in is not defined, let's use 1h (3600s)
                                expirationDate = DateTime.UtcNow.AddSeconds(authServerResponse.expires_in > 0 ? authServerResponse.expires_in : 3600);
                                return $"{AuthenticationScheme} {access_token}";
                            }
                        }
                    } finally {
                        if (rwlocker.IsWriteLockHeld) {
                            rwlocker.ExitWriteLock();
                        }
                        if (request != null) {
                            logger.LogRequest(configs, request, payloadBytes);
                            logger.LogResponse(response, responseText);
                        }
                        response?.Dispose();
                    }
                }
            } finally {
                if (rwlocker.IsReadLockHeld) {
                    rwlocker.ExitReadLock();
                }
            }

            try {
                rwlocker.EnterReadLock();
                return $"{AuthenticationScheme} {access_token}";
            } finally {
                if (rwlocker.IsReadLockHeld) {
                    rwlocker.ExitReadLock();
                }
            }
        }
    }
}
