/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Net;
using System.Text;
using Newtonsoft.Json;

namespace OutSystems.Internal.REST {
    /// <summary>
    /// Class for logging HTTP requests and responses during client credentials grant type access token acquisition.
    /// </summary>
    public class OAuth2ClientCredentialsLogger : IOAuth2Logger {

        /// <summary>
        /// Property that holds the logged details of an HTTP request and response made during the client credentials grant type access token acquisition process.  
        /// The property is reset after each request/response.
        /// </summary>
        public StringBuilder HttpTrace {
            get {
                return httpTrace;
            }
        }

        private StringBuilder httpTrace;
        private string redactedString = "[redacted]";

        /// <summary>
        /// The internal constructor of the OAuth2ClientCredentialsLogger class is used to create an instance of the class.
        /// </summary>
        public OAuth2ClientCredentialsLogger() {
            httpTrace = new StringBuilder();
        }

        /// <summary>
        /// Logs the details of an HTTP request made during the client credentials grant type access token acquisition process.
        /// The Authorization header is redacted.
        /// </summary>
        public void LogRequest(OAuth2Configs configs, HttpWebRequest request, byte[] payload) {
            var payloadStr = Encoding.UTF8.GetString(payload);
            
            httpTrace.AppendLine($"{request.Method} {request.RequestUri} HTTP/{request.ProtocolVersion}");

            foreach (var header in request.Headers.AllKeys) {
                var headerValue = request.Headers[header];
                if (configs.ClientAuthentication == ClientAuthentication.SendInHeader && header.Equals("Authorization")) {
                    headerValue = "Basic " + redactedString;
                }
                httpTrace.AppendLine($"{header}: {headerValue}");
            }

            if (configs.ClientAuthentication == ClientAuthentication.SendInHeader) {
                httpTrace.AppendLine($"Client ID: {configs.ClientId}");
            }

            httpTrace.AppendLine();

            if (configs.ClientAuthentication == ClientAuthentication.SendInBody) {
                payloadStr = payloadStr.Replace(configs.ClientSecret, redactedString);
            }

            httpTrace.AppendLine(payloadStr);
            httpTrace.AppendLine();
        }

        /// <summary>
        /// Logs the details of an HTTP response received during the client credentials grant type access token acquisition process.
        /// The response body is redacted.
        /// </summary>
        public void LogResponse(HttpWebResponse response, string responseText) {
            if (response != null) {
                httpTrace.AppendLine($"HTTP/{response.ProtocolVersion} {(int)response.StatusCode} {response.StatusDescription}");

                foreach (var headerName in response.Headers.AllKeys) {
                    var headerValue = response.Headers[headerName];
                    httpTrace.AppendLine($"{headerName}: {headerValue}");
                }
            }

            httpTrace.AppendLine();

            if (!String.IsNullOrEmpty(responseText)) {
                try {
                    var authServerResponse = JsonConvert.DeserializeObject<AuthServerResponse>(responseText);
                    httpTrace.Append(responseText.Replace(authServerResponse.access_token, redactedString));
                } catch (JsonSerializationException) {
                    httpTrace.Append(responseText);
                }
            }
        }
    }
}
