/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.DatabaseProvider.PostgreSQL.ConfigurationService;
using OutSystems.HubEdition.DatabaseProvider.PostgreSQL.DMLService;
using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;

namespace OutSystems.HubEdition.DatabaseProvider.PostgreSQL.DatabaseObjects {
    public class DatabaseInfo : BaseDatabaseInfo {

        public DatabaseInfo(IDatabaseServices databaseServices, string schema) : base(databaseServices) {
            Schema = ((DMLIdentifiers)DatabaseServices.DMLService.Identifiers).UnescapeIdentifier(schema);
            if (string.IsNullOrEmpty(Schema)) {
                DatabaseServices sqlServices = databaseServices as DatabaseServices;
                if (sqlServices != null) {
                    Schema = ((RuntimeDatabaseConfiguration) sqlServices.DatabaseConfiguration).Schema;
                }
            }
        }

        public override sealed string Identifier {
            get {
                return DatabaseServices.DMLService.Identifiers.EscapeIdentifier(Schema);
            }
        }

        public string Schema { get; private set; }

        public override bool Equals(IDatabaseInfo other) {
            DatabaseInfo dbi = other as DatabaseInfo;
            return ReferenceEquals(this, other) || (dbi != null && Schema == dbi.Schema);
        }

        public override int GetHashCode() {
            return Schema.GetHashCode();
        }
    }
}
