/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Text;
using RabbitMQ.Client;

namespace OutSystems.Plugin.RabbitMQ {
    internal static class RabbitMQUtils {
        internal static Encoding Encoding => Encoding.UTF8;

        internal static void DeclareExchange(this IModel channel, string topic) {
            lock (channel) {
                channel.ExchangeDeclare(
                    exchange: topic,
                    type: ExchangeType.Fanout,
                    durable: false,
                    autoDelete: false);
            }
        }

        internal static string DeclareQueue(this IModel channel, string queueName) {
            lock (channel) {
                QueueDeclareOk result = channel.QueueDeclare(
                    queue: queueName,
                    durable: false,
                    exclusive: true,
                    autoDelete: true);

                return result.QueueName;
            }
        }

        internal static void UnbindQueueFromExchange(this IModel channel, string queueName, string topic) {
            lock (channel) {
                channel.QueueUnbind(
                        queue: queueName,
                        exchange: topic,
                        routingKey: string.Empty);
            }
        }

        internal static void DeleteQueue(this IModel channel, string queueName) {
            lock (channel) {
                channel.QueueDelete(
                    queue: queueName,
                    ifEmpty: false,
                    ifUnused: false);
            }
        }

        internal static void BindQueueToExchange(this IModel channel, string queueName, string topic) {
            lock (channel) {
                channel.QueueBind(
                    queue: queueName,
                    exchange: topic,
                    routingKey: string.Empty);
            }
        }

        internal static void BasicConsume(this IModel channel, string queueName, IBasicConsumer consumer) {
            lock (channel) {
                channel.BasicConsume(
                    queue: queueName,
                    autoAck: true,
                    consumer: consumer);
            }
        }

        internal static void BasicCancel(this IModel channel, string consumerTag) {
            lock (channel) {
                channel.BasicCancel(consumerTag);
            }
        }

        internal static void Publish(this IModel channel, string topic, string message) {
            lock (channel) {
                var body = Encoding.GetBytes(message);
                channel.BasicPublish(
                    exchange: topic,
                    routingKey: string.Empty,
                    body: body);
            }
        }
    }
}
