/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Data;
using OutSystems.Internal.Db;

namespace OutSystems.HubEdition.DatabaseAbstractionLayer {
    public static class IDbCommandExtensions {
        public static T ExecuteScalar<T>(this IDbCommand cmd) {
            return DataReaderUtils.SafeGet<T>(cmd.ExecuteScalar());
        }
    }
}
