/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.ObjectKeys;

namespace OutSystems.RuntimeCommon {

    public static class ObjectKeyExtensions {

        public static string DatabaseValue(this ObjectKey key) {
            return ObjectKeyUtils.DatabaseValue(key);
        }

        public static string DatabaseValue(this GlobalObjectKey key) {
            return ObjectKeyUtils.DatabaseValue(key);
        }

        public static ObjectKey ReplaceKeyReference(this ObjectKey key, ObjectKey replaceFrom, ObjectKey replaceTo, out bool changed) {
            return ObjectKeyUtils.ReplaceKeyReference(key, replaceFrom, replaceTo, out changed);
        }
    }
}
