/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.Application.Core.Http;

namespace OutSystems.Application.Initialization.ASPNet.Http {
    public class ASPNetHttpSession : IHttpSession {

        private readonly System.Web.HttpContext wrappedContext;

        public ASPNetHttpSession(System.Web.HttpContext wrappedContext) {
            this.wrappedContext = wrappedContext;
        }

        public string Id => wrappedContext.Session.SessionID;

        public bool IsCookieless => wrappedContext.Session.IsCookieless;
    }
}
