/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.IO;
using OutSystems.Application.Core.Http;

namespace OutSystems.Application.Initialization.ASPNet.Http {
    public class ASPNetRequestFormFile : IRequestFormFile {

        private System.Web.HttpPostedFile formFile;

        public ASPNetRequestFormFile(System.Web.HttpPostedFile formFile) {
            this.formFile = formFile;
        }

        public string ContentType => formFile.ContentType;

        public long Length => formFile.ContentLength;

        public string FileName => formFile.FileName;

        public Stream OpenReadStream() => formFile.InputStream;
    }
}
