/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using OutSystems.Application.Core.Http;

namespace OutSystems.Application.Initialization.ASPNet.Http {
    public class ASPNetRequestFormFiles : IHttpCollection<string, IRequestFormFile> {

        private System.Web.HttpFileCollection wrappedRequestFiles;

        public ASPNetRequestFormFiles(System.Web.HttpFileCollection wrappedRequestFiles) {
            this.wrappedRequestFiles = wrappedRequestFiles;
        }

        public IRequestFormFile this[string key] => new ASPNetRequestFormFile(wrappedRequestFiles[key]);

        public int Count => wrappedRequestFiles.Count;

        public ICollection<string> Keys => wrappedRequestFiles.AllKeys;

        public bool ContainsKey(string key) => wrappedRequestFiles.AllKeys.Contains(key, StringComparer.InvariantCultureIgnoreCase);

        public IEnumerator<KeyValuePair<string, IRequestFormFile>> GetEnumerator() => CollectionAsEnumerable.GetEnumerator();

        public bool TryGetValue(string key, out IRequestFormFile value) {
            if (!ContainsKey(key)) {
                value = null;
                return false;
            }

            value = this[key];
            return true;
        }

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        public IReadOnlyList<IRequestFormFile> GetFiles(string key) {
            return CollectionAsEnumerable.Where(x => x.Key == key).Select(x => x.Value).ToList();
        }

        private IEnumerable<KeyValuePair<string, IRequestFormFile>> CollectionAsEnumerable {
            get => wrappedRequestFiles.Keys.Cast<string>().ToDictionary(key => key, key => (IRequestFormFile) new ASPNetRequestFormFile(wrappedRequestFiles[key]));
        }
    }
}
