/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.Application.Core.Http;
using OutSystems.RuntimeCommon.Settings;

namespace OutSystems.Application.Initialization.ASPNet.Http {

    public class ASPNetHttpRequest : AbstractHttpRequest {

        System.Web.HttpRequest wrappedRequest;

        private Lazy<ASPNetHttpHeaderDictionary> headers;
        private Lazy<ASPNetHttpNameValueCollection> serverVariables;
        private Lazy<ASPNetRequestForm> form;
        private Lazy<ASPNetRequestUri> url;
        private Lazy<ASPNetRequestUri> urlReferrer;
        private Lazy<ASPNetHttpCookieCollection> cookies;
        private Lazy<ASPNetHttpNameValueCollection> parameters;

        public ASPNetHttpRequest(IHttpContext httpContext, ISettingsProvider settingsProvider, System.Web.HttpRequest wrappedRequest)
            : base(httpContext, settingsProvider) {            
            this.wrappedRequest = wrappedRequest;
            headers  = new Lazy<ASPNetHttpHeaderDictionary>(() => new ASPNetHttpHeaderDictionary(() => wrappedRequest.Headers), true);
            serverVariables = new Lazy<ASPNetHttpNameValueCollection>(() => new ASPNetHttpNameValueCollection(() => wrappedRequest.ServerVariables), true);
            form = new Lazy<ASPNetRequestForm>(() => new ASPNetRequestForm(() => wrappedRequest.Form, wrappedRequest.Files), true);
            url = new Lazy<ASPNetRequestUri>(() => new ASPNetRequestUri(() => wrappedRequest.Url), true);
            urlReferrer = new Lazy<ASPNetRequestUri>(() => new ASPNetRequestUri(() => wrappedRequest.UrlReferrer), true);
            cookies = new Lazy<ASPNetHttpCookieCollection>(() => new ASPNetHttpCookieCollection(() => wrappedRequest.Cookies), true);
            parameters = new Lazy<ASPNetHttpNameValueCollection>(() => new ASPNetHttpNameValueCollection(() => wrappedRequest.Params), true);
        }

        public override IHttpCollection<string, string> Cookies => cookies.Value;

        public override IHttpHeaderDictionary Headers => headers.Value;

        public override string UserAgent => wrappedRequest.UserAgent;

        public override string UserHostAddress => wrappedRequest.UserHostAddress;

        public override string UserHostName => wrappedRequest.UserHostName;

        public override bool IsSecureConnection => wrappedRequest.IsSecureConnection;

        public override IRequestUri Url => url.Value;

        public override IRequestUri UrlReferrer => urlReferrer.Value;

        public override string Path => wrappedRequest.Path;

        public override string QueryString => wrappedRequest.QueryString.ToString();

        public override string HttpMethod => wrappedRequest.HttpMethod;

        public override bool IsLocal => wrappedRequest.IsLocal;

        public override string RawUrl => wrappedRequest.RawUrl;

        public override IHttpCollection<string, string> ServerVariables => serverVariables.Value;

        public override IRequestForm Form => form.Value;

        public override IHttpCollection<string, string> Params => parameters.Value;
        public override string ContentType { 
            get => wrappedRequest.ContentType; 
            set => wrappedRequest.ContentType = value; 
        }

        public override string[] UserLanguages => wrappedRequest.UserLanguages;
    }
}
