/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;

namespace OutSystems.HubEdition.Extensibility.Data.Platform.Session {
    public abstract class InMemoryPlatformSessionService : IPlatformSessionService {
        protected InMemoryPlatformSessionService(IPlatformDatabaseServices services) {
            DatabaseServices = services;
        }

        public IPlatformDatabaseServices DatabaseServices { get; }

        // This method does not need to be implemented.
        public virtual void DeleteSession(string sessionId) {
           
        }

        // This method does not need to be implemented, as it will not be called.
        public virtual void ChangeSessionId(string oldSessionId, string newSessionId) {
            throw new NotImplementedException();
        }

        // This method does not need to be implemented, as it will not be called.
        public virtual void ResetSessionTimeout(string sessionId, TimeSpan newTimeout) {
            throw new NotImplementedException();
        }

        // This method does not need to be implemented, as it will not be called.
        public virtual bool Store(string str, int hash, out int ehash, out string collidedStr) {
            throw new NotImplementedException();
        }

        // This method does not need to be implemented, as it will not be called.
        public virtual void ReleaseLock(string sessionId, int lockId) {
            throw new NotImplementedException();
        }

        // This method does not need to be implemented, as it will not be called.
        public virtual byte[] Get(string sessionId, out int lockId, out bool locked, out TimeSpan lockAge, out ItemState state) {
            throw new NotImplementedException();
        }

        // This method does not need to be implemented, as it will not be called.
        public virtual byte[] GetAndLock(string sessionId, out int lockId, out bool locked, out TimeSpan lockAge, out ItemState state) {
            throw new NotImplementedException();
        }

        // This method does not need to be implemented, as it will not be called.
        public virtual void Insert(string sessionId, byte[] data, TimeSpan timeout) {
            throw new NotImplementedException();
        }

        // This method does not need to be implemented, as it will not be called.
        public virtual void InsertUninitialized(string sessionId, byte[] data, TimeSpan timeout) {
            throw new NotImplementedException();
        }

        // This method does not need to be implemented, as it will not be called.
        public virtual void Update(string sessionId, int lockId, byte[] data, int prevDataSize, TimeSpan timeout) {
            throw new NotImplementedException();
        }

        // This method does not need to be implemented, as it will not be called.
        public virtual void Delete(string sessionId, int lockId) {
            
        }

        public virtual byte[] GetModuleItem(string sessionId, string itemId) {
            throw new NotImplementedException();
        }

        public virtual void InsertModuleItem(string sessionId, string itemId, byte[] data, int userId, string cookieId) {
            throw new NotImplementedException();
        }

        public virtual void UpdateModuleItem(string sessionId, string itemId, byte[] data, int userId, string cookieId) {
            throw new NotImplementedException();
        }

        public virtual void InsertModuleItemUser(string sessionId, string itemId, int userId, string cookieId) {
            throw new NotImplementedException();
        }

        public virtual void UpdateModuleItemUser(string sessionId, string itemId, int userId, string cookieId) {
            throw new NotImplementedException();
        }

        public virtual void DeleteModuleItems(string sessionId) {
            
        }
        
        public virtual void ResetModuleTimeout(string sessionId) {
            
        }
        
        // This method needs to return the default value because of Services.InitJobs()
        // Other than that, this method is not needed.
        public virtual int DeleteExpiredSessions() {
            return 0;
        }

        // This method needs to return the default value because of Services.InitJobs()
        // Other than that, this method is not needed.
        public virtual int DeleteExpiredSessionVars() {
            return 0;
        }

        // This method needs to return the default value because of Services.InitJobs()
        // Other than that, this method is not needed.
        public virtual bool ContainsExpiredSessionVarsNewMechanism() {
            return false;
        }
        
        /// <summary>
        /// Checks if the InMemory provider is working. 
        /// Returns always true. Override this method to implement appropriate check.
        /// </summary>
        /// <returns></returns>
        public virtual bool CheckSessionModel() {
            // Only thing the original methods is query the database, so the idea of this method is to see if the
            // InMemory provider is working.
            return true;
        } 
        
        // Needed because of GetSessionsCount
        public virtual void CountConcurrentUsers(DateTime referenceDate, string[] moduleIdsToExclude, out int anon, out int registered,
                                         out DateTime current) {
            anon = 0;
            registered = 0;
            current = DateTime.UtcNow;
        }

        public virtual int GetUserBySessionId(string sessionId) {
             return 0;
        }

        public int QueryTimeout { get; set; }

        public virtual InMemoryPlatformSessionStatus CheckStatus() {
            return null;
        }

        public abstract string GetProviderKey();
    }
}