/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.RuntimeCommon;

namespace OutSystems.DebuggerClient {
    // The methods bellow were copied from Debugger.cs - RuntimePlatform
    public static class DebuggerUtils {
        public static string GetModuleUrl(string host, string eSpaceName, string tenantName, string personalAreaName) {
            return GetUrl(host, new Uri(eSpaceName + (personalAreaName != null ? "/" + personalAreaName : ""), UriKind.Relative));
        }

        public static string GetUrl(string host, Uri debuggerUrlPath) {
            return new Uri(new UriBuilder("http", RuntimeEnvironment.FixHostIPForIPV6(host)).Uri, debuggerUrlPath).AbsoluteUri + "/";
        }
    }
}
