/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Http;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OutSystems.Application.Core;
using OutSystems.Application.Session.Data;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.HubEdition.RuntimePlatform.Log;
using OutSystems.HubEdition.RuntimePlatform.NewRuntime;
using OutSystems.HubEdition.RuntimePlatform.NewRuntime.Authentication;
using OutSystems.Internal.Db;
using OutSystems.RESTService.ErrorHandling;
using OutSystems.RESTService.Runtime.Abstractions.Controllers;
using OutSystems.RuntimeCommon;
using OutSystems.RuntimeCommon.Settings;

namespace OutSystems.RESTService.Controllers {

    public abstract partial class ScreenServicesApiController : RestServiceApiController {

        public static readonly object GlobalScreenServicesInitializationLock = new object();
        private const string RequestTokenHeaderName = CustomHeaderPrefix + "Request-Token";
        private const string CallContextIdHeaderName = CustomHeaderPrefix + "ccid";
        private const string StopImmediatelyHeaderName = CustomHeaderPrefix + "dbg-stop";
        private const string RunToBreakpointHeaderName = CustomHeaderPrefix + "dbg-bkp";
        private const string LocaleHeaderName = CustomHeaderPrefix + "locale";
        internal MobileSessionInfo MobileSessionInfo { get; set; }

        protected virtual ISettingsProvider SettingsProvider => RuntimeSettingsProvider.Instance;

        // Helper class to proxy the static methods of the Screen Services Implementations
        public abstract class BaseScreenControllerProxy : IScreenControllerProxy {
            public abstract CheckPermissionsIndex GetPermissionIndex();
            public abstract IEnumerable<IScreenControllerProxy> GetChildControllers();
            public abstract Type GetControllerType();
            public abstract void EnsureInitialized();
            public abstract Dictionary<string, BinaryContentUtils.DbBinaryConfig> GetDbBinaryConfigs();
        }

        public static Dictionary<string, BinaryContentUtils.DbBinaryConfig> AllDbBinaryConfigs = new Dictionary<string, BinaryContentUtils.DbBinaryConfig>();

        public static void SetDatabaseBinaries(Dictionary<string, BinaryContentUtils.DbBinaryConfig> binaries) {
            // The call to this method could be triggered multiple times and by different threads,
            // since it is being handled by the ASP.NET framework
            lock (typeof(ScreenServicesApiController)) {
                AllDbBinaryConfigs.Clear();
                AllDbBinaryConfigs.AddRange(binaries);
            }
        }

        public ScreenServicesApiController() : base() { }

        protected static void InitPermissionIndexes(CheckPermissionsIndex index, IEnumerable<IScreenControllerProxy> childControllers) {
            foreach (var childControllerProxy in childControllers) {
                childControllerProxy.EnsureInitialized();
                index.AddChildIndex(childControllerProxy.GetPermissionIndex());
            }
        }

        public static IScreenControllerProxy TryGetControllerProxy(Type controllerType) {
            if (controllerType != null && (typeof(ScreenServicesApiController)).IsAssignableFrom(controllerType)) {
                try {
                    return (IScreenControllerProxy)controllerType.GetField("ProxyInstance", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.Public).GetValue(null);
                } catch (Exception ex) {
                    OSTrace.Error("Unable to load controller proxy for " + controllerType.FullName, ex);
                }
            }
            return null;
        }

        protected static void SafeAddChildController(IScreenControllerProxy controllerProxy, HashSet<IScreenControllerProxy> childControllers) {
            childControllers.Add(controllerProxy);
        }

        protected static void SafeAddChildController(string typeStr, string assemblyName, HashSet<IScreenControllerProxy> childControllers) {
            try {
                var controllerType = Type.GetType(string.Format("{0},{1}", typeStr, assemblyName), /*throwOnError*/true);
                var controllerProxy = TryGetControllerProxy(controllerType);
                if (controllerProxy != null) {
                    SafeAddChildController(controllerProxy, childControllers);
                } else {
                    OSTrace.Error("Unable to load controller proxy for " + typeStr);
                }
            } catch (Exception ex) {
                OSTrace.Error("Unable to load controller for " + typeStr, ex);
            }
        }

        protected JsonSerializer JsonSerializer {
            get {
                var serializer = JsonSerializer.CreateDefault(JsonMediaTypeFormater.SerializerSettings);
                serializer.CheckAdditionalContent = false;
                return serializer;
            }
        }

        private IHttpActionResult GetScreenServiceResult(HttpStatusCode status, object dataPayload, Payload.ResponseVersionInfo versionInfo = null, ExceptionPayload exception = null, IEnumerable<string> roles = null, LoginInfo loginInfo = null) {
            var responseMessage = new HttpResponseMessage(status);

            string rolesInfoserialized = null;
            if (loginInfo != null) {
                if (roles != null) {
                    rolesInfoserialized = loginInfo.UpdateRolesHashAndCalculateRolesInfo(roles);
                }

                // This should be passed via dependency injection on the loginInfo constructors instead of being done here.
                // But right now it's not possible to do it in all the places where LoginInfo needs to be constructed.
                loginInfo.WriteLoginInfoToResponse(httpContextAccessor.Context);
            }

            responseMessage.Content = new ObjectContent(typeof(Payload.ResponsePayload),
                new Payload.ResponsePayload(versionInfo, dataPayload, exception, rolesInfoserialized), JsonMediaTypeFormater);

            RestServiceHttpUtils.AddNoCacheHeaders(responseMessage);

            if (DebuggerHelper.IsRunning) {
                if (DebuggerHelper.StopImmediately) {
                    RestServiceHttpUtils.AddCustomHeader(responseMessage, StopImmediatelyHeaderName, DebuggerHelper.StopImmediately.ToString());
                } else if (DebuggerHelper.RunToBreakpoint != null) {
                    RestServiceHttpUtils.AddCustomHeader(responseMessage, RunToBreakpointHeaderName, DebuggerHelper.RunToBreakpoint.ToString(true));
                }
            }

            return ResponseMessage(responseMessage);
        }

        protected delegate object EndpointImplementationDelegate(HeContext heContext, string screenName, JObject screenModel, JObject inputParameters, JObject clientVars);

        protected delegate HttpResponseMessage BinaryEndpointImplementationDelegate(HeContext heContext, string binaryDetails, HttpRequestMessage request, HttpResponseMessage response);

        private void SetCurrentStateFromHeaders() {
            if (DebuggerHelper.IsRunning) {
                if (Request.Headers.TryGetValues(RequestTokenHeaderName, out IEnumerable<string> auxEnum)) {
                    DebuggerHelper.SetCurrentRequestClientToken(auxEnum.FirstOrDefault());
                }

                if (Request.Headers.TryGetValues(CallContextIdHeaderName, out auxEnum)) {
                    DebuggerHelper.SetCurrentCallContextId(auxEnum.FirstOrDefault());
                }

                if (Request.Headers.TryGetValues(StopImmediatelyHeaderName, out auxEnum)) {
                    DebuggerHelper.SetCurrentStopImmediately(auxEnum.FirstOrDefault());
                } else if (Request.Headers.TryGetValues(RunToBreakpointHeaderName, out auxEnum)) {
                    DebuggerHelper.SetCurrentRunToBreakpoint(auxEnum.FirstOrDefault());
                }
            }

            if (Request.Headers.TryGetValues(LocaleHeaderName, out var locales)) {
                var locale = locales.FirstOrDefault();
                new CultureInfo(locale);    //assures that the Locale is known by .Net
                var appInfo = AppInfo.GetAppInfo();
                appInfo.OsContext.CurrentLocale = locale;
            }
        }

        protected IHttpActionResult endpoint_binary(string binaryDetailsCipher) {

            AppInfo appInfo = null;
            HeContext heContext = null;

            try {
                HttpResponseMessage response = new HttpResponseMessage();
                appInfo = AppInfo.GetAppInfo();
                heContext = appInfo.OsContext;

                if (appInfo?.IsApplicationEnabled != true) {
                    response.StatusCode = HttpStatusCode.ServiceUnavailable;
                    return ResponseMessage(response);
                }

                ValidateRequestSecurity();

                var mobileLoginConfiguration = appInfo.GetMobileLoginConfigurations();
                var moduleInfo = ModuleFactory.CreateModuleInfo(heContext);

                var tenantInfo = ModuleFactory.CreateTenantInfo(heContext);

                var httpContext = HttpService.Context;

                var databaseAccess = DatabaseAccess.ForSystemDatabase; // At this point all Authorization/Authentication data is persisted in System Database

                var sessionMetadata = DBSessionMetadata.GetSpecificInstance(databaseAccess.DatabaseServices.DatabaseConfiguration.DatabaseProvider);

                var ssoService = new SSOService(SettingsProvider, httpContext, databaseAccess, sessionMetadata, moduleInfo, mobileLoginConfiguration, tenantInfo, heContext.ApplicationLogger);

                MobileSessionInfo = new MobileSessionInfo(
                                                mobileLoginConfiguration,
                                                LoginInfo.ReadLoginInfoFromRequest(
                                                    mobileLoginConfiguration,
                                                    new MobileCookieNames(moduleInfo.UserProvider.Name, moduleInfo.Name),
                                                    ignoreCSRFToken: true,
                                                    hasSessionStorage: false,
                                                    SettingsProvider),
                                                SettingsProvider,
                                                moduleInfo,
                                                databaseAccess,
                                                sessionMetadata,
                                                ssoService,
                                                heContext.ApplicationLogger);

                heContext.SetSessionInfo(MobileSessionInfo);

                try {
                    MobileSessionInfo.Validate();
                } catch (InvalidLoginException ex) {
                    throw new ExposeRestException("Invalid Login", HttpStatusCode.Forbidden, ex);
                }

                int userId = heContext.Session.UserId;
                var statusCode = (HttpStatusCode)BinaryContentUtils.GetBinaryContent(ScreenServicesApiController.AllDbBinaryConfigs, binaryDetailsCipher, userId, out byte[] content);
                response.StatusCode = statusCode;

                if (statusCode == HttpStatusCode.OK) {
                    string mimeType = RuntimePlatformUtils.GetMIMEType(content, out bool isValidImage);
                    if (!isValidImage && RuntimePlatformSettings.Security.EnforceValidTypesOnBinaryEndpoints.GetValue()) {
                        response = new HttpResponseMessage(HttpStatusCode.InternalServerError);
                    }

                    response.Headers.CacheControl = new CacheControlHeaderValue() {
                        Private = true,
                        MaxAge = TimeSpan.FromDays(7),
                    };

                    response.Headers.AcceptRanges.Clear();
                    response.Headers.AcceptRanges.Add("none");

                    response.Content = new ByteArrayContent(content);
                    response.Content.Headers.ContentType = new MediaTypeHeaderValue(mimeType);
                }

                return ResponseMessage(response);
            } catch (Exception ex) {
                DatabaseAccess.FreeupResources(false);

                var licensingException = ex as LicensingException;
                if (licensingException != null) {
                    return ResponseMessage(new HttpResponseMessage(HttpStatusCode.ServiceUnavailable));
                }

                ErrorLog.LogApplicationError(ex, heContext, "");

                HttpStatusCode errorStatusCode = HttpStatusCode.InternalServerError;
                var exposeRestException = ex as ExposeRestException;
                if (exposeRestException != null) {
                    errorStatusCode = exposeRestException.StatusCode;
                }

                return ResponseMessage(new HttpResponseMessage(errorStatusCode));
            }
        }

        protected IHttpActionResult endpoint(string input, string endpointName, string apiVersion, EndpointImplementationDelegate implementation) {

            AppInfo appInfo = null;
            HeContext heContext = null;
            Payload.ResponseVersionInfo responseVersionInfo = null;
            try {

                appInfo = AppInfo.GetAppInfo();
                heContext = appInfo.OsContext;

                if (appInfo?.IsApplicationEnabled != true) {
                    return GetScreenServiceResult(
                        HttpStatusCode.ServiceUnavailable,
                        GetExceptionPayload(new ApplicationBackendUnavailableException(ApplicationNotEnabledMessage)));
                }

                ValidateRequestSecurity();

                var mobileLoginConfiguration = appInfo.GetMobileLoginConfigurations();

                var moduleInfo = ModuleFactory.CreateModuleInfo(heContext);

                var tenantInfo = ModuleFactory.CreateTenantInfo(heContext);

                var databaseAccess = DatabaseAccess.ForSystemDatabase; // At this point all Authorization/Authentication data is persisted in System Database

                var sessionMetadata = DBSessionMetadata.GetSpecificInstance(databaseAccess.DatabaseServices.DatabaseConfiguration.DatabaseProvider);

                var httpContext = HttpService.Context;

                var ssoService = new SSOService(SettingsProvider, httpContext, databaseAccess, sessionMetadata, moduleInfo, mobileLoginConfiguration, tenantInfo, heContext.ApplicationLogger);

                MobileSessionInfo = new MobileSessionInfo(
                                                mobileLoginConfiguration,
                                                LoginInfo.ReadLoginInfoFromRequest(
                                                    mobileLoginConfiguration,
                                                    new MobileCookieNames(moduleInfo.UserProvider.Name, moduleInfo.Name),
                                                    ignoreCSRFToken: false,
                                                    hasSessionStorage: true,
                                                    SettingsProvider),
                                                SettingsProvider,
                                                moduleInfo,
                                                databaseAccess,
                                                sessionMetadata,
                                                ssoService,
                                                heContext.ApplicationLogger);

                heContext.SetSessionInfo(MobileSessionInfo);

                try {
                    MobileSessionInfo.Validate();
                } catch (InvalidLoginException ex) {
                    throw new ExposeRestException("Invalid Login", HttpStatusCode.Forbidden, ex);
                }

                Payload.RequestPayload requestPayload;
                try {
                    requestPayload = JsonConvert.DeserializeObject<Payload.RequestPayload>(input, BehaviorsConfiguration.SerializerSettings);
                } catch (Exception ex) {
                    throw GetBadRequestException("Failed to parse JSON request content.", ex);
                }

                if (requestPayload.VersionInfo == null) {
                    throw GetBadRequestException("Missing Version Info in the request content.");
                }

                responseVersionInfo = new Payload.ResponseVersionInfo(requestPayload.VersionInfo, RunningInfo.ManifestVersionToken, apiVersion);

                if (responseVersionInfo.HasApiVersionChanged) {
                    return GetScreenServiceResult(
                        HttpStatusCode.OK,
                        dataPayload: new Payload.EmptyDataPayload(),
                        versionInfo: responseVersionInfo,
                        roles: heContext.Session.InternalSession.GetAllRoles(),
                        loginInfo: MobileSessionInfo?.LoginInfo);
                } else {
                    SetCurrentStateFromHeaders();

                    // Set logging context so logout actions have context about which user executed
                    var loggingContext = LoggingHelper.GetLoggingContext();
                    if (loggingContext != null && loggingContext.RequesterUserId == 0 && MobileSessionInfo != null && MobileSessionInfo.LoginInfo != null) {
                        loggingContext.RequesterUserId = MobileSessionInfo.LoginInfo.UserId;
                        loggingContext.RequesterUsername = MobileSessionInfo.LoginInfo.Username;
                        loggingContext.RequesterLoginId = MobileSessionInfo.LoginInfo.LoginId;
                    }

                    object dataResponsePayload = implementation(heContext, requestPayload.ViewName, requestPayload.ScreenData, requestPayload.InputParameters, requestPayload.ClientVariables);

                    // Add current locale to response so that the client side can properly update it
                    httpContext.Response.Headers.Add(LocaleHeaderName, heContext.CurrentLocale);

                    return GetScreenServiceResult(
                        HttpStatusCode.OK,
                        dataPayload: dataResponsePayload,
                        versionInfo: responseVersionInfo,
                        roles: heContext.Session.InternalSession.GetAllRoles(),
                        loginInfo: MobileSessionInfo?.LoginInfo);
                }
            } catch (Exception ex) {
                DatabaseAccess.FreeupResources(false);

                var licensingException = ex as LicensingException;
                if (licensingException != null) {
                    // Already logged
                    return GetScreenServiceResult(
                        HttpStatusCode.ServiceUnavailable,
                        GetExceptionPayload(
                            new ApplicationBackendUnavailableException(
                                ApplicationNotEnabledMessage)));
                }


                HttpStatusCode statusCode = HttpStatusCode.OK;
                var exposeRestException = ex as ExposeRestException;
                if (exposeRestException != null) {
                    statusCode = exposeRestException.StatusCode;
                }

                if (LogRoleRequiredException() || !(ex is NotRegisteredException)) {
                    // Currently for security reasons we log it here and don't let the handler in client side decide. This can generate many "non-errors" to be logged if exceptions are used for flow control
                    string errorLogId = ErrorLog.LogApplicationError(ex, heContext, "");
                    var loggingContext = LoggingHelper.GetLoggingContext();
                    if (loggingContext != null) {
                        loggingContext.ErrorLogId = errorLogId;
                    }
                }

                return GetScreenServiceResult(
                    statusCode,
                    new Payload.EmptyDataPayload(),
                    versionInfo: responseVersionInfo,
                    exception: GetExceptionPayload(ex),
                    roles: heContext.Session.InternalSession.GetAllRoles(),
                    loginInfo: MobileSessionInfo?.LoginInfo);
            } finally {
                MobileSessionInfo = null;
            }
        }

        private bool LogRoleRequiredException() {
            return SettingsProvider.Get(RuntimePlatformSettings.Logging.LogRoleRequiredException);
        }
    }
}
