/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Text;

namespace OutSystems.HubEdition.DatabaseAbstractionLayer.Platform.Configuration.ScriptParser {

    public class DatabaseScriptBlock {
        public DatabaseScriptParsedTag ConditionTag { get; private set; }

        public List<DatabaseScriptStatement> Statements { get; private set; }

        public void SetTagValue(string tag, string val) {
            var scriptTag = (DatabaseScriptTag)Enum.Parse(typeof(DatabaseScriptTag), tag);

            switch (scriptTag) {
                case DatabaseScriptTag.SCRIPT_VERSION:
                    ConditionTag = new DatabaseScriptParsedTag.ScriptVersion {
                        Version = Version.Parse(val)
                    };
                    break;
                case DatabaseScriptTag.VERSION_UPGRADE:
                    ConditionTag = new DatabaseScriptParsedTag.VersionUpgrade {
                        Version = Version.Parse(val)
                    };
                    break;
                case DatabaseScriptTag.COLUMN_NOT_EXISTS: {
                        var tableColumn = SafeSplit(val, '.');
                        ConditionTag = new DatabaseScriptParsedTag.ColumnNotExists {
                            TableName = tableColumn[0],
                            ColumnName = tableColumn[1]
                        };
                    }
                    break;
                case DatabaseScriptTag.COLUMN_EXISTS: {
                        var tableColumn = SafeSplit(val, '.');
                        ConditionTag = new DatabaseScriptParsedTag.ColumnExists {
                            TableName = tableColumn[0],
                            ColumnName = tableColumn[1]
                        };
                    }
                    break;
                case DatabaseScriptTag.TABLE_NOT_EXISTS:
                    ConditionTag = new DatabaseScriptParsedTag.TableNotExists {
                        TableName = UnqualifyTableName(val)
                    };
                    break;
                case DatabaseScriptTag.TABLE_EXISTS:
                    ConditionTag = new DatabaseScriptParsedTag.TableExists {
                        TableName = UnqualifyTableName(val)
                    };
                    break;
                case DatabaseScriptTag.END_IGNORING_BLOCK:
                    ConditionTag = new DatabaseScriptParsedTag.EndIgnoringBlock();
                    break;
                case DatabaseScriptTag.TOUCH_VERSION:
                    ConditionTag = new DatabaseScriptParsedTag.TouchVersion();
                    break;
                case DatabaseScriptTag.INDEX_NOT_EXISTS: {
                        var tableIndex = SafeSplit(val, '.');
                        ConditionTag = new DatabaseScriptParsedTag.IndexNotExists {
                            TableName = tableIndex[0],
                            IndexName = tableIndex[1]
                        };
                    }
                    break;
                case DatabaseScriptTag.INDEX_EXISTS: {
                        var tableIndex = SafeSplit(val, '.');
                        ConditionTag = new DatabaseScriptParsedTag.IndexExists {
                            TableName = tableIndex[0],
                            IndexName = tableIndex[1]
                        };
                    }
                    break;
                case DatabaseScriptTag.FOREIGN_KEY_EXISTS: {
                        var tableForeignKey = SafeSplit(val, '.');
                        ConditionTag = new DatabaseScriptParsedTag.ForeignKeyExists {
                            TableName = tableForeignKey[0],
                            ForeignKeyName = tableForeignKey[1]
                        };
                    }
                    break;
                case DatabaseScriptTag.PRIMARY_KEY_NOT_EXISTS:
                    ConditionTag = new DatabaseScriptParsedTag.PrimaryKeyNotExists {
                        TableName = val
                    };
                    break;
                case DatabaseScriptTag.TABLE_EXISTS_AND_COLUMN_NOT_EXISTS: {
                        var tableColumn = SafeSplit(val, '.');
                        ConditionTag = new DatabaseScriptParsedTag.TableExistsAndColumnNotExists {
                            TableName = tableColumn[0],
                            ColumnName = tableColumn[1]
                        };
                    }
                    break;
                case DatabaseScriptTag.CHECK: {
                        ConditionTag = new DatabaseScriptParsedTag.Check { MethodName = val };
                        break;
                    }
                case DatabaseScriptTag.INVARIANT_INDEX: {
                        break;
                    }
                case DatabaseScriptTag.SPECIFIC_UPGRADE: {
                        break;
                    }
                default:
                    throw new InvalidOperationException($"No parser for block tag '{scriptTag}'");
            }

            Statements = new List<DatabaseScriptStatement>();
        }

        public void AddStatement(string tagName, string tagValue, string statement) {
            if (!string.IsNullOrEmpty(tagName)) {

                var scriptTag = (DatabaseScriptTag)Enum.Parse(typeof(DatabaseScriptTag), tagName);

                switch (scriptTag) {
                    case DatabaseScriptTag.INVARIANT_INDEX:
                        var invariantIndex = SafeSplit(tagValue, ':');
                        Statements.Add(new DatabaseScriptStatement.InvariantIndex {
                            Text = string.Empty,
                            IndexName = invariantIndex[0].Trim(),
                            Fields = invariantIndex[1].Replace(" ", string.Empty).Split(',')
                        });
                        break;
                    case DatabaseScriptTag.DROP_COLUMN:
                        var dropColumn = SafeSplit(tagValue, '.');
                        Statements.Add(new DatabaseScriptStatement.DropColumn {
                            TableName = dropColumn[0],
                            ColumnName = dropColumn[1]
                        });
                        break;
                    case DatabaseScriptTag.SPECIFIC_UPGRADE:
                        Statements.Add(new DatabaseScriptStatement.SpecificUpgrade { MethodName = tagValue });
                        break;
                    default:
                        throw new InvalidOperationException($"Unknown statement tag '{scriptTag}'");
                }


            } else {
                Statements.Add(new DatabaseScriptStatement.SQL { Text = statement });
            }
        }

        public override string ToString() {
            StringBuilder builder = new StringBuilder();
            int i = 0;
            foreach (var statement in Statements) {
                builder.AppendLine("-- Statement #" + i++);
                builder.AppendLine(statement.ToString());
            }
            return ConditionTag + "\n-- Statements: \n" + builder;
        }

        static string UnqualifyTableName(string tableName) {
            var tableNameParts = SafeSplit(tableName, '.');

            switch (tableNameParts.Length) {
                case 1:
                    return tableNameParts[0];
                case 2:
                    return tableNameParts[1];
                default:
                    throw new ArgumentException($"Invalid table name value '{tableName}'");
            }
        }

        private static string[] SafeSplit(string s, char separator) {
            return string.IsNullOrEmpty(s) ? Array.Empty<string>() : s.Split(separator);
        }
    }
}
