/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using OutSystems.ModuleServices;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.RuntimePlatform.Processes {
    public class ActivitiesRestClient : AbstractRestClient, IActivitiesClient {
        private readonly Func<string> authorizationTokenGenerator;

        public ActivitiesRestClient( string moduleUrl,Func<string> authorizationTokenGenerator) :
            base(moduleUrl, ActivitiesApiRoutes.BaseRoute) {
            this.authorizationTokenGenerator = authorizationTokenGenerator;
        }

        protected override void AddHeaders(HttpWebRequest request) {
            request.Headers.Add("Authorization", authorizationTokenGenerator());
        }

        private List<Pair<T1, T2>> DictionaryToPairList<T1, T2>(Dictionary<T1, T2> inputs) {
            return inputs?.Select(kvp => Pair.Create(kvp.Key, kvp.Value)).ToList();
        }

        private Dictionary<T1, T2> PairListToDictionary<T1, T2>(List<Pair<T1, T2>> pairList) {
            return pairList?.ToDictionary(pair => pair.First, pair => pair.Second);
        }

        public bool ExecuteActivityAction(string ssKey, int activityId, int processId, int tenantId, ActivityStatus forInitialStatus, DateTime previousNextRun) {
            var input = new ActivitiesApiPayloads.ExecuteActivityRequest() {
                Key = ssKey,
                ActivityId = activityId,
                ProcessId = processId,
                TenantId = tenantId,
                ForInitialStatus = forInitialStatus,
                PreviousNextRun = previousNextRun
            };

            return ExecutePostRequest<ActivitiesApiPayloads.ExecuteActivityRequest, bool>(BuildEndpointUrl(ActivitiesApiRoutes.Execute), input);
        }

        public bool ExecuteActivityReset(string ssKey, int activityId, int processId, bool resetActivityUser, int tenantId, int userId, string locale, out string failureMessage) {
            var input = new ActivitiesApiPayloads.ActivityResetRequest() {
                Key = ssKey,
                ActivityId = activityId,
                ProcessId = processId,
                ResetActivityUser = resetActivityUser,
                TenantId = tenantId,
                UserId = userId,
                Locale = locale
            };

            var output = ExecutePostRequest<ActivitiesApiPayloads.ActivityResetRequest, ActivitiesApiPayloads.ActivitiesApiBooleanResponse>(BuildEndpointUrl(ActivitiesApiRoutes.Reset), input);

            failureMessage = output.FailureMessage;
            return output.Result;
        }

        public bool ExecuteActivitySchedule(string ssKey, int activityId, int processId, DateTime startDate, int tenantId, int userId, string locale, out string failureMessage) {
            var input = new ActivitiesApiPayloads.ScheduleRequest() {
                Key = ssKey,
                ActivityId = activityId,
                ProcessId = processId,
                StartDate = startDate,
                TenantId = tenantId,
                UserId = userId,
                Locale = locale
            };

            var output = ExecutePostRequest<ActivitiesApiPayloads.ScheduleRequest, ActivitiesApiPayloads.ActivitiesApiBooleanResponse>(BuildEndpointUrl(ActivitiesApiRoutes.Schedule), input);

            failureMessage = output.FailureMessage;
            return output.Result;
        }

        public bool ExecuteOnClose(string ssKey, int activityId, int processId, int tenantId, int userId, string locale, bool advanceProcess, bool skip, bool skipAll, List<Pair<string, object>> inputs, out string failureMessage, out List<Pair<int, ActivityKind>> nextActIds) {
            var input = new ActivitiesApiPayloads.OnCloseRequest() {
                Key = ssKey,
                ActivityId = activityId,
                ProcessId = processId,
                TenantId = tenantId,
                UserId = userId,
                Locale = locale,
                AdvanceProcess = advanceProcess,
                Skip = skip,
                SkipAll = skipAll,
                Inputs = PairListToDictionary(inputs)
            };

            var output = ExecutePostRequest<ActivitiesApiPayloads.OnCloseRequest, ActivitiesApiPayloads.OnCloseResponse>(BuildEndpointUrl(ActivitiesApiRoutes.OnClose), input);

            failureMessage = output.FailureMessage;
            nextActIds = DictionaryToPairList(output.NextActivitiesIds);
            return output.Result;
        }

        public bool ExecuteOnEvent(string ssKey, int activityId, int processId, int tenantId, string dataId, bool advanceProcess) {
            var input = new ActivitiesApiPayloads.OnEventRequest() {
                Key = ssKey,
                ActivityId = activityId,
                ProcessId = processId,
                TenantId = tenantId,
                DataId = dataId,
                AdvanceProcess = advanceProcess
            };

            return ExecutePostRequest<ActivitiesApiPayloads.OnEventRequest, bool>(BuildEndpointUrl(ActivitiesApiRoutes.OnEvent), input);
        }

        public bool ExecuteOnOpen(string ssKey, int activityId, int processId, int tenantId, int userId, string locale, string sessionId, bool requestIsSecure, string hostname, bool onlyGetUrl, out string failureMessage, out string handlingUrl) {
            var input = new ActivitiesApiPayloads.OnOpenRequest() {
                Key = ssKey,
                ActivityId = activityId,
                ProcessId = processId,
                TenantId = tenantId,
                UserId = userId,
                Locale = locale,
                SessionId = sessionId,
                RequestIsSecure = requestIsSecure,
                Hostname = hostname,
                OnlyGetUrl = onlyGetUrl
            };

            var output = ExecutePostRequest<ActivitiesApiPayloads.OnOpenRequest, ActivitiesApiPayloads.OnOpenResponse>(BuildEndpointUrl(ActivitiesApiRoutes.OnOpen), input);

            failureMessage = output.FailureMessage;
            handlingUrl = output.HandlingUrl;
            return output.Result;
        }

        public int ExecuteProcessDefEvent(string ssKey, int tenantId, string dataId) {
            var input = new ActivitiesApiPayloads.DefineEventRequest() {
                Key = ssKey,
                TenantId = tenantId,
                DataId = dataId
            };

            return ExecutePostRequest<ActivitiesApiPayloads.DefineEventRequest, int>(BuildEndpointUrl(ActivitiesApiRoutes.DefEvent), input);
        }

        public int ExecuteProcessLaunch(string ssKey, int tenantId, int userId, int parentActivityId, int parentProcessId, List<Pair<string, object>> inputs, out List<Pair<int, ActivityKind>> nextActIds, out string failureMessage) {
            var input = new ActivitiesApiPayloads.ProcessLaunchRequest() {
                Key = ssKey,
                TenantId = tenantId,
                UserId = userId,
                ParentActivityId = parentActivityId,
                ParentProcessId = parentProcessId,
                Inputs = PairListToDictionary(inputs)
            };

            var output = ExecutePostRequest<ActivitiesApiPayloads.ProcessLaunchRequest, ActivitiesApiPayloads.ProcessLaunchResponse>(BuildEndpointUrl(ActivitiesApiRoutes.LaunchProcess), input);

            failureMessage = output.FailureMessage;
            nextActIds = DictionaryToPairList(output.NextActivitiesIds);
            return output.Result;
        }

        public bool ExecuteProcessTerminate(string ssKey, int processId, int tenantId, int userId, out string failureMessage) {
            var input = new ActivitiesApiPayloads.ProcessLaunchRequest() {
                Key = ssKey,
                ProcessId = processId,
                TenantId = tenantId,
                UserId = userId
            };

            var output = ExecutePostRequest<ActivitiesApiPayloads.ProcessLaunchRequest, ActivitiesApiPayloads.ActivitiesApiBooleanResponse>(BuildEndpointUrl(ActivitiesApiRoutes.TerminateProcess), input);

            failureMessage = output.FailureMessage;
            return output.Result;
        }

        public bool ExecuteRemoveEventFilters(string ssKey, int activityId, int processId, int tenantId) {
            var input = new ActivitiesApiPayloads.ActivitiesApiRequest() {
                Key = ssKey,
                ActivityId = activityId,
                ProcessId = processId,
                TenantId = tenantId
            };

            return ExecutePostRequest<ActivitiesApiPayloads.ActivitiesApiRequest, bool>(BuildEndpointUrl(ActivitiesApiRoutes.RemoveEventFilters), input);
        }

        public bool ExecuteSetEventFilters(string ssKey, int activityId, int processId, int tenantId) {
            var input = new ActivitiesApiPayloads.ActivitiesApiRequest() {
                Key = ssKey,
                ActivityId = activityId,
                ProcessId = processId,
                TenantId = tenantId
            };

            return ExecutePostRequest<ActivitiesApiPayloads.ActivitiesApiRequest, bool>(BuildEndpointUrl(ActivitiesApiRoutes.SetEventFilters), input);
        }

        public bool ExecuteSetProcessSuspension(string ssKey, int processId, bool suspend, int tenantId, int userId, out string failureMessage) {
            var input = new ActivitiesApiPayloads.ProcessSuspensionRequest() {
                Key = ssKey,
                ProcessId = processId,
                Suspend = suspend,
                TenantId = tenantId,
                UserId = userId
            };

            var output = ExecutePostRequest<ActivitiesApiPayloads.ProcessSuspensionRequest, ActivitiesApiPayloads.ActivitiesApiBooleanResponse>(BuildEndpointUrl(ActivitiesApiRoutes.SetProcessSuspension), input);

            failureMessage = output.FailureMessage;
            return output.Result;
        }
    }
}
