/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace OutSystems.RESTService.Controllers {
    public abstract partial class CoreServicesApiController {

        public class Payload {

            [Obsolete("Deprecated on 11.8.0")]
            public class SuccessResponsePayload : SuccessResponsePayload<object> {
                public SuccessResponsePayload(object outputParameters) : base(outputParameters) { }
            }

            public class SuccessResponsePayload<T> {
                [JsonProperty("outputParameters")]
                public T OutputParameters;

                public SuccessResponsePayload(T outputParameters) {
                    OutputParameters = outputParameters;
                }
            }

            public class FailResponsePayload {

                [JsonProperty("exception")]
                public ExceptionPayload Exception;

                public FailResponsePayload(ExceptionPayload exception) {
                    Exception = exception;
                }
            }

            [Obsolete("Deprecated on 11.8.0")]
            public class RequestPayload : RequestPayload<JObject> {

            }

            public class RequestPayload<T> {

                [JsonProperty("requestKey")]
                public string RequestKey;

                [JsonProperty("inputParameters")]
                public T InputParameters;
            }
        }
    }
}
