/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.PluginAPI.PluginConfiguration;

namespace OutSystems.HubEdition.Extensibility.Data.ConfigurationService {

    /// <summary>
    /// Attribute used to identify configuration parameters.
    /// This attribute should be used in a database configuration objects.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public class ConfigurationParameter : Attribute, IPluginConfigurationParameter {

        /// <summary>
        /// Defines if the attribute should be encrypted
        /// </summary>
        public bool Encrypt {
            get;
            set;
        }

        /// <summary>
        /// Defines if this parameter should be persisted
        /// </summary>
        public bool Persist { get; set; } = true;
            
        
        /// <summary>
        /// Defines the full name of Setting.
        /// Optional field.
        /// Note: The setting will need to be saved in the .config file outside of the DAL
        /// </summary>
        public string RuntimeSettingName { get; set; } = null;
    }
}