/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace OutSystems.RESTService.Controllers.PWA {

    public class JSONWithExtraProperties {

        [JsonExtensionData]
        public IDictionary<string, JToken> ExtraProperties { get; set; }
    }

    public class PWAManifestExtensibility : JSONWithExtraProperties {

        public string Name { get; set; }

        [JsonProperty("short_name")]
        public string ShortName { get; set; }

        public string Description { get; set; }

        public string Display { get; set; }

        [JsonProperty("background_color")]
        public string BackgroundColor { get; set; }

        [JsonProperty("theme_color")]
        public string ThemeColor { get; set; }

        public IList<ImageResource> Icons { get; set; }

        [JsonProperty("start_url")]
        public string StartUrl { get; set; }

        public ServiceWorker ServiceWorker { get; set; }
    }

    public class ServiceWorker : JSONWithExtraProperties {

        [JsonProperty("src")]
        public string Source { get; set; }
        public string Scope { get; set; }

        [JsonProperty("update_via_cache")]
        public string UpdateViaCache { get; set; }

        internal ServiceWorker Clone() {
            return new ServiceWorker {
                Source = Source,
                Scope = Scope,
                UpdateViaCache = UpdateViaCache,
                ExtraProperties = ExtraProperties?.ToDictionary(entry => entry.Key, entry => entry.Value)
            };
        }
    }

    public class ImageResource : JSONWithExtraProperties {

        [JsonProperty("src")]
        public string Source { get; set; }
        public string Type { get; set; }
        public string Sizes { get; set; }
        public string Purpose { get; set; }
        public string Platform { get; set; }
    }
}
