/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;

namespace OutSystems.Application.Core.RequestCancelation {

    public sealed class TokenRequestCancelation : IRequestCancelation {

        private static readonly CancellationToken PausedCancelationToken = CancellationToken.None;

        private readonly DateTime requestStartUtc;

        private CancellationTokenSource tokenSource;
        private CancellationToken token;
        private TimeSpan requestSpan;

        public TokenRequestCancelation(int timeout) : this(TimeSpan.FromSeconds(timeout)) {

        }

        public TokenRequestCancelation(TimeSpan timeout) {
            requestStartUtc = DateTime.UtcNow;
            token = PausedCancelationToken;
            CancelWhenElapsed(timeout);
        }

        public TimeSpan GetRequestSpan() {
            return requestSpan;
        }

        public void CancelWhenElapsed(TimeSpan newRequestSpan) {
            if (tokenSource != null) {
                tokenSource.Dispose();
            }

            TimeSpan elapsed = DateTime.UtcNow - requestStartUtc;
            TimeSpan timeLeft = newRequestSpan - elapsed;

            if (timeLeft < TimeSpan.Zero) {
                timeLeft = TimeSpan.Zero;
            }

            if (timeLeft > TimeSpan.FromMilliseconds(int.MaxValue)) {
                // Cancellation Tokens don't accept more than this value.
                timeLeft = TimeSpan.FromMilliseconds(int.MaxValue);
            }

            tokenSource = new CancellationTokenSource(timeLeft);
            token = tokenSource.Token;
            requestSpan = newRequestSpan;
        }

        public void Disable() {
            if (tokenSource != null) {
                tokenSource.Dispose();
            }

            tokenSource = new CancellationTokenSource();
            token = tokenSource.Token;
            requestSpan = TimeSpan.FromSeconds(int.MaxValue);
        }

        public void Pause() {
            token = PausedCancelationToken;
        }

        public void Resume() {
            if (tokenSource != null) {
                token = tokenSource.Token;
            }
        }

        public void ThrowIfCanceled() {
            token.ThrowIfCancellationRequested();
        }

        public void Dispose() {
            if (tokenSource != null) {
                tokenSource.Dispose();
                tokenSource = null;
            }

            token = PausedCancelationToken;
        }
    }
}
