/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Text.RegularExpressions;
using OutSystems.HubEdition.DatabaseProvider.Oracle.Platform.Configuration;
using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.ConfigurationService;
using OutSystems.RuntimeCommon;
using OutSystems.RuntimeCommon.ObfuscationProperties;

namespace OutSystems.HubEdition.DatabaseProvider.Oracle.ConfigurationService {
    [DoNotObfuscate]
    public class DatabaseConfiguration : BaseDatabaseConfiguration {

        private const int DefaultPortValue = 1521;

        public DatabaseConfiguration() {
            Port = DefaultPortValue;
        }

        public override bool Equals(object obj) {
            if (!base.Equals(obj)) {
                return false;
            }

            var other = obj as DatabaseConfiguration;

            return ((other != null) && EqualsBasedOnParts(new object[] { Host, Port, ServiceName, NLSLanguage, DatabaseIdentifier, DbAuthType, Username, Password },
                new object[] { other.Host, other.Port, other.ServiceName, other.NLSLanguage, other.DatabaseIdentifier, other.DbAuthType, other.Username, other.Password }));
        }

        public override int GetHashCode() {
            return base.GetHashCode() ^ GetHashCodeBasedOnParts(Host, Port, ServiceName, NLSLanguage, DatabaseIdentifier, DbAuthType, Username, Password);
        }

        public override IDatabaseProvider DatabaseProvider { get { return Oracle.DatabaseProvider.Instance; } }

        public AuthenticationType DbAuthType { get; set; }

        [UserDefinedConfigurationParameter(Label = "Host", IsMandatory = true, Order = 1, Region = ParameterRegion.DatabaseLocation, Prompt = "Host")]
        public string Host { get; set; }

        [UserDefinedConfigurationParameter(Label = "Port", IsMandatory = true, Order = 2, Region = ParameterRegion.DatabaseLocation, Prompt = "Port")]
        public int Port { get; set; }

        [UserDefinedConfigurationParameter(Label = "Service Name", IsMandatory = true, Order = 3, Region = ParameterRegion.DatabaseLocation, Prompt = "Service Name")]
        public string ServiceName { get; set; }

        [UserDefinedConfigurationParameter(Label = "NLS_LANGUAGE Parameter Value", IsMandatory = false, Order = 4,
            Region = ParameterRegion.UserSpecific,
            Example = "In order to avoid errors when converting dates and numbers,\nthe NLS_LANGUAGE field should be configured according to the NLS_LANGUAGE parameter of the external database.\n\n" + 
                       "If you don't know the value of the extrnal database's NLS_LANGUAGE parameter, you should run the following script:\n" + 
                       "select value from nls_database_parameters where parameter = 'NLS_LANGUAGE';")]
        public string NLSLanguage { get; set; }

        [UserDefinedConfigurationParameter(Label = "NLS_LENGTH_SEMANTICS Parameter Value", IsMandatory = true, Order = 5,
            Region = ParameterRegion.UserSpecific)]
        public NLSLengthSemantics NLSLengthSemantics { get; set; }

        [UserDefinedConfigurationParameter(Label = "Username", IsMandatory = true, Order = 1, Region = ParameterRegion.UserSpecific, Prompt = "Username")]
        public string Username { get; set; }

        [UserDefinedConfigurationParameter(Label = "Password", IsPassword = true, Order = 2, Region = ParameterRegion.UserSpecific, Prompt = "Password")]
        public string Password { get; set; }

        private AdvancedConfiguration advancedConfiguration = new AdvancedConfiguration(
            "Configuration parameters must be separated by a semi-colon ‘;’."
            + " When configured, username and password are automatically added to the generated connection string."
            + " Configuration example: DataSource=<db>;Integrated Security=no",
            "Configuration Parameters",
            "[user id=$Username;password=<hidden>;]$AdvancedConnectionStringField");

        public override AdvancedConfiguration AdvancedConfiguration {
            get {
                return advancedConfiguration;
            }
            set {
                advancedConfiguration = value;
            }
        }

        [ConfigurationParameter]
        public string Schema { get; set; }

        public override string DatabaseIdentifier {
            get { return Schema; }
        }

        protected override string AssembleBasicConnectionString() {
            return ConnectionStringHelper.Build(Username, Password, Host, Port, ServiceName, string.Empty, true);
        }

        protected override string AssembleAdvancedConnectionString() {
            return ConnectionStringHelper.Build(Username, Password, AdvancedConfiguration.AdvancedConnectionStringField);
        }

        private string _connectionStringOverride;
        public override string ConnectionStringOverride {
            get { return _connectionStringOverride; }
            set {
                _connectionStringOverride = value;
                if (_connectionStringOverride.IsNullOrEmpty()) {
                    return;
                }

                Regex userIdRegex = new Regex(@"user id=\s*([^ ;]+)\s*;", RegexOptions.CultureInvariant | RegexOptions.IgnoreCase);
                Match userIdMatch = userIdRegex.Match(_connectionStringOverride + (_connectionStringOverride.EndsWith(";") ? "" : ";"));
                Username = userIdMatch.Groups[1].Value.Replace("\"", "");
            }
        }

        public override IRuntimeDatabaseConfiguration RuntimeDatabaseConfiguration {
            get {
                return new RuntimeDatabaseConfiguration(DatabaseProvider) {
                    ConnectionString = ConnectionString,
                    Schema = Schema,
                    NLS_Language = NLSLanguage,
                    NLS_Length_Semantics = NLSLengthSemantics
                };
            }
        }
    }
}
