/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using Oracle.ManagedDataAccess.Client;
using OutSystems.HubEdition.DatabaseAbstractionLayer.ConfigurationService;
using OutSystems.HubEdition.DatabaseAbstractionLayer.ConfigurationService.DynamicTracing.NotificationPlugin;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.DatabaseProvider.Oracle.ConfigurationService {
    internal class OracleDynamicTracingService : BaseDynamicTracingService {
        internal enum Keys {
            TraceFileLocation,
            TraceFileMaxSize,
            TraceLevel,
            TraceOption
        }

        public OracleDynamicTracingService(string name) : base(name, FileSystemNotifier.Instance, FileSystemNotifier.GetDirectoryFromAssemblyLocation()) {}

        public override void NotifyDelete(IDictionary<string, string> map) {
            if (!IsNotificationValid(map)) {
                return;
            }

            OracleConfiguration.TraceLevel = 0;
        }

        public override void NotifyChange(IDictionary<string, string> map) {
            if (!IsNotificationValid(map)) {
                return;
            }

            // the defaults at time of writing this code are:
            // TraceFileLocation = null 
            // TraceFileMaxSize = 100
            // TraceLevel = 0
            // TraceOption = 0

            OSTrace.Debug($"{nameof(OracleDynamicTracingService)} received notification of dtsconfig change.");
            //  Specifies the destination directory to output provider traces
            if (map.TryGetValue(Keys.TraceFileLocation.ToString(), out var value)) {
                var directory = new DirectoryInfo(value);
                if (directory.Exists) {
                    OracleConfiguration.TraceFileLocation = value;
                } else {
                    OSTrace.Debug($"{directory} does not exist to set to TraceFileLocation.");
                }
            }

            // Specifies the maximum file size of each trace file
            var fileMaxSize = 5120;
            ReadAndSetInt(map, Keys.TraceFileMaxSize, i => { 
                if (i < 0) {
                    return 100;
                } else {
                    return i >= fileMaxSize ? fileMaxSize : i;
                }                
            });

            //  Specifies the generated trace level to trace ODP.NET calls and diagnose provider issues
            ReadAndSetInt(map, Keys.TraceLevel, i => { return i < 0 ? 0 : i; });

            // Specifies whether to generate a single trace file or multiple trace files for multithreaded applications
            ReadAndSetInt(map, Keys.TraceOption, i => { return i < 0 ? 0 : i; });
        }

        internal static bool ReadAndSetInt(IDictionary<string, string> map, Keys key, Func<int, int> sanitizeValue) {
            var status = false;

            var property = typeof(OracleConfiguration).GetProperty(key.ToString(), BindingFlags.Static | BindingFlags.Public);
            
            if (property == null) {
                OSTrace.Debug($"Unable to find property {key}.");
                return status;
            }

            if (map.TryGetValue(key.ToString(), out var value)) {
                if (int.TryParse(value, out var intValue)) {
                    property.SetValue(null, sanitizeValue(intValue));
                    status = true;
                } else {
                    OSTrace.Debug($"Unable to convert {value} to int.");
                }
            }

            return status;
        }
    }
}
