/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using Microsoft.Extensions.DependencyInjection;
using OutSystems.Application.Core.Configuration;

namespace OutSystems.Application.Core {
    public static class ServiceLocator {
        public static IOutsystemsServiceProvider Provider { get; private set; }

        public static T GetService<T>() {
            if (Provider != null) {
                return Provider.GetService<T>();
            }

            return default(T);
        }

        public static object GetService(Type type) {
            if (Provider != null) {
                return Provider.GetService(type);
            }

            return null;
        }

        public static void SetupProvider(IOutsystemsServiceProvider provider) => Provider = provider;
    }
}
