/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Web;
using OutSystems.Application.Core.RequestCancelation;
using OutSystems.HubEdition.RuntimePlatform;

namespace OutSystems.Application.Initialization.ASPNet.Configuration {
    public static class RequestCancellationSetup {
        public static IRequestCancelation GetRequestCancellation() {
            var usingIISRequestCancelation = RuntimeSettingsProvider.Instance.Get(RuntimePlatformSettings.Request.UseIISRequestCancelation) || !AppInfo.GetAppInfo().IsMobileRuntime;
            var tokenRequestTimeout = RuntimeSettingsProvider.Instance.Get(RuntimePlatformSettings.Request.TokenRequestTimeoutInSeconds);

#if !NETSTANDARD
            var defaultTimeout = usingIISRequestCancelation ? HttpContext.Current.Server.ScriptTimeout : tokenRequestTimeout;
#else
            var defaultTimeout = tokenRequestTimeout;
#endif
            IRequestCancelation requestCancelation = null;

#if !NETSTANDARD
            if (usingIISRequestCancelation) {
                requestCancelation = new IISRequestCancelation(
                   /*SetTimeout*/ (timeout) => HttpContext.Current.Server.ScriptTimeout = timeout,
                   /*GetTimeout*/ () => TimeSpan.FromSeconds(HttpContext.Current.Server.ScriptTimeout)
                );
            } else {
#endif
                requestCancelation = new TokenRequestCancelation(defaultTimeout);
#if !NETSTANDARD
                // As a backup plan, for IIS we leave a timeout twice the timeout set
                // to avoid having stale connections with the new mechanism
                var fallbackTimeout = 2 * tokenRequestTimeout;

                var fallbackTimeoutSet = RuntimeSettingsProvider.Instance.Get(RuntimePlatformSettings.Request.TokenRequestFallbackTimeoutInSeconds);

                // We're allowing to set a different timeout value as fallback but it can't
                // be the default of lesser than the timeout set for the mechanism
                if (fallbackTimeoutSet != RuntimePlatformSettings.Request.TokenRequestFallbackTimeoutInSeconds.DefaultValue &&
                    fallbackTimeoutSet > tokenRequestTimeout) {
                    fallbackTimeout = fallbackTimeoutSet;
                }
                HttpContext.Current.Server.ScriptTimeout = fallbackTimeout;
            }
#endif
            return requestCancelation;
        }
    }
}
