/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using Microsoft.Extensions.DependencyInjection;
using OutSystems.Application.Core;
using OutSystems.Application.Core.Http;
using OutSystems.Application.Core.RequestCancelation;
using OutSystems.Application.Initialization.ASPNet.Http;
using OutSystems.HubEdition.Extensibility.Data.Platform.QueryProvider;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.HubEdition.RuntimePlatform.Internal.TelemetryProvider;
using OutSystems.Internal.Db;
using OutSystems.Logging;
using OutSystems.RuntimeCommon.Caching;
using OutSystems.RuntimeCommon.Extensibility.Plugins;
using OutSystems.RuntimeCommon.Settings;
using static OutSystems.HubEdition.RuntimePlatform.ModuleFactory;

namespace OutSystems.Application.Initialization.ASPNet.Configuration {
    public static class ServiceCollectionExtensions {

        public static IServiceCollection AddStartupServices(this IServiceCollection services) {
            return services
                .AddOutsystemsHttpContextAccessor()
                .AddSettingsProvider()
                .AddDatabaseAccess()
                .AddQueryProviders()
                .AddESpaceInfo()
                .AddApplicationInfo()
                .AddApplicationContext()
                .AddApplicationLogService()
                .AddRuntimeCache()
                .AddRequestCancellation()
                .AddRequestTracer();
        }

        public static IServiceCollection AddSettingsProvider(this IServiceCollection services) {
            // SettingsProvider is Transient so that the changes in app settings file are reloaded in runtime
            return services.AddTransient<ISettingsProvider, RuntimeSettingsProvider>();
        }


        public static IServiceCollection AddESpaceInfo(this IServiceCollection services) {
            return services.AddSingleton<ESpaceInfoForAppStart>();
        }

        public static IServiceCollection AddApplicationInfo(this IServiceCollection services) {
            return services.AddSingleton<AppInfo>();
        }

        public static IServiceCollection AddApplicationContext(this IServiceCollection services) {
            //Internal constructor
            return services.AddScoped(_ => new HeContext(
                ServiceLocator.GetService<AppInfo>(),
                HttpService.ContextAccessor,
                ServiceLocator.GetService<IRequestCancelation>()
            ));
        }

        public static IServiceCollection AddOutsystemsHttpContextAccessor(this IServiceCollection services) {
            return services.AddSingleton<IHttpContextAccessor, ASPNetHttpContextAccessor>();
        }

        public static IServiceCollection AddDatabaseAccess(this IServiceCollection services) {
            //Internal constructor
            return services.AddScoped(_ => new DatabaseAccess(
                true, RuntimeSettingsProvider.Instance,
                new TelemetryDBProviderService(ServiceLocator.GetService<ISettingsProvider>())
            ));
        }

        public static IServiceCollection AddRuntimeCache(this IServiceCollection services) {
            return services
                .AddSingleton<CachePluginProvider>()
                .AddSingleton<ICache, RuntimeCache>();
        }

        public static IServiceCollection AddRequestTracer(this IServiceCollection services) {
            return services.AddScoped<RequestTracer>();
        }

        public static IServiceCollection AddApplicationLogService(this IServiceCollection services) {
            return services
                .AddSingleton<AbstractPluginProvider<string, ILoggingPlugin>, LoggingPluginProvider>()
                .AddDatabaseAccessService()
                .AddLoggingDatabaseService()
                .AddSingleton<IApplicationInfo, ApplicationInfoWrapper>()
                .AddSingleton<IModuleInfo, ModuleInfoWrapper>()
                .AddSingleton<ITenantInfo, TenantInfoWrapper>()
                .AddScoped<IRequestInfo, RequestInfoWrapper>()
                .AddScoped<ApplicationLogService>();
        }

        public static IServiceCollection AddRequestCancellation(this IServiceCollection services) {
            //Needs configuration to be instantiated
            return services.AddScoped(_ => RequestCancellationSetup.GetRequestCancellation());
        }

        public static IServiceCollection AddQueryProviders(this IServiceCollection services) {
            //Needs configuration to be instantiated
            return services
                .AddScoped(_ => BaseQueryProvider<DBRuntimePlatform>.GetInstance())
                //.AddSingleton(_ => BaseQueryProvider<DBSessionMetadata>.GetInstance())
                ;
        }
    }
}