/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.ObjectKeys;
using OutSystems.RuntimeCommon;
using OutSystems.RuntimeSettingsConfiguration;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Xml;

#region Aliases

using MiscSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Misc;
using LoggingSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Logging;
using RequestSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Request;
using CacheSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Cache;
using ModuleSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Module;
using ApplicationSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Application;
using EnvironmentSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Environment;
using ScreenServicesSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.ScreenServices;
using ServiceAPIsSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.ServiceAPIs;
using SitePropertiesSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.SiteProperties;
using CacheInvalidationSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Plugin.CacheInvalidation;
using CatalogSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Catalog;
using InternalNetworkSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.InternalNetwork;
using QueriesSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Queries;
using DebugSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Debug;
using AuthenticationSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Authentication;
using SecuritySettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Security;
using ContentSecurityPolicySettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.ContentSecurityPolicy;
using EMailSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.EMail;
using BPTSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.BPT;
using TimersSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Timers;
using SMSSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.SMS;
using SandboxSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Sandbox;
using ProcessesSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Processes;
using ViewStateSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.ViewState;
using EntitySettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Entity;
using ExternalConnectionsSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.ExternalConnections;
using FixesSettings = OutSystems.RuntimeSettingsConfiguration.RuntimeSettingsDefinition.Fixes;
using OutSystems.RuntimeCommon.Settings;

#endregion Aliases

namespace OutSystems.HubEdition.RuntimePlatform {
    public static class RuntimePlatformSettings {

        public static class Misc {

            public static readonly RuntimeSetting<bool> GenerateLegacyExcell2003 = MiscSettings.GenerateLegacyExcell2003.ForRuntime();

            public static readonly RuntimeSetting<bool> SanitizeSpreadsheetFormulas = MiscSettings.SanitizeSpreadsheetFormulas.ForRuntime();

            public static readonly RuntimeSetting<bool> SanitizeSpreadsheetNumbers = MiscSettings.SanitizeSpreadsheetNumbers.ForRuntime();

            public static readonly RuntimeSetting<string> SettingsKeyPath = MiscSettings.SettingsKeyPath.ForRuntime();

            public static readonly RuntimeSetting<string> DefaultErrorPage = MiscSettings.DefaultErrorPage.ForRuntime();

            //// not ossys_parameter. used in the web.config
            public static readonly RuntimeSetting<string> UnifiedEspaceKey = MiscSettings.UnifiedEspaceKey.ForRuntime();

            public static readonly RuntimeSetting<int> DefaultWebReferenceTimeoutMs = MiscSettings.DefaultWebReferenceTimeoutMs.ForRuntime();

            public static readonly RuntimeSetting<bool> DisableMetricsCollect = MiscSettings.DisableMetricsCollect.ForRuntime();

            public static readonly RuntimeSetting<bool> DisableRuntimeTelemetry = MiscSettings.DisableRuntimeTelemetry.ForRuntime();

            public static readonly RuntimeSetting<string> HTTPtoHTTPSproxyHeader = MiscSettings.HTTPtoHTTPSproxyHeader.ForRuntime();

            public static readonly RuntimeSetting<bool> JavascriptAPI_ShowHiddenFields = MiscSettings.JavascriptAPI_ShowHiddenFields.ForRuntime();

            public static readonly RuntimeSetting<int> ApplicationServerPort = MiscSettings.ApplicationServerPort.ForRuntime();

            public static readonly RuntimeSetting<int> ApplicationServerSecurePort = MiscSettings.ApplicationServerSecurePort.ForRuntime();

            public static readonly RuntimeSetting<string> InternalAddress = MiscSettings.InternalAddress.ForRuntime();

            public static readonly RuntimeSetting<bool> RuntimeExpect100Continue = MiscSettings.RuntimeExpect100Continue.ForRuntime();

            public static readonly RuntimeSetting<string> CallbackDebugInformationKey = MiscSettings.CallbackDebugInformationKey.ForRuntime();

            public static readonly RuntimeSetting<bool> RequestTracerExposedIntegrationExecuted = MiscSettings.RequestTracerExposedIntegrationExecuted.ForRuntime();

            public static readonly RuntimeSetting<bool> RequestTracerServiceActionExecuted = MiscSettings.RequestTracerServiceActionExecuted.ForRuntime();

            public static readonly RuntimeSetting<bool> RequestTracerInternalCallExecuted = MiscSettings.RequestTracerInternalCallExecuted.ForRuntime();

            public static readonly RuntimeSetting<bool> RequestTracerUndefinedMainEventExecuted = MiscSettings.RequestTracerUndefinedMainEventExecuted.ForRuntime();

            public static readonly RuntimeSetting<bool> RequestTracerScreenServerExecutedEnabled = MiscSettings.RequestTracerScreenServerExecutedEnabled.ForRuntime();

            public static readonly RuntimeSetting<bool> RequestTracerTimerExecutedEnabled = MiscSettings.RequestTracerTimerExecutedEnabled.ForRuntime();

            public static readonly RuntimeSetting<bool> QueuesAvailable = MiscSettings.QueuesAvailable.ForRuntime();

            public static readonly RuntimeSetting<bool> CompressHttpAjaxResponse = MiscSettings.CompressHttpAjaxResponse.ForRuntime();

            public static readonly RuntimeSetting<int> SlowExtensionCallInMs = MiscSettings.SlowExtensionCallInMs.ForRuntime();

            public static readonly RuntimeSetting<int> SlowIntegrationInMs = MiscSettings.SlowIntegrationInMs.ForRuntime();

            public static readonly RuntimeSetting<int> SlowServiceActionInMs = MiscSettings.SlowServiceActionInMs.ForRuntime();

            public static readonly RuntimeSetting<int> MaxLogsPerRequestAudit = MiscSettings.MaxLogsPerRequestAudit.ForRuntime();

            public static readonly RuntimeSetting<int> MaxLogsPerSecondInLogsEndpoint = MiscSettings.MaxLogsPerSecondInLogsEndpoint.ForRuntime();

            public static readonly RuntimeSetting<int> MaxLogsPerRequestExtension = MiscSettings.MaxLogsPerRequestExtension.ForRuntime();

            public static readonly RuntimeSetting<int> CustomErrorStackSize = MiscSettings.CustomErrorStackSize.ForRuntime();

            public static readonly RuntimeSetting<string> XUACompatible = MiscSettings.XUACompatible.ForRuntime();

            public static readonly RuntimeSetting<bool> EnableCoreRestEndpoints = MiscSettings.EnableCoreRestEndpoints.ForRuntime();

            public static readonly RuntimeSetting<bool> DisableCoreSoapEndpoints = MiscSettings.DisableCoreSoapEndpoints.ForRuntime();

            public static readonly RuntimeSetting<int> DatabaseBatchOperationsSize = MiscSettings.DatabaseBatchOperationsSize.ForRuntime();

            public static readonly RuntimeSetting<bool> EnablePTAVersioning = MiscSettings.EnablePTAVersioning.ForRuntime();

            public static readonly RuntimeSetting<bool> ProcessDeletionDeadlockMitigation = MiscSettings.ProcessDeletionDeadlockMitigation.ForRuntime();

            //// Transaction Behaviour
            //// Defines the behaviour in order to support Read Committed without MARS support - OP-CR-8940 #RAT-216
            public static readonly RuntimeSetting<bool> ReadUncommittedOrReadCommittedWithMARS = MiscSettings.ReadUncommittedOrReadCommittedWithMARS.ForRuntime();
        }

        public static class Logging {
            public static readonly RuntimeSetting<string> RedactedSensitiveHeaders = LoggingSettings.RedactedSensitiveHeaders.ForRuntime();
            public static readonly ISetting<string> SearchAPIToken = LoggingSettings.SearchAPIToken.ForRuntime();
            public static readonly ISetting<string> SearchAPIAuthorization = LoggingSettings.SearchAPIAuthorization.ForRuntime();
            public static readonly ISetting<string> SearchAPIUrl = LoggingSettings.SearchAPIUrl.ForRuntime();
            public static readonly ISetting<string> EnvironmentOrn = LoggingSettings.EnvironmentOrn.ForRuntime();
            
            // RPM-2509: disables NotRegisteredException logs.
            public static readonly RuntimeSetting<bool> LogRoleRequiredException = LoggingSettings.LogRoleRequiredException.ForRuntime();
        }

        public static class Request {
            public static readonly RuntimeSetting<bool> UseIISRequestCancelation = RequestSettings.UseIISRequestCancelation.ForRuntime();
            public static readonly RuntimeSetting<int> TokenRequestTimeoutInSeconds = RequestSettings.TokenRequestTimeoutInSeconds.ForRuntime();
            public static readonly RuntimeSetting<int> TokenRequestFallbackTimeoutInSeconds = RequestSettings.TokenRequestFallbackTimeoutInSeconds.ForRuntime();
        }

        public static class Cache {
            public static readonly RuntimeSetting<string> CacheControlPath = CacheSettings.CacheControlPath.ForRuntime();
        }

        public static class Module {
            [Obsolete("Please use ForKey().Id()")]
            public static readonly RuntimeSetting<int> Id = ModuleSettings.Id.ForRuntime();

            [Obsolete("Please use ForKey().VersionId")]
            public static readonly RuntimeSetting<int> VersionId = ModuleSettings.VersionId.ForRuntime();

            [Obsolete]
            public static readonly RuntimeSetting<bool> IsActive = ModuleSettings.IsActive.ForRuntime();

            public static readonly RuntimeSetting<string> PersonalAreaName = ModuleSettings.PersonalAreaName.ForRuntime();
            public static readonly RuntimeSetting<int> DefaultTenantId = ModuleSettings.DefaultTenantId.ForRuntime();

            public static readonly RuntimeSetting<string> HMAC = ModuleSettings.HMAC.ForRuntime();
            public static readonly RuntimeSetting<string> CompilationDate = ModuleSettings.CompilationDate.ForRuntime();

            public static readonly RuntimeSetting<bool> PerformanceMonitoringEnabled = ModuleSettings.PerformanceMonitoringEnabled.ForRuntime();
            public static readonly RuntimeSetting<bool> AllowAuditing = ModuleSettings.AllowAuditing.ForRuntime();
            public static readonly RuntimeSetting<bool> AllowLogging = ModuleSettings.AllowLogging.ForRuntime();
            public static readonly RuntimeSetting<bool> RemoteShowStack = ModuleSettings.RemoteShowStack.ForRuntime();
			public static readonly RuntimeSetting<bool> EnableSchemaCompliance = ModuleSettings.EnableSchemaCompliance.ForRuntime();
            public static readonly RuntimeSetting<bool> HasEPAEnabled = ModuleSettings.HasEPAEnabled.ForRuntime();

            public static readonly RuntimeSetting<bool> MobileCookieDebug = ModuleSettings.MobileCookieDebug.ForRuntime();

            public static string BuildKey(string settingName) => ModuleSettings.BuildKey(settingName);

            public static ModuleSetting ForKey(ObjectKey moduleKey) {
                return new ModuleSetting(moduleKey);
            }

            public static ModuleSetting ForKey(string moduleKey) {
                return ForKey(ObjectKey.Parse(moduleKey));
            }

            public class ModuleSetting {
                private readonly ObjectKey ModuleKey;

                public ModuleSetting(ObjectKey ModuleKey) {
                    this.ModuleKey = ModuleKey;
                }

                public RuntimeSetting<string> VersionToken => ModuleSettings.ModuleSetting.VersionToken(ModuleKey).ForRuntime();

                public RuntimeSetting<int> VersionId => ModuleSettings.ModuleSetting.VersionId(ModuleKey).ForRuntime();

                public RuntimeSetting<int> Id(int idValue = 0) => ModuleSettings.ModuleSetting.Id(ModuleKey).ForRuntime(idValue);

                public RuntimeSetting<T> ForSetting<T>(string settingName, T defaultValue = default(T)) =>
                    ModuleSettings.ModuleSetting.GetSetting(ModuleKey, settingName, defaultValue).ForRuntime();
            }
        }

        public static class Application {
            public static readonly RuntimeSetting<string> Key = ApplicationSettings.Key.ForRuntime();
            public static readonly RuntimeSetting<string> Name = ApplicationSettings.Name.ForRuntime();
            public static readonly RuntimeSetting<string> Description = ApplicationSettings.Description.ForRuntime();
            public static readonly RuntimeSetting<string> PrimaryColor = ApplicationSettings.PrimaryColor.ForRuntime();
            public static readonly RuntimeSetting<bool> IsPWAEnabled = ApplicationSettings.IsPWAEnabled.ForRuntime();
            public static readonly RuntimeSetting<bool> IsALDEnabled = ApplicationSettings.IsALDEnabled.ForRuntime();
            public static readonly RuntimeSetting<string> ApplicationURL = ApplicationSettings.ApplicationURL.ForRuntime();
            public static readonly RuntimeSetting<bool> IsAutoUpgradeDisabled = ApplicationSettings.IsAutoUpgradeDisabled.ForRuntime();
            public static readonly RuntimeSetting<string> ExtensibilityConfiguration = ApplicationSettings.ExtensibilityConfiguration.ForRuntime();
            public static readonly RuntimeSetting<string> ModuleNames = ApplicationSettings.ModuleNames.ForRuntime();
            public static readonly RuntimeSetting<bool> Enabled = ApplicationSettings.Enabled.ForRuntime();
            public static readonly RuntimeSetting<int> DefaultTimeout = ApplicationSettings.DefaultTimeout.ForRuntime();
            public static readonly RuntimeSetting<bool> IsApplication = ApplicationSettings.IsApplication.ForRuntime();
            public static readonly RuntimeSetting<bool> IsInIsolatedDB = ApplicationSettings.IsInIsolatedDB.ForRuntime();
        }

        public static class Environment {
            public static readonly RuntimeSetting<string> Key = EnvironmentSettings.Key.ForRuntime();
            public static readonly RuntimeSetting<string> Name = EnvironmentSettings.Name.ForRuntime();
            public static readonly RuntimeSetting<int> ServiceCenterId = EnvironmentSettings.ServiceCenterId.ForRuntime();
            public static readonly RuntimeSetting<int> ServiceCenterTenantId = EnvironmentSettings.ServiceCenterTenantId.ForRuntime();
            public static readonly RuntimeSetting<string> AdministrationEmail = EnvironmentSettings.AdministrationEmail.ForRuntime();
            public static readonly RuntimeSetting<bool> ISAPIFilterEnabled = EnvironmentSettings.ISAPIFilterEnabled.ForRuntime();
            public static readonly RuntimeSetting<bool> OptimizeTenantViewsCreation = EnvironmentSettings.OptimizeTenantViewsCreation.ForRuntime();
        }

        public static class ScreenServices {
            public static readonly RuntimeSetting<bool> TraceAll = ScreenServicesSettings.TraceAll.ForRuntime();
            public static readonly RuntimeSetting<bool> TraceErrors = ScreenServicesSettings.TraceErrors.ForRuntime();
        }

        public static class ServiceAPIs {
            public static readonly RuntimeSetting<bool> TraceAll = ServiceAPIsSettings.TraceAll.ForRuntime();
            public static readonly RuntimeSetting<bool> TraceErrors = ServiceAPIsSettings.TraceErrors.ForRuntime();
            // request lifetime in seconds
            public static readonly RuntimeSetting<int> RequestLifetime = ServiceAPIsSettings.RequestLifetime.ForRuntime();
            public static readonly RuntimeSetting<int> RequestTimeoutInSeconds = ServiceAPIsSettings.RequestTimeoutInSeconds.ForRuntime();
        }

        public static class SiteProperties {
            public static readonly RuntimeSetting<bool> LogRuntimeChanges = SitePropertiesSettings.LogRuntimeChanges.ForRuntime();
            public static readonly RuntimeSetting<string> EncryptionKey = SitePropertiesSettings.EncryptionKey.ForRuntime();

            public static ReadOnlySiteProperty ForModule(ObjectKey moduleKey) {
                return ReadOnlySiteProperty.ForModule(moduleKey);
            }

            public class ReadOnlySiteProperty {
                [Obsolete("Use RuntimeSettingsConfiguration")]
                public static string BuildKey(ObjectKey moduleKey, ObjectKey sitePropertyKey, string settingName) {
                    return $"OutSystems.SiteProperties.{ObjectKeyUtils.DatabaseValue(moduleKey)}.{ObjectKeyUtils.DatabaseValue(sitePropertyKey)}.{settingName}";
                }

                private ObjectKey ModuleKey { get; }
                private ObjectKey SitePropertyKey { get; set; }

                private ReadOnlySiteProperty(ObjectKey moduleKey) {
                    ModuleKey = moduleKey;
                }

                public static ReadOnlySiteProperty ForModule(ObjectKey moduleKey) {
                    return new ReadOnlySiteProperty(moduleKey);
                }

                public ReadOnlySiteProperty ForSiteProperty(ObjectKey sitePropertyKey) {
                    SitePropertyKey = sitePropertyKey;
                    return this;
                }

                public RuntimeSetting<string> DataValue() {
                    ValidateSitePropertyKey();
                    return SitePropertiesSettings.ReadOnlySiteProperty.DataValue(ModuleKey, SitePropertyKey).ForRuntime();
                }

                public RuntimeSetting<string> DataType() {
                    ValidateSitePropertyKey();
                    return SitePropertiesSettings.ReadOnlySiteProperty.DataType(ModuleKey, SitePropertyKey).ForRuntime();
                }

                public RuntimeSetting<bool> IsSecret() {
                    ValidateSitePropertyKey();
                    return SitePropertiesSettings.ReadOnlySiteProperty.IsSecret(ModuleKey, SitePropertyKey).ForRuntime();
                }
                
                public RuntimeSetting<bool> IsActive() {
                    ValidateSitePropertyKey();
                    return SitePropertiesSettings.ReadOnlySiteProperty.IsActive(ModuleKey, SitePropertyKey).ForRuntime();
                }

                private void ValidateSitePropertyKey() {
                    if (SitePropertyKey is null) {
                        throw new Exception("The 'SitePropertyKey' needs to be defined.");
                    }
                }
            }
        }

        public static class Plugin {
            public static class CacheInvalidation {
                public static readonly RuntimeSetting<string> CacheProviderKey = CacheInvalidationSettings.CacheProviderKey.ForRuntime();
                public static readonly RuntimeSetting<bool> EnableRabbitMQCacheInvalidation = CacheInvalidationSettings.EnableRabbitMQCacheInvalidation.ForRuntime();
                public static readonly RuntimeSetting<string> RabbitMQAddress = CacheInvalidationSettings.RabbitMQAddress.ForRuntime();
                public static readonly RuntimeSetting<int> RabbitMQPort = CacheInvalidationSettings.RabbitMQPort.ForRuntime();
                public static readonly RuntimeSetting<string> RabbitMQUsername = CacheInvalidationSettings.RabbitMQUsername.ForRuntime();
                public static readonly RuntimeSetting<string> RabbitMQPassword = CacheInvalidationSettings.RabbitMQPassword.ForRuntime();
                public static readonly RuntimeSetting<string> RabbitMQVirtualHost = CacheInvalidationSettings.RabbitMQVirtualHost.ForRuntime();
                public static readonly RuntimeSetting<bool> RabbitMQTlsEnabled = CacheInvalidationSettings.RabbitMQTlsEnabled.ForRuntime();
                public static readonly RuntimeSetting<string> RabbitMQTlsServerCanonicalName = CacheInvalidationSettings.RabbitMQTlsServerCanonicalName.ForRuntime();
                public static readonly RuntimeSetting<int> RabbitMQConnectionTimeout = CacheInvalidationSettings.RabbitMQConnectionTimeout.ForRuntime();
                public static readonly RuntimeSetting<int> RabbitMQConnectionHeartbeat = CacheInvalidationSettings.RabbitMQConnectionHeartbeat.ForRuntime();
                public static readonly RuntimeSetting<string> FileBasedCacheProviderKey = CacheInvalidationSettings.FileBasedCacheProviderKey.ForRuntime();
            }

            public static string GetSettingKey(string pluginName, string moduleKey, string pluginKey, string settingName) =>
                RuntimeSettingsDefinition.Plugin.GetSettingKey(pluginName, moduleKey, pluginKey, settingName);

            public static RuntimeSetting<T> GetSetting<T>(string pluginName, string moduleKey, string pluginKey, string settingName, T defaultValue, bool isEncrypted = false) =>
                RuntimeSettingsDefinition.Plugin.GetSetting(pluginName, moduleKey, pluginKey, settingName, defaultValue, isEncrypted).ForRuntime();
        }

        public static class Catalog {
            public class ModuleCatalogSetting {
                private string ModuleKey { get; set; }

                public ModuleCatalogSetting(string moduleKey) => this.ModuleKey = moduleKey;

                public RuntimeSetting<string> Catalog => CatalogSettings.ModuleCatalogSetting.Catalog(ModuleKey).ForRuntime();
            }

            public static ModuleCatalogSetting ForModule(string moduleKey) {
                return new ModuleCatalogSetting(moduleKey);
            }

            public class CatalogConfigurationSetting {
                private string CatalogName { get; set; }

                public CatalogConfigurationSetting(string catalogName) {
                    this.CatalogName = catalogName;
                }

                public RuntimeSetting<string> Name => CatalogSettings.CatalogConfigurationSetting.Name(CatalogName).ForRuntime();

                public RuntimeSetting<string> Catalog => CatalogSettings.CatalogConfigurationSetting.Catalog(CatalogName).ForRuntime();

                public RuntimeSetting<string> Schema => CatalogSettings.CatalogConfigurationSetting.Schema(CatalogName).ForRuntime();

                public RuntimeSetting<string> Tablespace => CatalogSettings.CatalogConfigurationSetting.Tablespace(CatalogName).ForRuntime();

                public RuntimeSetting<string> TablespaceIndex => CatalogSettings.CatalogConfigurationSetting.TablespaceIndex(CatalogName).ForRuntime();

                public RuntimeSetting<string> Username => CatalogSettings.CatalogConfigurationSetting.Username(CatalogName).ForRuntime();

                public RuntimeSetting<string> Password => CatalogSettings.CatalogConfigurationSetting.Password(CatalogName).ForRuntime();

                public Dictionary<string, object> All {
                    get {
                        var name = Name.GetValue();
                        if (name.IsNullOrEmpty() || name.Equals(Constants.MainDatabaseLogicalName)) {
                            return null;
                        }

                        var details = new Dictionary<string, object>();

                        var catalog = Catalog.GetValue();
                        if (!string.IsNullOrEmpty(catalog)) {
                            details["Catalog"] = catalog;
                        }

                        var schema = Schema.GetValue();
                        if (!string.IsNullOrEmpty(schema)) {
                            details["Schema"] = schema;
                        }

                        var tablespace = Tablespace.GetValue();
                        if (!string.IsNullOrEmpty(tablespace)) {
                            details["Tablespace"] = tablespace;
                        }

                        var tablespaceIndex = TablespaceIndex.GetValue();
                        if (!string.IsNullOrEmpty(tablespaceIndex)) {
                            details["TablespaceIndex"] = tablespaceIndex;
                        }

                        var username = Username.GetValue();
                        if (!string.IsNullOrEmpty(username)) {
                            details["Username"] = username;
                        }

                        var password = Password.GetValue();
                        if (!string.IsNullOrEmpty(password)) {
                            details["Password"] = password;
                        }

                        return details;
                    }
                }
            }

            public static CatalogConfigurationSetting Configuration(string catalogName) {
                return new CatalogConfigurationSetting(catalogName);
            }
        }

        public static class InternalNetwork {
            public static readonly RuntimeSetting<string> TrustedProxyAddresses = InternalNetworkSettings.TrustedProxyAddresses.ForRuntime();
            public static readonly RuntimeSetting<bool> EnableTrustedProxies = InternalNetworkSettings.EnableTrustedProxies.ForRuntime();
            public static readonly RuntimeSetting<bool> EnableBehaviour = InternalNetworkSettings.EnableBehaviour.ForRuntime();
            public static readonly RuntimeSetting<string> IPAdressList = InternalNetworkSettings.IPAdressList.ForRuntime();
            public static readonly RuntimeSetting<bool> EnableFallbackToFirstTrustedWhenAllForwardedIPsTrusted = InternalNetworkSettings.EnableFallbackToFirstTrustedWhenAllForwardedIPsTrusted.ForRuntime();
            // TODO jmt: deprecated
            public static readonly RuntimeSetting<string> IPAdresses = InternalNetworkSettings.IPAdresses.ForRuntime();
        }

        public static class Queries {
            public static readonly RuntimeSetting<int> SlowQueryInMs = QueriesSettings.SlowQueryInMs.ForRuntime();
            public static readonly RuntimeSetting<int> QueryRecursionLimit = QueriesSettings.QueryRecursionLimit.ForRuntime();
            public static readonly RuntimeSetting<int> QueryTimeout = QueriesSettings.QueryTimeout.ForRuntime();
        }

        public static class Debug {
            public static readonly RuntimeSetting<bool> UseShortRequestsOnDebugger = DebugSettings.UseShortRequestsOnDebugger.ForRuntime();
            // TODO jmt: not used in hubserver
            public static readonly RuntimeSetting<bool> AllowDebuggingMobileAppsFromAnyIP = DebugSettings.AllowDebuggingMobileAppsFromAnyIP.ForRuntime();
            public static readonly RuntimeSetting<bool> AllowDebuggingTraditionalAppsFromAnyIp = DebugSettings.AllowDebuggingTraditionalAppsFromAnyIp.ForRuntime();
            public static readonly RuntimeSetting<bool> DebugSetCurrentLocale = DebugSettings.DebugSetCurrentLocale.ForRuntime();
            public static readonly RuntimeSetting<bool> ForceClientSideTracing = DebugSettings.ForceClientSideTracing.ForRuntime();
        }

        public static class Authentication {
            public static readonly RuntimeSetting<bool> ForceSecureAlgorithmsInAuthentication = AuthenticationSettings.ForceSecureAlgorithmsInAuthentication.ForRuntime();
            public static readonly RuntimeSetting<bool> PasswordUpgradeOnLogin = AuthenticationSettings.PasswordUpgradeOnLogin.ForRuntime();
            public static readonly RuntimeSetting<int> RememberLoginTimeoutInDays = AuthenticationSettings.RememberLoginTimeoutInDays.ForRuntime();
            public static readonly RuntimeSetting<bool> UpdateUserLastLogin = AuthenticationSettings.UpdateUserLastLogin.ForRuntime();

            public static readonly RuntimeSetting<int> MobileLogin_Persistent_MaxIdleTimeInDays = AuthenticationSettings.MobileLogin_Persistent_MaxIdleTimeInDays.ForRuntime();
            public static readonly RuntimeSetting<int> MobileLogin_Persistent_CookieExpirationInDays = AuthenticationSettings.MobileLogin_Persistent_CookieExpirationInDays.ForRuntime();
            public static readonly RuntimeSetting<int> MobileLogin_Session_MaxIdleTimeInMinutes = AuthenticationSettings.MobileLogin_Session_MaxIdleTimeInMinutes.ForRuntime();
            public static readonly RuntimeSetting<int> MobileLogin_CacheTimeInMinutes = AuthenticationSettings.MobileLogin_CacheTimeInMinutes.ForRuntime();

            public static readonly RuntimeSetting<string> MobileLogin_AuthenticationHMACKey = AuthenticationSettings.MobileLogin_AuthenticationHMACKey.ForRuntime();
            public static readonly RuntimeSetting<string> MobileLogin_AuthenticationEncryptKey = AuthenticationSettings.MobileLogin_AuthenticationEncryptKey.ForRuntime();

            public static readonly RuntimeSetting<bool> EnforceSessionCookiesHttpOnly = AuthenticationSettings.EnforceSessionCookiesHttpOnly.ForRuntime();
            public static readonly RuntimeSetting<bool> EnforceSessionCookiesSecure = AuthenticationSettings.EnforceSessionCookiesSecure.ForRuntime();

            public static readonly RuntimeSetting<string> ReferencesAuthenticationKey = AuthenticationSettings.ReferencesAuthenticationKey.ForRuntime();
            public static readonly RuntimeSetting<string> ReferencesHashKey = AuthenticationSettings.ReferencesHashKey.ForRuntime();
            public static readonly RuntimeSetting<bool> ReferencesAllowLegacyAuth = AuthenticationSettings.ReferencesAllowLegacyAuth.ForRuntime();

            public static readonly RuntimeSetting<string> UsersAuthenticationKey = AuthenticationSettings.UsersAuthenticationKey.ForRuntime();
            public static readonly RuntimeSetting<string> UsersHashKey = AuthenticationSettings.UsersHashKey.ForRuntime();

            public static readonly RuntimeSetting<string> IdentityServerSignatureKey = AuthenticationSettings.IdentityServerSignatureKey.ForRuntime();

            public static readonly RuntimeSetting<bool> SSOBetweenRuntimes = AuthenticationSettings.SSOBetweenRuntimes.ForRuntime();
            public static readonly RuntimeSetting<bool> ForceSSOTraditionalPersistentLoginToken = AuthenticationSettings.ForceSSOTraditionalPersistentLoginToken.ForRuntime();
            public static readonly RuntimeSetting<bool> SSOSetRolesCookieInTraditionalLogin = AuthenticationSettings.SSOSetRolesCookieInTraditionalLogin.ForRuntime();

            // Just a last resort tentative fix for RPM-4878
            public static readonly RuntimeSetting<bool> DisableMaxAgeAnonymousCookies = AuthenticationSettings.DisableMaxAgeAnonymousCookies.ForRuntime();
            public static readonly RuntimeSetting<string> DisableMaxAgeAnonymousCookiesRegex = AuthenticationSettings.DisableMaxAgeAnonymousCookiesRegex.ForRuntime();

        }

        public static class Security {
            public static readonly RuntimeSetting<bool> EnforceValidTypesOnBinaryEndpoints = SecuritySettings.EnforceValidTypesOnBinaryEndpoints.ForRuntime(); //RRCT-2002
            public static readonly RuntimeSetting<bool> EnableSessionFixationProtection = SecuritySettings.EnableSessionFixationProtection.ForRuntime();
            public static readonly RuntimeSetting<int> SessionFixationAllowedOverlapWindowInSecs = SecuritySettings.SessionFixationAllowedOverlapWindowInSecs.ForRuntime();
            public static readonly RuntimeSetting<bool> DebugSessionFixationProtection = SecuritySettings.DebugSessionFixationProtection.ForRuntime();
            public static readonly RuntimeSetting<bool> EnableHSTS = SecuritySettings.EnableHSTS.ForRuntime();
            public static readonly RuntimeSetting<bool> EnableSecurityFeaturesISA = SecuritySettings.EnableSecurityFeaturesISA.ForRuntime();
            public static readonly RuntimeSetting<bool> RemoveNr2CookieUsername = SecuritySettings.RemoveNr2CookieUsername.ForRuntime();

            public static readonly RuntimeSetting<bool> EnableContentSecurityPolicy = SecuritySettings.EnableContentSecurityPolicy.ForRuntime();
            public static readonly RuntimeSetting<bool> ForceIntegrationSecurity = SecuritySettings.ForceIntegrationSecurity.ForRuntime();
            public static readonly RuntimeSetting<bool> ForceScreensSecurity = SecuritySettings.ForceScreensSecurity.ForRuntime();
            public static readonly RuntimeSetting<bool> ApplyCspRulesOnCompileTime = SecuritySettings.ApplyCspRulesOnCompileTime.ForRuntime();
        }

        public static class ContentSecurityPolicy {
            public static class Directives {
                public const string BaseUri = "base-uri";
                public const string ChildSource = "child-src";
                public const string ConnectSource = "connect-src";
                public const string DefaultSource = "default-src";
                public const string FontSource = "font-src";
                public const string ImageSource = "img-src";
                public const string MediaSource = "media-src";
                public const string ObjectSource = "object-src";
                public const string PluginTypes = "plugin-types";
                public const string ScriptSource = "script-src";
                public const string StyleSource = "style-src";
                public const string FrameAncestors = "frame-ancestors";
                public const string FrameSource = "frame-src";
                public const string ReportTo = "report-to";
                public const string ReportUri = "report-uri";
                public const string Other = "other";
            }

            public static readonly RuntimeSetting<string> BaseUri = ContentSecurityPolicySettings.BaseUri.ForRuntime();
            public static readonly RuntimeSetting<string> ChildSource = ContentSecurityPolicySettings.ChildSource.ForRuntime();
            public static readonly RuntimeSetting<string> ConnectSource = ContentSecurityPolicySettings.ConnectSource.ForRuntime();
            public static readonly RuntimeSetting<string> DefaultSource = ContentSecurityPolicySettings.DefaultSource.ForRuntime();
            public static readonly RuntimeSetting<string> FontSource = ContentSecurityPolicySettings.FontSource.ForRuntime();
            public static readonly RuntimeSetting<string> FrameAncestors = ContentSecurityPolicySettings.FrameAncestors.ForRuntime();
            public static readonly RuntimeSetting<string> ImageSource = ContentSecurityPolicySettings.ImageSource.ForRuntime();
            public static readonly RuntimeSetting<string> MediaSource = ContentSecurityPolicySettings.MediaSource.ForRuntime();
            public static readonly RuntimeSetting<string> ObjectSource = ContentSecurityPolicySettings.ObjectSource.ForRuntime();
            public static readonly RuntimeSetting<string> Other = ContentSecurityPolicySettings.Other.ForRuntime();
            public static readonly RuntimeSetting<string> PluginTypes = ContentSecurityPolicySettings.PluginTypes.ForRuntime();
            public static readonly RuntimeSetting<string> ScriptSource = ContentSecurityPolicySettings.ScriptSource.ForRuntime();
            public static readonly RuntimeSetting<string> StyleSource = ContentSecurityPolicySettings.StyleSource.ForRuntime();
            public static readonly RuntimeSetting<string> ReportTo = ContentSecurityPolicySettings.ReportTo.ForRuntime();
        }

        public static class EMail {
            public static readonly RuntimeSetting<string> DefaultDnsName = EMailSettings.DefaultDnsName.ForRuntime();

            public static readonly RuntimeSetting<string> ServerHost = EMailSettings.ServerHost.ForRuntime();
            public static readonly RuntimeSetting<string> DefaultOriginator = EMailSettings.DefaultOriginator.ForRuntime();
            public static readonly RuntimeSetting<string> DefaultOriginatorName = EMailSettings.DefaultOriginatorName.ForRuntime();
            public static readonly RuntimeSetting<bool> EnableEmails = EMailSettings.EnableEmails.ForRuntime();
            public static readonly RuntimeSetting<string> TestEmails = EMailSettings.TestEmails.ForRuntime();
            public static readonly RuntimeSetting<string> UrlsToExcludeOnRender = EMailSettings.UrlsToExcludeOnRender.ForRuntime();

            // TODO jmt: no uses found in hubserver
            public static readonly RuntimeSetting<string> DefaultOriginatorCustomLogQueuePath = EMailSettings.DefaultOriginatorCustomLogQueuePath.ForRuntime();
        }

        public static class BPT {
            public static readonly RuntimeSetting<int> ProcessBackoffRetrybaseSec = BPTSettings.ProcessBackoffRetrybaseSec.ForRuntime();
            public static readonly RuntimeSetting<double> ProcessBackoffConstant = BPTSettings.ProcessBackoffConstant.ForRuntime();
            public static readonly RuntimeSetting<int> ActivitiesTimeout = BPTSettings.ActivitiesTimeout.ForRuntime();
            public static readonly RuntimeSetting<int> AutomaticActivitiesTimeout = BPTSettings.AutomaticActivitiesTimeout.ForRuntime();
            public static readonly RuntimeSetting<bool> GetUserRolesForEPAByJoin = BPTSettings.GetUserRolesForEPAByJoin.ForRuntime();
        }

        public static class Timers {
            public static readonly RuntimeSetting<int> NumberOfRetries = TimersSettings.NumberOfRetries.ForRuntime();
        }

        public static class SMS {
            public static readonly RuntimeSetting<int?> BulkSmsMaxDestinations = SMSSettings.BulkSmsMaxDestinations.ForRuntime();
        }

        public static class Sandbox {
            public static readonly RuntimeSetting<bool> SandboxOperating = SandboxSettings.SandboxOperating.ForRuntime();
            public static readonly RuntimeSetting<string> SandboxBoxesKeyName = SandboxSettings.SandboxBoxesKeyName.ForRuntime();
            public static readonly RuntimeSetting<string> SandboxEmailQueuePath = SandboxSettings.SandboxEmailQueuePath.ForRuntime();
            public static readonly RuntimeSetting<int> SandboxQueueMessagesMaxAge = SandboxSettings.SandboxQueueMessagesMaxAge.ForRuntime();
        }

        public static class Processes {
            // Max time to wait for a conditional start to reach the ready state when invoking and explicit startactivity
            public static readonly RuntimeSetting<int> StartActivityReadyWaitTimeInSeconds = ProcessesSettings.StartActivityReadyWaitTimeInSeconds.ForRuntime();

            // When set, regular conditional start listeners are created on demand when invoking the explicit startactivity.
            // Conditional starts that register event listeners or have a child onready callback are not delayed even when this
            // setting is set to true.
            public static readonly RuntimeSetting<bool> ConditionalStartListenersCreatedOnDemand = ProcessesSettings.ConditionalStartListenersCreatedOnDemand.ForRuntime();

            // When enabled, allows to use lightweight processes (with a Start -> Automatic Activity -> End structure) that handle a database event,
            // using a fast execution engine.
            public static readonly RuntimeSetting<bool> EnableLightProcessExecution = ProcessesSettings.EnableLightProcessExecution.ForRuntime();
            public static readonly RuntimeSetting<bool> EnableImprovedDequeueEvent = ProcessesSettings.EnableImprovedDequeueEvent.ForRuntime();
        }

        public static class ViewState {
            public static readonly RuntimeSetting<bool> EncryptViewState = ViewStateSettings.EncryptViewState.ForRuntime();
            public static readonly RuntimeSetting<bool> EncryptViewStateWithVisitorId = ViewStateSettings.EncryptViewStateWithVisitorId.ForRuntime();
            public static readonly RuntimeSetting<bool> EncryptViewStateWithUserId = ViewStateSettings.EncryptViewStateWithUserId.ForRuntime();
            public static readonly RuntimeSetting<bool> EncryptViewStateWithSessionToken = ViewStateSettings.EncryptViewStateWithSessionToken.ForRuntime();
            public static readonly RuntimeSetting<bool> AllowQueryStringViewState = ViewStateSettings.AllowQueryStringViewState.ForRuntime();
        }

        public static class Entity {
            public static string GetSettingKey(string ownerKey, string entityKey, string settingName) =>
                EntitySettings.GetSettingKey(ownerKey, entityKey, settingName);

            public static RuntimeSetting<T> GetSetting<T>(string ownerKey, string entityKey, string settingName, T defaultValue, bool isEncrypted = false) =>
                EntitySettings.GetSetting(ownerKey, entityKey, settingName, defaultValue, isEncrypted).ForRuntime();
        }

        public static class ExternalConnections {
            public static string BaseKey = ExternalConnectionsSettings.BaseKey;

            public class DBConnectionSetting {
                private string DBConnectionname { get; set; }

                public DBConnectionSetting(string dbConnectionName) {
                    this.DBConnectionname = dbConnectionName;
                }

                public RuntimeSetting<string> DBConnection => ExternalConnectionsSettings.DBConnectionSetting.DBConnection(DBConnectionname).ForRuntime();

                public string GetKey() => ExternalConnectionsSettings.DBConnectionSetting.DBConnection(DBConnectionname).Key;
            }
        }

        public static class Fixes {
            // RPD-3565 advance query flag to control the fix of literals being misinterpreted as identifiers
            public static readonly RuntimeSetting<bool> LiteralsMisinterpretedAsIdentifiers = FixesSettings.LiteralsMisinterpretedAsIdentifiers.ForRuntime();
        }

        private static volatile bool appSettingsNeedInitialization = true;
        private static readonly object appSettingsInitilizationLock = new object();

        public static void SafeInitializeAppSettings() {
            try {
                if (appSettingsNeedInitialization) {
                    lock (appSettingsInitilizationLock) {
                        if (appSettingsNeedInitialization) {
                            using (OSTrace.Timer("AppSettings initialization")) {
                                var filePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "appSettings.config");
                                InitializeAppSettings(filePath);
                            }
                            appSettingsNeedInitialization = false;
                        }
                    }
                }
            } catch (Exception e) {
                try {
                    OSTrace.Debug("An error occurred during AppSettings initialization.", e);
                } catch {
                    // Do nothing. We failed at logging but we don't want to kill the app start-up.
                }
            }
        }

        private static void InitializeAppSettings(string filePath) {
            OSTrace.Debug($"There are {ConfigurationManager.AppSettings.Count} settings loaded before AppSettings initialization.");
            var xmlContent = new XmlDocument();
            xmlContent.Load(filePath);
            var nodeList = xmlContent.SelectSingleNode("appSettings").ChildNodes;
            foreach (XmlNode node in nodeList) {
                var key = node.Attributes["key"]?.Value;
                if (!key.IsEmpty()) {
                    if (ConfigurationManager.AppSettings[key] != null) {
                        OSTrace.Debug($"Overriding initialization of AppSetting '{key}'.");
                    }
                    ConfigurationManager.AppSettings[key] = node.Attributes["value"] == null ? string.Empty : node.Attributes["value"].Value;
                    // TODO: support <remove> and <clear> tags in case the platform ever generates/needs them.
                }
            }
            OSTrace.Debug($"There are {ConfigurationManager.AppSettings.Count} settings loaded after AppSettings initialization.");
        }
    }

    public static class RuntimePlatformSettingsExtensions {
        public static RuntimeSetting<T> ForRuntime<T>(this ISetting<T> setting) {
            return ForRuntime(setting, setting.DefaultValue);
        }

        public static RuntimeSetting<T> ForRuntime<T>(this ISetting<T> setting, T defaultValue) {
            return new RuntimeSetting<T>(setting.Key, defaultValue, setting.IsEncrypted);

        }
    }
}
