/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.RuntimeCommon.Caching;
using OutSystems.RuntimeCommon.Settings;

namespace OutSystems.HubEdition.RuntimePlatform {
    public class ServerSideCache : ICache {
        private readonly ICache cacheImplementation;
        private ISettingsProvider settingsProvider;
        private CachePluginProvider pluginProvider;

        public ServerSideCache(ISettingsProvider settingsProvider, CachePluginProvider pluginProvider, string cacheInstanceKey = null) {
            this.settingsProvider = settingsProvider;
            this.pluginProvider = pluginProvider;

            if (settingsProvider.Get(RuntimePlatformSettings.Plugin.CacheInvalidation.EnableRabbitMQCacheInvalidation)) {
                cacheImplementation = GetCacheImplementation(RuntimePlatformSettings.Plugin.CacheInvalidation.CacheProviderKey, cacheInstanceKey);
            }

            if (cacheImplementation == null) {
                cacheImplementation = GetCacheImplementation(RuntimePlatformSettings.Plugin.CacheInvalidation.FileBasedCacheProviderKey, cacheInstanceKey);
            }
        }

        public void Clear() {
            cacheImplementation.Clear();
        }

        public void Listen(ICacheKey key, ICacheDependency dependency, CacheItemInvalidationCallback invalidationCallback) {
            cacheImplementation.Listen(key, dependency, invalidationCallback);
        }

        public object StopListen(ICacheKey key) {
            return cacheImplementation.StopListen(key);
        }

        public void Invalidate(ICacheInvalidationKey invalidationKey) {
            cacheImplementation.Invalidate(invalidationKey);
        }

        public void Add(ICacheKey key, object value, ICacheDependency dependency, DateTime expirationDate, TimeSpan slidingSpan, CacheItemPriority priority) {
            cacheImplementation.Add(key, value, dependency, expirationDate, slidingSpan, priority);
        }

        public object Get(ICacheKey key) {
            return cacheImplementation.Get(key);
        }

        public object GetOrAdd(ICacheKey key, CacheItemValueGetter getter, ICacheDependency dependency, DateTime expirationDate, TimeSpan slidingSpan, CacheItemPriority priority) {
            return cacheImplementation.GetOrAdd(key, getter, dependency, expirationDate, slidingSpan, priority);
        }

        public bool IsAvailable() {
            return cacheImplementation.IsAvailable();
        }

        public bool IsAvailable(out Exception ex) {
            return cacheImplementation.IsAvailable(out ex);
        }

        public void Dispose() {
            cacheImplementation?.Dispose();
        }

        private ICache GetCacheImplementation(RuntimeSetting<string> providerKeyName, string cacheInstanceKey) {
            var provider = pluginProvider.GetImplementation(settingsProvider.Get(providerKeyName), (_) => null);
            return provider?.GetImplementation(settingsProvider, cacheInstanceKey);
        }
    }
}
