/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.IO;
using System.Text;
using System.Web.UI;
using OutSystems.Application.Core;
using ICSharpCode.SharpZipLib.Zip.Compression;
using ICSharpCode.SharpZipLib.Zip.Compression.Streams;
using OutSystems.HubEdition.RuntimePlatform;
using OutSystems.HubEdition.RuntimePlatform.Log;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.WebWidgets {
    public abstract class OSPageViewStateCompressed : OSPageViewState {
        private static readonly string DefaultLoggingModuleName = nameof(OSPageViewStateCompressed);

        // RPD-4181 - Cypher ViewState with session token to prevent CSRF attacks
        private const string VS_SESSION_TOKEN_USER_ID = "ViewStateSessionTokenUserId";
        private const string VS_SESSION_TOKEN = "ViewStateSessionToken";

        protected OSPageViewStateCompressed(bool quirksMode) : base(quirksMode) { }

        private byte[] CompressBinary(byte[] input) {
            var inputBuffer = new MemoryStream(input, 0, input.Length);
            var outputBuffer = new MemoryStream();
            var compressor = new DeflaterOutputStream(outputBuffer, new Deflater(Deflater.BEST_COMPRESSION, false));
            StreamUtils.PumpStream(inputBuffer, compressor);
            inputBuffer.Close();
            compressor.Close();
            return outputBuffer.ToArray();
        }

        private byte[] DecompressBinary(byte[] input) {
            var inputBuffer = new MemoryStream(input, 0, input.Length);
            var decompressor = new InflaterInputStream(inputBuffer);
            var outputBuffer = new MemoryStream();
            StreamUtils.PumpStream(decompressor, outputBuffer);
            decompressor.Close();
            outputBuffer.Close();
            return outputBuffer.ToArray();
        }

        protected override object DeserializeViewState(string viewState, out string hash) {
            HeContext context = null;
            try { context = AppInfo.GetAppInfo().OsContext; } catch { }

            OutSystems.HubEdition.RuntimePlatform.RuntimePlatformUtils.SetViewstateSize(viewState.Length);
            byte[] bytes = Array.Empty<byte>();
            int sizeDecompressed = 0;
            int sizeCompressed = 0;

            try {
                if (viewState.Length == 0) {
                    if (RuntimePlatformSettings.ViewState.EncryptViewState.GetValue()) {
                        throw new Exception("Missing viewstate");
                    }
                } else {
                    bytes = Convert.FromBase64String(viewState);
                    if (RuntimePlatformSettings.ViewState.EncryptViewState.GetValue()) {
                        bytes = AuthenticatedEncryptionWithAssociatedData.Instance.Decrypt(bytes, GetAssociatedData(toSerialize: false));
                    }
                    sizeCompressed = bytes.Length;
                    bytes = DecompressBinary(bytes);
                    sizeDecompressed = bytes.Length;
                }

                return base.DeserializeViewState(Convert.ToBase64String(bytes), out hash);

            } catch (Exception excep) {
                string extraInfo = "";
          
                if (excep.Message.Equals("Cannot decrypt content")) {
                    extraInfo = "Unexpected ViewState size received.";             
                }
                else if (excep.Message.Equals("Cannot decrypt the content")) { 
                    bool isUsingVisitorId = RuntimePlatformSettings.ViewState.EncryptViewStateWithVisitorId.GetValue();
                    bool isUsingSessionToken = RuntimePlatformSettings.ViewState.EncryptViewStateWithSessionToken.GetValue();
                    bool isUsingUserId = RuntimePlatformSettings.ViewState.EncryptViewStateWithUserId.GetValue();
                    extraInfo = $"Unexpected encrypted ViewState received considering the current control values:{(isUsingVisitorId ? " (VisitorId)" : "")}{(isUsingSessionToken ? " (SessionToken)" : "")}{(isUsingUserId ? " (UserId)" : "")}.";
                }

                string pageName = "";
                try { pageName = context.CurrentScreen.ToString(); } catch { }
                try {
                    var errorMessage = $"Error Deserializing ViewState of page \"{pageName}\", visitorid \"{AppInfo.GetAppInfo().VisitorId.FormatSensitiveString()}\", size {viewState.Length} bytes (\"{viewState.Substring(0, Math.Min(10, viewState.Length))}...\"). \n{extraInfo}";
                    ErrorLog.LogApplicationError(errorMessage, excep, context, "Global");
                    OSTrace.Error(errorMessage, excep);
                } catch { }

                throw;

            } finally {
                context?.ApplicationLogger?.LogTrace($"[DeserializeViewState] Viewstate size {viewState.Length} bytes (\"{viewState.Substring(0, Math.Min(10, viewState.Length))}...\"), {sizeDecompressed} bytes decompressed, {sizeCompressed} bytes compressed.", DefaultLoggingModuleName);
            }
        }

        private static readonly Lazy<RandomGenerator> random = new Lazy<RandomGenerator>(
            () => RandomGenerator.GetSecureRandomGenerator()
        );

        private byte[] GetAssociatedData(bool toSerialize) {

            string visitorId = null;
            string vsUserId = null;
            string sessionToken = null;

            if (RuntimePlatformSettings.ViewState.EncryptViewStateWithVisitorId.GetValue()) {
                visitorId = AppInfo.GetAppInfo().VisitorId;
            }

            var osContext = AppInfo.GetAppInfo().OsContext;

            if (osContext != null && osContext.Session != null) {
                var userId = osContext.Session.UserId.ToString();

                // RPD-4181 - Cypher ViewState with session token to prevent CSRF attacks
                // Ignores the unauthenticated sessions (UserId = 0), this exception is because of the kiosks use case
                if (userId != "0" && RuntimePlatformSettings.ViewState.EncryptViewStateWithSessionToken.GetValue()) {
                    if (string.IsNullOrEmpty((string)osContext.Session[VS_SESSION_TOKEN]) ||
                        !string.Equals((string)osContext.Session[VS_SESSION_TOKEN_USER_ID], userId)) {
                        osContext.Session[VS_SESSION_TOKEN] = String.Empty + random.Value.NextULong() + random.Value.NextULong();
                        osContext.Session[VS_SESSION_TOKEN_USER_ID] = userId;
                    }
                    sessionToken = (string)osContext.Session[VS_SESSION_TOKEN];
                }

                if (RuntimePlatformSettings.ViewState.EncryptViewStateWithUserId.GetValue()) {
                    vsUserId = userId;
                }
            }

            if (visitorId == null && vsUserId == null && sessionToken == null) {
                return null;
            }

            osContext?.ApplicationLogger?.LogTrace($"[GetAssociatedData] Data used to {(toSerialize ? "" : "de")}serialize viewstate{(osContext.IsAjaxRequest ? " (for Ajax Request)" :"")}: Visitor({(visitorId != null ? $"true, '{visitorId.FormatSensitiveString()}'" : "false")}), UserId({(vsUserId != null ? "true" : "false")}), SessionToken({(sessionToken != null ? $"true, '{sessionToken.FormatSensitiveString()}'" : "false")})", DefaultLoggingModuleName);

            return Encoding.UTF8.GetBytes((visitorId ?? "") + (vsUserId ?? "") + (sessionToken ?? ""));
        }

        protected override string SerializeViewState(object viewState, out string hash) {
            int sizeDecompressed;
            int sizeCompressed;

            byte[] bytes = Convert.FromBase64String(base.SerializeViewState(viewState, out hash));
            sizeDecompressed = bytes.Length;

            bytes = CompressBinary(bytes);
            sizeCompressed = bytes.Length;

            if (RuntimePlatformSettings.ViewState.EncryptViewState.GetValue()) {
                bytes = AuthenticatedEncryptionWithAssociatedData.Instance.Encrypt(bytes, GetAssociatedData(toSerialize: true));
            }

            string serializedViewState = Convert.ToBase64String(bytes);

            AppInfo.GetAppInfo().OsContext?.ApplicationLogger?.LogTrace($"[SerializeViewState] Viewstate size {serializedViewState.Length} bytes (\"{serializedViewState.Substring(0, Math.Min(10, serializedViewState.Length))}...\"), {sizeDecompressed} bytes decompressed, {sizeCompressed} bytes compressed.", DefaultLoggingModuleName);
            return serializedViewState;
        }
    }
}
