/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System.Globalization;
using OutSystems.HubEdition.Extensibility.Data.DMLService.DMLPlaceholders;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.Extensibility.Data.DMLService {
    public static class DMLExtensions {
        public static string GetMaxRecordsSQL(this IDMLQueries queries, int maxRecords, string selectSQL, string fromSQL, string whereSQL) {
            return GetMaxRecordsSQL(queries, maxRecords, selectSQL, fromSQL, whereSQL, null);
        }

        public static string GetMaxRecordsSQL(this IDMLQueries queries, int maxRecords, string selectSQL, string fromSQL, string whereSQL, string orderBySQL) {
            var placeholders = queries.SQLPlaceholderValuesForMaxRecords(maxRecords.ToString(CultureInfo.InvariantCulture));
            string beforeStatement = placeholders.GetPlaceholderValue(SelectPlaceholder.BeforeStatement);
            string afterSelect = placeholders.GetPlaceholderValue(SelectPlaceholder.AfterSelectKeyword);
            string beforeFrom = placeholders.GetPlaceholderValue(SelectPlaceholder.BeforeFromKeyword);
            string afterFrom = placeholders.GetPlaceholderValue(SelectPlaceholder.AfterFromKeyword);
            string beforeWhere = placeholders.GetPlaceholderValue(SelectPlaceholder.BeforeWhereKeyword);
            string afterWhere = placeholders.GetPlaceholderValue(SelectPlaceholder.AfterWhereKeyword);
            string beforeOrderBy = placeholders.GetPlaceholderValue(SelectPlaceholder.BeforeOrderByKeyword);
            string afterOrderBy = placeholders.GetPlaceholderValue(SelectPlaceholder.AfterOrderByKeyword);
            string afterStatement = placeholders.GetPlaceholderValue(SelectPlaceholder.AfterStatement);
            
            return
                $"{beforeStatement} SELECT {afterSelect} {selectSQL} {beforeFrom} " +
                $"FROM {afterFrom} {fromSQL} {beforeWhere} " +
                $"WHERE {afterWhere} {whereSQL} {(orderBySQL.IsNullOrEmpty() ? "" : $"{beforeOrderBy} ORDER BY {afterOrderBy} {orderBySQL}")} " +
                $"{afterStatement}";
        }

        public static string GetCountSQL(this IDMLQueries queries, string sqlStatement) {
            var placeholders = queries.SQLPlaceholderValuesForCountQuery();
            string beforeStatement = placeholders.GetPlaceholderValue(StatementPlaceholder.BeforeStatement);
            string afterStatement = placeholders.GetPlaceholderValue(StatementPlaceholder.AfterStatement);
            return $"{beforeStatement} {sqlStatement} {afterStatement}";
        }
    }
}
